#!/bin/sh

PATH=$PATH:/bin
export PATH

lines=`cat $0 | wc -l`
lines=`expr $lines - 17`
tail -$lines $0 > /tmp/runperl$$
echo "# $0 $*" >> /tmp/runperl$$
while [ $# -ne 0 ]
do
    line=$1
    shift
    totline="$totline\`$line"
done
exec perl /tmp/runperl$$ $0 $totline

# Perl begins here

unlink("$0");

# strippath separates a fully-expanded filename into its path and file
# parts.  If the fully-expanded filename does not have a path componenent, a
# NULL string is returned as the path.  The returned value is a list with the
# filename first and the path second, so that you can ignore the path if
# you like:
#           ($file) = &strippath($bigname);

sub strippath
{
    local($fullname) = @_;

    $fullname =~ m|^(.*/)?([^/]*)$|;
    ($path,$file) = ($1,$2);
    return($file,$path);
}

($0) = &strippath(shift);

$args = "@ARGV";
$args =~ s/^.//;
@ARGV = split('\`',$args);

# Real code begins here

use Env;

# Get the name of the new branch.
open(NB,"/home/meshtv/next_release_branch");
($full_new_release_branch,$new_release_label) = (<NB> =~ /^(\S+)\s+(\S+)/);
close(NB);
($new_release_branch) = ($full_new_release_branch =~ m|^/main/(.*)$|);

# Get the name of the current branch
open(NB,"/home/meshtv/current_release_branch");
($full_current_release_branch,$current_release_label) = (<NB> =~
/^(\S+)\s+(\S+)/);
close(NB);
($current_release_branch) = ($full_current_release_branch =~ m|^/main/(.*)$|);

$USER = $1;
$cleartool = "/usr/atria/bin/cleartool";
$branch_name = $ENV{'CLEARCASE_BRTYPE_NAME'};
if (($branch_name eq "main") || ($branch_name eq "$new_release_branch") || ($branch_name eq "$current_release_branch"))
{
    # We don't need to check these branches.
    exit;
}

# Look for all elements that have an attribute of type SingleBranchName
$att_elements =
    `$cleartool find /MeshTV_vob -element "attype(SingleBranchName)" -print`;
exit(0) if ($att_elements =~ /^\s*$/);

# Check for the $branch_name value in each of these elements.
@att_elements = split('\n',$att_elements);
foreach $element (@att_elements)
{
    $value = `$cleartool desc -fmt "%NS[SingleBranchName]a" $element`;
    $value =~ s/"//g;
    if ($value eq $branch_name)
    {
        $status = system("$cleartool rmattr SingleBranchName $element");
        $status /= 256;
        exit($status) if ($status != 0);
    }
}
exit(0);
