#!/bin/sh

lines=`cat $0 | wc -l`
lines=`expr $lines - 14`
tail -$lines $0 > /tmp/runperl$$
echo "# $0 $*" >> /tmp/runperl$$
while [ $# -ne 0 ]
do
    line=$1
    shift
    totline="$totline\`$line"
done
exec perl /tmp/runperl$$ $0 $totline

unlink($0);

sub strippath
{
    local($fullname) = @_;

    $fullname =~ m|^(.*/)?([^/]*)$|;
    ($path,$file) = ($1,$2);
    return($file,$path);
}

($0) = &strippath(shift);

$args = "@ARGV";
$args =~ s/^.//;
@ARGV = split('\`',$args);

use Env;

$USER = $1;
$cleartool = "/usr/atria/bin/cleartool";
$file = $ENV{'CLEARCASE_PNAME'};
$branch = $ENV{'CLEARCASE_BRTYPE_NAME'};

# Check to see if the file is a directory.
if (-d $file)
{
    # Directories have no processing done to them, so we're fine.
    exit(0);
}

if ($branch !~ /Release/)
{
    # See if this file has an attribute of type SingleBranchName with the value
    # of the branch name.  (It should.)
    $current_attr = `$cleartool desc -fmt \"%NS[SingleBranchName]a" $file@@`;
    $current_attr =~ s/"//g;

    if ($current_attr eq "")
    {
        print STDERR <<"EOF";
ERROR: Element "$file@@" doesn't have an attribute of type
"SingleBranchName".  It should.  This signifies an error in the locking
mechanism.  Please contact Sean Ahern and let him know about the problem.
EOF
        exit(1);
    } elsif ($current_attr ne $branch)
    {
        $conflicting_user = `$cleartool desc -fmt "%Fu" -type brtype:$current_attr`;
        print STDERR <<"EOF";
WARNING:  $conflicting_user was modifying "$file" on branch
"$current_attr" while you had it on your branch "$branch".
This is not a problem since you are currently removing
branch "$branch", but this condition should never have occurred.
Check with Sean Ahern to see if there are other problems with this branch.
EOF
        exit(1);
    } else {
        $status = system("$cleartool rmattr SingleBranchName $file@@");
        $status /= 256;
    }
}
else {
    # Swap the ReleaseBranch attribute for the OldReleaseBranch attribute, if it 
    # exists.  If it doesn't, just remove the ReleaseBranch attribute.
    if ($branch =~ /Release/)
    {
        # Check to see if there's an OldReleaseBranch attribute.
        $oldreleaseattr = `$cleartool desc -fmt \"%NS[OldReleaseBranch]a" $file@@`;
        $oldreleaseattr =~ s/"//g;

        if ($oldreleaseattr ne "")
        {
            $status = system $cleartool, "mkattr", "-replace", "ReleaseBranch",
                             "\"$oldreleaseattr\"", "$file@@";
            $status /= 256;
            $status = system("$cleartool rmattr OldReleaseBranch $file@@");
            $status /= 256;
        } else
        {
            $status = system("$cleartool rmattr ReleaseBranch $file@@");
            $status /= 256;
        }
    }
}

exit($status);
