title: Silo

description: >
  An API for reading and writing a wide diversity of binary, scientific data to be easily shared and exchanged.
  Silo is prominently used by the VisIt visualization tool.

theme: minima

minima:
  skin: solarized

# we exclude a lot to keep generation process fast. None of this stuff is needed
# to generate the site.
exclude: [CMake, config, config-site, docs, resources, src, svn_bin, tests, tools]

show_downloads: false

# This plugin needed to generate main landing page, index.html, from README.md
plugins:
  - jekyll-readme-index

readme_index:
  enabled:          true
  remove_originals: false
  with_frontmatter: true

header_pages:
  - ghpages/releases.md
  - ghpages/examples.md
  - ghpages/help.md
  - ghpages/documentation.md
  - ghpages/more.md
