/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <rpc/rpc.h>
#include "sdxproto.h"

bool_t
xdr_request_type(XDR *xdrs, request_type *objp)
{
	if (!xdr_enum(xdrs, (enum_t *)objp)) {
		return (FALSE);
	}
	return (TRUE);
}

bool_t
xdr_reply_type(XDR *xdrs, reply_type *objp)
{
	if (!xdr_enum(xdrs, (enum_t *)objp)) {
		return (FALSE);
	}
	return (TRUE);
}

bool_t
xdr_SDXreadvar(XDR *xdrs, SDXreadvar *objp)
{
	if (!xdr_int(xdrs, &objp->type)) {
		return (FALSE);
	}
	if (!xdr_vector(xdrs, (char *)objp->varname, MAXSTRLEN, sizeof(char), (xdrproc_t) xdr_char)) {
		return (FALSE);
	}
	return (TRUE);
}

bool_t
xdr_request_info(XDR *xdrs, request_info *objp)
{
	if (!xdr_request_type(xdrs, &objp->request)) {
		return (FALSE);
	}
	switch (objp->request) {
	case READVAR:
		if (!xdr_SDXreadvar(xdrs, &objp->request_info_u.read)) {
			return (FALSE);
		}
		break;
	}
	return (TRUE);
}

bool_t
xdr_SDXrequest(XDR *xdrs, SDXrequest *objp)
{
	if (!xdr_int(xdrs, &objp->type)) {
		return (FALSE);
	}
	if (!xdr_request_info(xdrs, &objp->info)) {
		return (FALSE);
	}
	return (TRUE);
}

bool_t
xdr_reply_info(XDR *xdrs, reply_info *objp)
{
	if (!xdr_reply_type(xdrs, &objp->reply)) {
		return (FALSE);
	}
	switch (objp->reply) {
	case OK:
		break;
	case ERROR:
		if (!xdr_int(xdrs, &objp->reply_info_u.errorno)) {
			return (FALSE);
		}
		break;
	default:
		return (FALSE);
	}
	return (TRUE);
}

bool_t
xdr_SDXreply(XDR *xdrs, SDXreply *objp)
{
	if (!xdr_reply_info(xdrs, &objp->info)) {
		return (FALSE);
	}
	return (TRUE);
}

bool_t
xdr_connect_type(XDR *xdrs, connect_type *objp)
{
	if (!xdr_enum(xdrs, (enum_t *)objp)) {
		return (FALSE);
	}
	return (TRUE);
}

bool_t
xdr_SDXcontrol(XDR *xdrs, SDXcontrol *objp)
{
	if (!xdr_vector(xdrs, (char *)objp->username, MAXSTRLEN, sizeof(char), (xdrproc_t) xdr_char)) {
		return (FALSE);
	}
	return (TRUE);
}

bool_t
xdr_SDXopen(XDR *xdrs, SDXopen *objp)
{
	if (!xdr_vector(xdrs, (char *)objp->username, MAXSTRLEN, sizeof(char), (xdrproc_t) xdr_char)) {
		return (FALSE);
	}
	if (!xdr_vector(xdrs, (char *)objp->idstring, MAXSTRLEN, sizeof(char), (xdrproc_t) xdr_char)) {
		return (FALSE);
	}
	return (TRUE);
}

bool_t
xdr_SDXserver(XDR *xdrs, SDXserver *objp)
{
	if (!xdr_vector(xdrs, (char *)objp->username, MAXSTRLEN, sizeof(char), (xdrproc_t) xdr_char)) {
		return (FALSE);
	}
	if (!xdr_vector(xdrs, (char *)objp->idstring, MAXSTRLEN, sizeof(char), (xdrproc_t) xdr_char)) {
		return (FALSE);
	}
	if (!xdr_int(xdrs, &objp->nvar)) {
		return (FALSE);
	}
	if (!xdr_array(xdrs, (char **)&objp->varnames.varnames_val, (u_int *)&objp->varnames.varnames_len, ~0, sizeof(char), (xdrproc_t) xdr_char)) {
		return (FALSE);
	}
	if (!xdr_array(xdrs, (char **)&objp->meshnames.meshnames_val, (u_int *)&objp->meshnames.meshnames_len, ~0, sizeof(char), (xdrproc_t) xdr_char)) {
		return (FALSE);
	}
	if (!xdr_array(xdrs, (char **)&objp->vartypes.vartypes_val, (u_int *)&objp->vartypes.vartypes_len, ~0, sizeof(int), (xdrproc_t) xdr_int)) {
		return (FALSE);
	}
	if (!xdr_int(xdrs, &objp->nmats)) {
		return (FALSE);
	}
	if (!xdr_int(xdrs, &objp->nblocks)) {
		return (FALSE);
	}
	return (TRUE);
}

bool_t
xdr_connect_info(XDR *xdrs, connect_info *objp)
{
	if (!xdr_connect_type(xdrs, &objp->connect)) {
		return (FALSE);
	}
	switch (objp->connect) {
	case CONTROL_CONNECT:
		if (!xdr_SDXcontrol(xdrs, &objp->connect_info_u.control)) {
			return (FALSE);
		}
		break;
	case OPEN_CONNECT:
		if (!xdr_SDXopen(xdrs, &objp->connect_info_u.open)) {
			return (FALSE);
		}
		break;
	case SERVER_CONNECT:
		if (!xdr_SDXserver(xdrs, &objp->connect_info_u.server)) {
			return (FALSE);
		}
		break;
	}
	return (TRUE);
}

bool_t
xdr_SDXconnect(XDR *xdrs, SDXconnect *objp)
{
	if (!xdr_int(xdrs, &objp->type)) {
		return (FALSE);
	}
	if (!xdr_connect_info(xdrs, &objp->info)) {
		return (FALSE);
	}
	return (TRUE);
}

bool_t
xdr_SDXcontrolinfo(XDR *xdrs, SDXcontrolinfo *objp)
{
	if (!xdr_int(xdrs, &objp->nservers)) {
		return (FALSE);
	}
	if (!xdr_array(xdrs, (char **)&objp->idstrings.idstrings_val, (u_int *)&objp->idstrings.idstrings_len, ~0, sizeof(char), (xdrproc_t) xdr_char)) {
		return (FALSE);
	}
	if (!xdr_array(xdrs, (char **)&objp->nvars.nvars_val, (u_int *)&objp->nvars.nvars_len, ~0, sizeof(int), (xdrproc_t) xdr_int)) {
		return (FALSE);
	}
	if (!xdr_array(xdrs, (char **)&objp->varnames.varnames_val, (u_int *)&objp->varnames.varnames_len, ~0, sizeof(char), (xdrproc_t) xdr_char)) {
		return (FALSE);
	}
	if (!xdr_array(xdrs, (char **)&objp->vartypes.vartypes_val, (u_int *)&objp->vartypes.vartypes_len, ~0, sizeof(int), (xdrproc_t) xdr_int)) {
		return (FALSE);
	}
	if (!xdr_array(xdrs, (char **)&objp->nmats.nmats_val, (u_int *)&objp->nmats.nmats_len, ~0, sizeof(int), (xdrproc_t) xdr_int)) {
		return (FALSE);
	}
	if (!xdr_array(xdrs, (char **)&objp->nblocks.nblocks_val, (u_int *)&objp->nblocks.nblocks_len, ~0, sizeof(int), (xdrproc_t) xdr_int)) {
		return (FALSE);
	}
	return (TRUE);
}

bool_t
xdr_SDXtoc(XDR *xdrs, SDXtoc *objp)
{
	if (!xdr_int(xdrs, &objp->nvars)) {
		return (FALSE);
	}
	if (!xdr_array(xdrs, (char **)&objp->varnames.varnames_val, (u_int *)&objp->varnames.varnames_len, ~0, sizeof(char), (xdrproc_t) xdr_char)) {
		return (FALSE);
	}
	if (!xdr_array(xdrs, (char **)&objp->vartypes.vartypes_val, (u_int *)&objp->vartypes.vartypes_len, ~0, sizeof(int), (xdrproc_t) xdr_int)) {
		return (FALSE);
	}
	return (TRUE);
}

bool_t
xdr_var_type(XDR *xdrs, var_type *objp)
{
	if (!xdr_enum(xdrs, (enum_t *)objp)) {
		return (FALSE);
	}
	return (TRUE);
}

bool_t
xdr_var_info(XDR *xdrs, var_info *objp)
{
	if (!xdr_var_type(xdrs, &objp->var)) {
		return (FALSE);
	}
	switch (objp->var) {
	case SDX_INTEGER:
		if (!xdr_int(xdrs, &objp->var_info_u.ivalue)) {
			return (FALSE);
		}
		break;
	case SDX_FLOAT:
		if (!xdr_float(xdrs, &objp->var_info_u.fvalue)) {
			return (FALSE);
		}
		break;
	case SDX_DOUBLE:
		if (!xdr_double(xdrs, &objp->var_info_u.dvalue)) {
			return (FALSE);
		}
		break;
	case SDX_CHAR:
		if (!xdr_vector(xdrs, (char *)objp->var_info_u.cvalue, MAXSTRLEN, sizeof(char), (xdrproc_t) xdr_char)) {
			return (FALSE);
		}
		break;
	}
	return (TRUE);
}

bool_t
xdr_SDXvar(XDR *xdrs, SDXvar *objp)
{
	if (!xdr_var_type(xdrs, &objp->type)) {
		return (FALSE);
	}
	if (!xdr_var_info(xdrs, &objp->info)) {
		return (FALSE);
	}
	return (TRUE);
}


bool_t
xdr_SDXmultimesh(XDR *xdrs, SDXmultimesh *objp)
{
	if (!xdr_int(xdrs, &objp->id)) {
		return (FALSE);
	}
	if (!xdr_int(xdrs, &objp->nblocks)) {
		return (FALSE);
	}
	if (!xdr_array(xdrs, (char **)&objp->meshids.meshids_val, (u_int *)&objp->meshids.meshids_len, ~0, sizeof(int), (xdrproc_t) xdr_int)) {
		return (FALSE);
	}
	if (!xdr_array(xdrs, (char **)&objp->meshnames.meshnames_val, (u_int *)&objp->meshnames.meshnames_len, ~0, sizeof(char), (xdrproc_t) xdr_char)) {
		return (FALSE);
	}
	if (!xdr_array(xdrs, (char **)&objp->meshtypes.meshtypes_val, (u_int *)&objp->meshtypes.meshtypes_len, ~0, sizeof(int), (xdrproc_t) xdr_int)) {
		return (FALSE);
	}
	return (TRUE);
}

bool_t
xdr_SDXmultivar(XDR *xdrs, SDXmultivar *objp)
{
	if (!xdr_int(xdrs, &objp->id)) {
		return (FALSE);
	}
	if (!xdr_int(xdrs, &objp->nvars)) {
		return (FALSE);
	}
	if (!xdr_array(xdrs, (char **)&objp->varnames.varnames_val, (u_int *)&objp->varnames.varnames_len, ~0, sizeof(char), (xdrproc_t) xdr_char)) {
		return (FALSE);
	}
	if (!xdr_array(xdrs, (char **)&objp->vartypes.vartypes_val, (u_int *)&objp->vartypes.vartypes_len, ~0, sizeof(int), (xdrproc_t) xdr_int)) {
		return (FALSE);
	}
	return (TRUE);
}

bool_t
xdr_SDXmultimat(XDR *xdrs, SDXmultimat *objp)
{
	if (!xdr_int(xdrs, &objp->id)) {
		return (FALSE);
	}
	if (!xdr_int(xdrs, &objp->nmats)) {
		return (FALSE);
	}
	if (!xdr_array(xdrs, (char **)&objp->matnames.matnames_val, (u_int *)&objp->matnames.matnames_len, ~0, sizeof(char), (xdrproc_t) xdr_char)) {
		return (FALSE);
	}
	return (TRUE);
}

bool_t
xdr_SDXmultimatspecies(XDR *xdrs, SDXmultimatspecies *objp)
{
	if (!xdr_int(xdrs, &objp->id)) {
		return (FALSE);
	}
	if (!xdr_int(xdrs, &objp->nspec)) {
		return (FALSE);
	}
	if (!xdr_array(xdrs, (char **)&objp->specnames.specnames_val, (u_int *)&objp->specnames.specnames_len, ~0, sizeof(char), (xdrproc_t) xdr_char)) {
		return (FALSE);
	}
	return (TRUE);
}

bool_t
xdr_SDXzonelist(XDR *xdrs, SDXzonelist *objp)
{
	if (!xdr_int(xdrs, &objp->ndims)) {
		return (FALSE);
	}
	if (!xdr_int(xdrs, &objp->nzones)) {
		return (FALSE);
	}
	if (!xdr_int(xdrs, &objp->nshapes)) {
		return (FALSE);
	}
	if (!xdr_array(xdrs, (char **)&objp->shapecnt.shapecnt_val, (u_int *)&objp->shapecnt.shapecnt_len, ~0, sizeof(int), (xdrproc_t) xdr_int)) {
		return (FALSE);
	}
	if (!xdr_array(xdrs, (char **)&objp->shapesize.shapesize_val, (u_int *)&objp->shapesize.shapesize_len, ~0, sizeof(int), (xdrproc_t) xdr_int)) {
		return (FALSE);
	}
	if (!xdr_array(xdrs, (char **)&objp->nodelist.nodelist_val, (u_int *)&objp->nodelist.nodelist_len, ~0, sizeof(int), (xdrproc_t) xdr_int)) {
		return (FALSE);
	}
	if (!xdr_int(xdrs, &objp->lnodelist)) {
		return (FALSE);
	}
	if (!xdr_int(xdrs, &objp->origin)) {
		return (FALSE);
	}
	return (TRUE);
}

bool_t
xdr_SDXfacelist(XDR *xdrs, SDXfacelist *objp)
{
	if (!xdr_int(xdrs, &objp->ndims)) {
		return (FALSE);
	}
	if (!xdr_int(xdrs, &objp->nfaces)) {
		return (FALSE);
	}
	if (!xdr_int(xdrs, &objp->origin)) {
		return (FALSE);
	}
	if (!xdr_array(xdrs, (char **)&objp->nodelist.nodelist_val, (u_int *)&objp->nodelist.nodelist_len, ~0, sizeof(int), (xdrproc_t) xdr_int)) {
		return (FALSE);
	}
	if (!xdr_int(xdrs, &objp->lnodelist)) {
		return (FALSE);
	}
	if (!xdr_int(xdrs, &objp->nshapes)) {
		return (FALSE);
	}
	if (!xdr_array(xdrs, (char **)&objp->shapecnt.shapecnt_val, (u_int *)&objp->shapecnt.shapecnt_len, ~0, sizeof(int), (xdrproc_t) xdr_int)) {
		return (FALSE);
	}
	if (!xdr_array(xdrs, (char **)&objp->shapesize.shapesize_val, (u_int *)&objp->shapesize.shapesize_len, ~0, sizeof(int), (xdrproc_t) xdr_int)) {
		return (FALSE);
	}
	if (!xdr_int(xdrs, &objp->ntypes)) {
		return (FALSE);
	}
	if (!xdr_array(xdrs, (char **)&objp->typelist.typelist_val, (u_int *)&objp->typelist.typelist_len, ~0, sizeof(int), (xdrproc_t) xdr_int)) {
		return (FALSE);
	}
	if (!xdr_array(xdrs, (char **)&objp->types.types_val, (u_int *)&objp->types.types_len, ~0, sizeof(int), (xdrproc_t) xdr_int)) {
		return (FALSE);
	}
	if (!xdr_array(xdrs, (char **)&objp->zoneno.zoneno_val, (u_int *)&objp->zoneno.zoneno_len, ~0, sizeof(int), (xdrproc_t) xdr_int)) {
		return (FALSE);
	}
	return (TRUE);
}

bool_t
xdr_SDXedgelist(XDR *xdrs, SDXedgelist *objp)
{
	if (!xdr_int(xdrs, &objp->ndims)) {
		return (FALSE);
	}
	if (!xdr_int(xdrs, &objp->nedges)) {
		return (FALSE);
	}
	if (!xdr_array(xdrs, (char **)&objp->edge_beg.edge_beg_val, (u_int *)&objp->edge_beg.edge_beg_len, ~0, sizeof(int), (xdrproc_t) xdr_int)) {
		return (FALSE);
	}
	if (!xdr_array(xdrs, (char **)&objp->edge_end.edge_end_val, (u_int *)&objp->edge_end.edge_end_len, ~0, sizeof(int), (xdrproc_t) xdr_int)) {
		return (FALSE);
	}
	if (!xdr_int(xdrs, &objp->origin)) {
		return (FALSE);
	}
	return (TRUE);
}

bool_t
xdr_SDXquadmesh(XDR *xdrs, SDXquadmesh *objp)
{
	if (!xdr_int(xdrs, &objp->id)) {
		return (FALSE);
	}
	if (!xdr_int(xdrs, &objp->block_no)) {
		return (FALSE);
	}
	if (!xdr_vector(xdrs, (char *)objp->name, MAXSTRLEN, sizeof(char), (xdrproc_t) xdr_char)) {
		return (FALSE);
	}
	if (!xdr_int(xdrs, &objp->cycle)) {
		return (FALSE);
	}
	if (!xdr_float(xdrs, &objp->time)) {
		return (FALSE);
	}
	if (!xdr_int(xdrs, &objp->coord_sys)) {
		return (FALSE);
	}
	if (!xdr_int(xdrs, &objp->major_order)) {
		return (FALSE);
	}
	if (!xdr_vector(xdrs, (char *)objp->stride, 3, sizeof(int), (xdrproc_t) xdr_int)) {
		return (FALSE);
	}
	if (!xdr_int(xdrs, &objp->coordtype)) {
		return (FALSE);
	}
	if (!xdr_int(xdrs, &objp->facetype)) {
		return (FALSE);
	}
	if (!xdr_int(xdrs, &objp->planar)) {
		return (FALSE);
	}
	if (!xdr_SDXarray(xdrs, &objp->xcoords)) {
		return (FALSE);
	}
	if (!xdr_SDXarray(xdrs, &objp->ycoords)) {
		return (FALSE);
	}
	if (!xdr_SDXarray(xdrs, &objp->zcoords)) {
		return (FALSE);
	}
	if (!xdr_int(xdrs, &objp->datatype)) {
		return (FALSE);
	}
	if (!xdr_vector(xdrs, (char *)objp->min_extents, 3, sizeof(float), (xdrproc_t) xdr_float)) {
		return (FALSE);
	}
	if (!xdr_vector(xdrs, (char *)objp->max_extents, 3, sizeof(float), (xdrproc_t) xdr_float)) {
		return (FALSE);
	}
	if (!xdr_vector(xdrs, (char *)objp->xlabel, MAXSTRLEN, sizeof(char), (xdrproc_t) xdr_char)) {
		return (FALSE);
	}
	if (!xdr_vector(xdrs, (char *)objp->ylabel, MAXSTRLEN, sizeof(char), (xdrproc_t) xdr_char)) {
		return (FALSE);
	}
	if (!xdr_vector(xdrs, (char *)objp->zlabel, MAXSTRLEN, sizeof(char), (xdrproc_t) xdr_char)) {
		return (FALSE);
	}
	if (!xdr_vector(xdrs, (char *)objp->xunits, MAXSTRLEN, sizeof(char), (xdrproc_t) xdr_char)) {
		return (FALSE);
	}
	if (!xdr_vector(xdrs, (char *)objp->yunits, MAXSTRLEN, sizeof(char), (xdrproc_t) xdr_char)) {
		return (FALSE);
	}
	if (!xdr_vector(xdrs, (char *)objp->zunits, MAXSTRLEN, sizeof(char), (xdrproc_t) xdr_char)) {
		return (FALSE);
	}
	if (!xdr_int(xdrs, &objp->ndims)) {
		return (FALSE);
	}
	if (!xdr_int(xdrs, &objp->nspace)) {
		return (FALSE);
	}
	if (!xdr_int(xdrs, &objp->nnodes)) {
		return (FALSE);
	}
	if (!xdr_vector(xdrs, (char *)objp->dims, 3, sizeof(int), (xdrproc_t) xdr_int)) {
		return (FALSE);
	}
	if (!xdr_int(xdrs, &objp->origin)) {
		return (FALSE);
	}
	if (!xdr_vector(xdrs, (char *)objp->min_index, 3, sizeof(int), (xdrproc_t) xdr_int)) {
		return (FALSE);
	}
	if (!xdr_vector(xdrs, (char *)objp->max_index, 3, sizeof(int), (xdrproc_t) xdr_int)) {
		return (FALSE);
	}
	return (TRUE);
}

bool_t
xdr_SDXucdmesh(XDR *xdrs, SDXucdmesh *objp)
{
	if (!xdr_int(xdrs, &objp->id)) {
		return (FALSE);
	}
	if (!xdr_int(xdrs, &objp->block_no)) {
		return (FALSE);
	}
	if (!xdr_vector(xdrs, (char *)objp->name, MAXSTRLEN, sizeof(char), (xdrproc_t) xdr_char)) {
		return (FALSE);
	}
	if (!xdr_int(xdrs, &objp->cycle)) {
		return (FALSE);
	}
	if (!xdr_float(xdrs, &objp->time)) {
		return (FALSE);
	}
	if (!xdr_int(xdrs, &objp->coord_sys)) {
		return (FALSE);
	}
	if (!xdr_vector(xdrs, (char *)objp->xunits, MAXSTRLEN, sizeof(char), (xdrproc_t) xdr_char)) {
		return (FALSE);
	}
	if (!xdr_vector(xdrs, (char *)objp->yunits, MAXSTRLEN, sizeof(char), (xdrproc_t) xdr_char)) {
		return (FALSE);
	}
	if (!xdr_vector(xdrs, (char *)objp->zunits, MAXSTRLEN, sizeof(char), (xdrproc_t) xdr_char)) {
		return (FALSE);
	}
	if (!xdr_vector(xdrs, (char *)objp->xlabel, MAXSTRLEN, sizeof(char), (xdrproc_t) xdr_char)) {
		return (FALSE);
	}
	if (!xdr_vector(xdrs, (char *)objp->ylabel, MAXSTRLEN, sizeof(char), (xdrproc_t) xdr_char)) {
		return (FALSE);
	}
	if (!xdr_vector(xdrs, (char *)objp->zlabel, MAXSTRLEN, sizeof(char), (xdrproc_t) xdr_char)) {
		return (FALSE);
	}
	if (!xdr_array(xdrs, (char **)&objp->xcoords.xcoords_val, (u_int *)&objp->xcoords.xcoords_len, ~0, sizeof(float), (xdrproc_t) xdr_float)) {
		return (FALSE);
	}
	if (!xdr_array(xdrs, (char **)&objp->ycoords.ycoords_val, (u_int *)&objp->ycoords.ycoords_len, ~0, sizeof(float), (xdrproc_t) xdr_float)) {
		return (FALSE);
	}
	if (!xdr_array(xdrs, (char **)&objp->zcoords.zcoords_val, (u_int *)&objp->zcoords.zcoords_len, ~0, sizeof(float), (xdrproc_t) xdr_float)) {
		return (FALSE);
	}
	if (!xdr_int(xdrs, &objp->datatype)) {
		return (FALSE);
	}
	if (!xdr_vector(xdrs, (char *)objp->min_extents, 3, sizeof(float), (xdrproc_t) xdr_float)) {
		return (FALSE);
	}
	if (!xdr_vector(xdrs, (char *)objp->max_extents, 3, sizeof(float), (xdrproc_t) xdr_float)) {
		return (FALSE);
	}
	if (!xdr_int(xdrs, &objp->ndims)) {
		return (FALSE);
	}
	if (!xdr_int(xdrs, &objp->nnodes)) {
		return (FALSE);
	}
	if (!xdr_int(xdrs, &objp->origin)) {
		return (FALSE);
	}
	return (TRUE);
}

bool_t
xdr_SDXquadvar(XDR *xdrs, SDXquadvar *objp)
{
	if (!xdr_int(xdrs, &objp->id)) {
		return (FALSE);
	}
	if (!xdr_vector(xdrs, (char *)objp->name, MAXSTRLEN, sizeof(char), (xdrproc_t) xdr_char)) {
		return (FALSE);
	}
	if (!xdr_vector(xdrs, (char *)objp->units, MAXSTRLEN, sizeof(char), (xdrproc_t) xdr_char)) {
		return (FALSE);
	}
	if (!xdr_vector(xdrs, (char *)objp->label, MAXSTRLEN, sizeof(char), (xdrproc_t) xdr_char)) {
		return (FALSE);
	}
	if (!xdr_int(xdrs, &objp->cycle)) {
		return (FALSE);
	}
	if (!xdr_float(xdrs, &objp->time)) {
		return (FALSE);
	}
	if (!xdr_int(xdrs, &objp->meshid)) {
		return (FALSE);
	}
	if (!xdr_SDXarray(xdrs, &objp->vals)) {
		return (FALSE);
	}
	if (!xdr_int(xdrs, &objp->datatype)) {
		return (FALSE);
	}
	if (!xdr_int(xdrs, &objp->nels)) {
		return (FALSE);
	}
	if (!xdr_int(xdrs, &objp->ndims)) {
		return (FALSE);
	}
	if (!xdr_vector(xdrs, (char *)objp->dims, 3, sizeof(int), (xdrproc_t) xdr_int)) {
		return (FALSE);
	}
	if (!xdr_int(xdrs, &objp->major_order)) {
		return (FALSE);
	}
	if (!xdr_vector(xdrs, (char *)objp->stride, 3, sizeof(int), (xdrproc_t) xdr_int)) {
		return (FALSE);
	}
	if (!xdr_vector(xdrs, (char *)objp->min_index, 3, sizeof(int), (xdrproc_t) xdr_int)) {
		return (FALSE);
	}
	if (!xdr_vector(xdrs, (char *)objp->max_index, 3, sizeof(int), (xdrproc_t) xdr_int)) {
		return (FALSE);
	}
	if (!xdr_int(xdrs, &objp->origin)) {
		return (FALSE);
	}
	if (!xdr_vector(xdrs, (char *)objp->align, 3, sizeof(float), (xdrproc_t) xdr_float)) {
		return (FALSE);
	}
	return (TRUE);
}

bool_t
xdr_SDXucdvar(XDR *xdrs, SDXucdvar *objp)
{
	if (!xdr_int(xdrs, &objp->id)) {
		return (FALSE);
	}
	if (!xdr_vector(xdrs, (char *)objp->name, MAXSTRLEN, sizeof(char), (xdrproc_t) xdr_char)) {
		return (FALSE);
	}
	if (!xdr_int(xdrs, &objp->cycle)) {
		return (FALSE);
	}
	if (!xdr_vector(xdrs, (char *)objp->units, MAXSTRLEN, sizeof(char), (xdrproc_t) xdr_char)) {
		return (FALSE);
	}
	if (!xdr_vector(xdrs, (char *)objp->label, MAXSTRLEN, sizeof(char), (xdrproc_t) xdr_char)) {
		return (FALSE);
	}
	if (!xdr_float(xdrs, &objp->time)) {
		return (FALSE);
	}
	if (!xdr_int(xdrs, &objp->meshid)) {
		return (FALSE);
	}
	if (!xdr_array(xdrs, (char **)&objp->vals.vals_val, (u_int *)&objp->vals.vals_len, ~0, sizeof(float), (xdrproc_t) xdr_float)) {
		return (FALSE);
	}
	if (!xdr_int(xdrs, &objp->datatype)) {
		return (FALSE);
	}
	if (!xdr_int(xdrs, &objp->nels)) {
		return (FALSE);
	}
	if (!xdr_int(xdrs, &objp->ndims)) {
		return (FALSE);
	}
	if (!xdr_int(xdrs, &objp->origin)) {
		return (FALSE);
	}
	if (!xdr_int(xdrs, &objp->centering)) {
		return (FALSE);
	}
	return (TRUE);
}

bool_t
xdr_SDXmaterial(XDR *xdrs, SDXmaterial *objp)
{
	if (!xdr_int(xdrs, &objp->id)) {
		return (FALSE);
	}
	if (!xdr_vector(xdrs, (char *)objp->name, MAXSTRLEN, sizeof(char), (xdrproc_t) xdr_char)) {
		return (FALSE);
	}
	if (!xdr_int(xdrs, &objp->ndims)) {
		return (FALSE);
	}
	if (!xdr_int(xdrs, &objp->origin)) {
		return (FALSE);
	}
	if (!xdr_vector(xdrs, (char *)objp->dims, 3, sizeof(int), (xdrproc_t) xdr_int)) {
		return (FALSE);
	}
	if (!xdr_int(xdrs, &objp->major_order)) {
		return (FALSE);
	}
	if (!xdr_vector(xdrs, (char *)objp->stride, 3, sizeof(float), (xdrproc_t) xdr_float)) {
		return (FALSE);
	}
	if (!xdr_int(xdrs, &objp->nmat)) {
		return (FALSE);
	}
	if (!xdr_array(xdrs, (char **)&objp->matnos.matnos_val, (u_int *)&objp->matnos.matnos_len, ~0, sizeof(int), (xdrproc_t) xdr_int)) {
		return (FALSE);
	}
	if (!xdr_array(xdrs, (char **)&objp->matlist.matlist_val, (u_int *)&objp->matlist.matlist_len, ~0, sizeof(int), (xdrproc_t) xdr_int)) {
		return (FALSE);
	}
	if (!xdr_int(xdrs, &objp->mixlen)) {
		return (FALSE);
	}
	if (!xdr_int(xdrs, &objp->datatype)) {
		return (FALSE);
	}
	if (!xdr_SDXarray(xdrs, &objp->mix_vf)) {
		return (FALSE);
	}
	if (!xdr_array(xdrs, (char **)&objp->mix_next.mix_next_val, (u_int *)&objp->mix_next.mix_next_len, ~0, sizeof(int), (xdrproc_t) xdr_int)) {
		return (FALSE);
	}
	if (!xdr_array(xdrs, (char **)&objp->mix_mat.mix_mat_val, (u_int *)&objp->mix_mat.mix_mat_len, ~0, sizeof(int), (xdrproc_t) xdr_int)) {
		return (FALSE);
	}
	if (!xdr_array(xdrs, (char **)&objp->mix_zone.mix_zone_val, (u_int *)&objp->mix_zone.mix_zone_len, ~0, sizeof(int), (xdrproc_t) xdr_int)) {
		return (FALSE);
	}
	return (TRUE);
}

bool_t
xdr_SDXMWDInfo(XDR *xdrs, SDXMWDInfo *objp)
{
	if (!xdr_int(xdrs, &objp->nqmesh)) {
		return (FALSE);
	}
	if (!xdr_array(xdrs, (char **)&objp->nqvar.nqvar_val, (u_int *)&objp->nqvar.nqvar_len, ~0, sizeof(int), (xdrproc_t) xdr_int)) {
		return (FALSE);
	}
	if (!xdr_int(xdrs, &objp->numesh)) {
		return (FALSE);
	}
	if (!xdr_array(xdrs, (char **)&objp->nuvar.nuvar_val, (u_int *)&objp->nuvar.nuvar_len, ~0, sizeof(int), (xdrproc_t) xdr_int)) {
		return (FALSE);
	}
	if (!xdr_vector(xdrs, (char *)objp->min_extents, 3, sizeof(float), (xdrproc_t) xdr_float)) {
		return (FALSE);
	}
	if (!xdr_vector(xdrs, (char *)objp->max_extents, 3, sizeof(float), (xdrproc_t) xdr_float)) {
		return (FALSE);
	}
	if (!xdr_int(xdrs, &objp->nspace)) {
		return (FALSE);
	}
	if (!xdr_int(xdrs, &objp->cycle)) {
		return (FALSE);
	}
	if (!xdr_float(xdrs, &objp->time)) {
		return (FALSE);
	}
	if (!xdr_vector(xdrs, (char *)objp->name, MAXSTRLEN, sizeof(char), (xdrproc_t) xdr_char)) {
		return (FALSE);
	}
	return (TRUE);
}
