#!/bin/csh
#######################################################################
#
#                            Copyright 1991 - 1995
#                 The Regents of the University of California.
#                            All rights reserved.
#
# This work was produced at the University of California, Lawrence
# Livermore National Laboratory (UC LLNL) under contract no.  W-7405-ENG-48
# (Contract 48) between the U.S. Department of Energy (DOE) and The Regents
# of the University of California (University) for the operation of UC LLNL.
# Copyright is reserved to the University for purposes of controlled
# dissemination, commercialization through formal licensing, or other
# disposition under terms of Contract 48; DOE policies, regulations and
# orders; and U.S. statutes.  The rights of the Federal Government are
# reserved under Contract 48 subject to the restrictions agreed upon by
# DOE and University.
#
#                                 DISCLAIMER
#
# This software was prepared as an account of work sponsored by an agency
# of the United States Government. Neither the United States Government
# nor the University of California nor any of their employees, makes any
# warranty, express or implied, or assumes any liability or responsiblity
# for the accuracy, completeness, or usefullness of any information,
# apparatus, product, or process disclosed, or represents that its use
# would not infringe privately owned rights. Reference herein to any
# specific commercial products, process, or service by trade name, trademark,
# manufacturer, or otherwise, does not necessarily constitute or imply its
# endorsement, recommendation, or favoring by the United States Government
# or the University of California. The views and opinions of authors
# expressed herein do not necessarily state or reflect those of the United
# States Government or the University of California, and shall not be used
# for advertising or product endorsement purposes.
#
#######################################################################

#######################################################################
#
# Script to test the sdx library.
#
# The checking is not automatic.  The script only runs some test
# cases which generate output files.  These output files must be
# checked by someone to determine if they are correct.
#
#######################################################################


#
# Generate the server, client test program, and control test program.
#
make

#
# Start the sdx deamon.
#
echo "starting sdx daemon..."
./sdxd &
sleep 2

#
# Start the server process.
#
hostname > sdxinfo
whoami   >> sdxinfo
echo "starting server process..."
./tserver &
sleep 2

#
# Run the client test program.
#
echo "running client test program..."
./tclient > test.log

#
# Run the control test program.
#
echo "running  control test program."
./tcontrol >> test.log

#
# Kill the server and deamon.
#
echo "killing server and daemon..."
set sdxdid = `ps -e | grep sdxd | sed "s/pts.*//"`
set tserverid = `ps -e | grep tserver | sed "s/pts.*//"`
kill -9 $sdxdid $tserverid

#
# Clean up.
#
#rm *.o tserver tclient tcontrol
