# This file is included by CTest at test time (not configure time)
if(APPLE)
    set(ENV{DYLD_INSERT_LIBRARIES} "/Library/Developer/CommandLineTools/usr/lib/clang/17/lib/darwin/libclang_rt.asan_osx_dynamic.dylib")
    set(ENV{MallocNanoZone} "0")
    set(ENV{ASAN_OPTIONS} "halt_on_error=1:malloc_context_size=50:fast_unwind_on_malloc=0:detect_stack_use_after_return=1")
else()
    set(ENV{ASAN_OPTIONS} "detect_leaks=1:halt_on_error=1:malloc_context_size=50:fast_unwind_on_malloc=0:detect_stack_use_after_return=1")
endif()
