import Silo

db = Silo.Create("foo.silo", "test file")
db.Write("t1", 12)
db.Write("t2", "hello")
db.Write("t3", (13,))
db.Write("t4", 14.5)
db.Write("t5", (1.2, 10))
db.Write("t6", (1.2, 10.2))
db.Write("t7", (10, 1.2))
db.Write("t8", "a")
db.MkDir("a")
db.Write("a/t8", "x2")
db.SetDir("a")
db.Write("t9", "x3")
db.Write("../t10", "x4")
db.SetDir("..")
db.Write("t11", "x5")
db.Close()

db2=Silo.Open("foo.silo")
print "toc=%s"%db2.GetToc()
print "t2='%s'"%db2.GetVar("t2")
print "t6=",db2.GetVar("t6")
print "a/t8='%s'"%db2.GetVar("a/t8")
db2.SetDir("a")
print "t9=%s"%db2.GetVar("t9")
print "/t5=",db2.GetVar("../t5")
db2.Close()
