#!/bin/sh

# Copyright (C) 1994-2016 Lawrence Livermore National Security, LLC.
# LLNL-CODE-425250.
# All rights reserved.
# 
# This file is part of Silo. For details, see silo.llnl.gov.
# 
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 
#    * Redistributions of source code must retain the above copyright
#      notice, this list of conditions and the disclaimer below.
#    * Redistributions in binary form must reproduce the above copyright
#      notice, this list of conditions and the disclaimer (as noted
#      below) in the documentation and/or other materials provided with
#      the distribution.
#    * Neither the name of the LLNS/LLNL nor the names of its
#      contributors may be used to endorse or promote products derived
#      from this software without specific prior written permission.
# 
# THIS SOFTWARE  IS PROVIDED BY  THE COPYRIGHT HOLDERS  AND CONTRIBUTORS
# "AS  IS" AND  ANY EXPRESS  OR IMPLIED  WARRANTIES, INCLUDING,  BUT NOT
# LIMITED TO, THE IMPLIED  WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
# A  PARTICULAR  PURPOSE ARE  DISCLAIMED.  IN  NO  EVENT SHALL  LAWRENCE
# LIVERMORE  NATIONAL SECURITY, LLC,  THE U.S.  DEPARTMENT OF  ENERGY OR
# CONTRIBUTORS BE LIABLE FOR  ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
# EXEMPLARY, OR  CONSEQUENTIAL DAMAGES  (INCLUDING, BUT NOT  LIMITED TO,
# PROCUREMENT OF  SUBSTITUTE GOODS  OR SERVICES; LOSS  OF USE,  DATA, OR
# PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
# LIABILITY, WHETHER  IN CONTRACT, STRICT LIABILITY,  OR TORT (INCLUDING
# NEGLIGENCE OR  OTHERWISE) ARISING IN  ANY WAY OUT  OF THE USE  OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
# 
# This work was produced at Lawrence Livermore National Laboratory under
# Contract  No.   DE-AC52-07NA27344 with  the  DOE.  Neither the  United
# States Government  nor Lawrence  Livermore National Security,  LLC nor
# any of  their employees,  makes any warranty,  express or  implied, or
# assumes   any   liability   or   responsibility  for   the   accuracy,
# completeness, or usefulness of any information, apparatus, product, or
# process  disclosed, or  represents  that its  use  would not  infringe
# privately-owned   rights.  Any  reference   herein  to   any  specific
# commercial products,  process, or  services by trade  name, trademark,
# manufacturer or otherwise does not necessarily constitute or imply its
# endorsement,  recommendation,   or  favoring  by   the  United  States
# Government or Lawrence Livermore National Security, LLC. The views and
# opinions  of authors  expressed  herein do  not  necessarily state  or
# reflect those  of the United  States Government or  Lawrence Livermore
# National  Security, LLC,  and shall  not  be used  for advertising  or
# product endorsement purposes.

# -----------------------------------------------------------------------------
# Test writing silo objects via python file format compatibility of HDF5
#
# This test works only onehex executable has run and created onehex.silo
#
# Programmer: Mark C. Miller
# Creation:   July 21, 2008
#
# -----------------------------------------------------------------------------

#
# Find dir where this script lives and source the shell utils script there.
#
# dirname -- "$0" gets the script’s directory even if this script is run via a
#     relative path like ../../foo/bar/gorfo.sh.
# The CDPATH= nulls that env. variable and prevents cd from printing anything
#     if CDPATH is set in the environment.
# pwd gives the absolute path after the cd has occurred. This all happens in
#     a subshell so the cwd of the current script is unchanged.
#
script_dir=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
. $script_dir/silo_sh_utils.sh

#
# In uses of find_file, below, the multiple paths tested are due to the fact
# that this code needs to work, for a short period of time, for both Autotools
# and CMake/CTest. The first path tested is for CMake/CTest build and the
# others are for Autotools
#

#
# Ensure we have Silo's python module
#
silo_pyso=$(find_file -r lib/Silo.so lib64/Silo.so tools/python/Silo.so tools/python/.libs/Silo.so)
[ $? -eq 0 ] || exit 1

# 
# Ensure we have Silo's 'browser' tool available
# 
browser=$(find_file -x bin/browser tools/browser/browser tools/browser/.libs/browser)
[ $? -eq 0 ] || exit 1

#
# Ensure we have onehex.py python script
#
onehexpy=$(find_file -r tests/bin/onehex.py tests/onehex.py)
[ $? -eq 0 ] || exit 1

#
# Ensure we have the python interpreter in PATH
#
pycmd=$(command -v python3)
if [ -z "$pycmd" ]; then
    pycmd=$(command -v python)
fi
if [ -z "$pycmd" ]; then
    pycmd=$(command -v python2)
fi
if [ -z "$pycmd" ]; then
    echo "Unable to find python command in path"
    exit 5
fi

#
# Use python module to create data with no special features 
#
env PYTHONPATH=$(dirname $silo_pyso) $pycmd $onehexpy 1>/dev/null 2>&1

#
# Now, run browser and make sure we don't get any errors in the diff
#
result=0
$browser --proper-exit-code -R 0.00001 -q -e diff onehex.silo onehexpy.silo 1>testonehex.out 2>&1
if [ $? -ne 0 ] || [ `grep -v 'appears only in' testonehex.out | grep '=' | wc -l | tr -s ' ' | cut -d' ' -f2` -gt 5 ]; then
    result=1
fi

exit $result 
