#!/bin/sh

# Copyright (c) 1994 - 2010, Lawrence Livermore National Security, LLC.
# LLNL-CODE-425250.
# All rights reserved.
# 
# This file is part of Silo. For details, see silo.llnl.gov.
# 
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 
#    * Redistributions of source code must retain the above copyright
#      notice, this list of conditions and the disclaimer below.
#    * Redistributions in binary form must reproduce the above copyright
#      notice, this list of conditions and the disclaimer (as noted
#      below) in the documentation and/or other materials provided with
#      the distribution.
#    * Neither the name of the LLNS/LLNL nor the names of its
#      contributors may be used to endorse or promote products derived
#      from this software without specific prior written permission.
# 
# THIS SOFTWARE  IS PROVIDED BY  THE COPYRIGHT HOLDERS  AND CONTRIBUTORS
# "AS  IS" AND  ANY EXPRESS  OR IMPLIED  WARRANTIES, INCLUDING,  BUT NOT
# LIMITED TO, THE IMPLIED  WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
# A  PARTICULAR  PURPOSE ARE  DISCLAIMED.  IN  NO  EVENT SHALL  LAWRENCE
# LIVERMORE  NATIONAL SECURITY, LLC,  THE U.S.  DEPARTMENT OF  ENERGY OR
# CONTRIBUTORS BE LIABLE FOR  ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
# EXEMPLARY, OR  CONSEQUENTIAL DAMAGES  (INCLUDING, BUT NOT  LIMITED TO,
# PROCUREMENT OF  SUBSTITUTE GOODS  OR SERVICES; LOSS  OF USE,  DATA, OR
# PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
# LIABILITY, WHETHER  IN CONTRACT, STRICT LIABILITY,  OR TORT (INCLUDING
# NEGLIGENCE OR  OTHERWISE) ARISING IN  ANY WAY OUT  OF THE USE  OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
# 
# This work was produced at Lawrence Livermore National Laboratory under
# Contract  No.   DE-AC52-07NA27344 with  the  DOE.  Neither the  United
# States Government  nor Lawrence  Livermore National Security,  LLC nor
# any of  their employees,  makes any warranty,  express or  implied, or
# assumes   any   liability   or   responsibility  for   the   accuracy,
# completeness, or usefulness of any information, apparatus, product, or
# process  disclosed, or  represents  that its  use  would not  infringe
# privately-owned   rights.  Any  reference   herein  to   any  specific
# commercial products,  process, or  services by trade  name, trademark,
# manufacturer or otherwise does not necessarily constitute or imply its
# endorsement,  recommendation,   or  favoring  by   the  United  States
# Government or Lawrence Livermore National Security, LLC. The views and
# opinions  of authors  expressed  herein do  not  necessarily state  or
# reflect those  of the United  States Government or  Lawrence Livermore
# National  Security, LLC,  and shall  not  be used  for advertising  or
# product endorsement purposes.

# -----------------------------------------------------------------------------
# Test interversion file format compatibility of HDF5
#
# Programmer: Mark C. Miller
# Creation:   July 21, 2008
#
# -----------------------------------------------------------------------------

difffiles () {
    for df in multi_*.h5; do
        bf=`basename $df .h5`
        # do a diff on the files
        rm -f testxvers.out
        $topDir/../tools/browser/browser -q -R 0.00001 -e diff $df $topDir/xvers_data/${bf}_$1 1>testxvers.out 2>&1
        if test $(cat testxvers.out | grep -v 'not centered'\\\|'not specified'\\\|'extensive'\\\|'conserved' | wc -l) -gt 20; then
            return 1
            break
        fi
    done
}

# Diddle the the directory because Autotest is not at all designed to handle
# tests the way this one was written
if test -n "$1"; then
    topDir=$1
    if test -e $topDir/../../multi_test; then
        topDir=$1/../..
    fi
else
    topDir=.
fi

#
# Create data with no special features 
#
$topDir/multi_test DB_HDF5 1>/dev/null 2>&1

#
# Figure out minor version num of HDF5 used to create the current data
#
vmin=`$topDir/../tools/browser/browser -e _hdf5libinfo multi_ucd3d.h5 2>/dev/null | grep hdf5 | cut -d'-' -f2 | cut -d'.' -f2`
if test $vmin -eq 6; then
    vtest=8
elif test $vmin -eq 8; then
    vtest=6
else
    echo "Did not find expected hdf5 minor version number"
    exit 1
fi

#
# Uncompress and untar data files from specific versions of HDF5
#
which bunzip2 1>/dev/null 2>&1
test $? -eq 0 || exit 1
bunzip2 < $topDir/xvers_data.tar.bz2 | tar xf -

#
# Now, run browser and make sure we don't get any errors in the diff
#
result=0
difffiles v1${vtest}.h5
result=$(expr $result + $?)
if test $result -eq 0; then
    difffiles v1${vtest}ck.h5
    result=$(expr $result + $?)
fi
if test $result -eq 0; then
    difffiles v1${vtest}fpz.h5
    result=$(expr $result + $?)
fi

#
# Cleanup
#
rm -f testxvers.out
rm -rf $topDir/xvers_data

exit $result 
