#!/bin/sh
result=0

# -----------------------------------------------------------------------------
# Test datatype handling with force single on and off 
#
# Programmer: Mark C. Miller, Thu Jul 15 18:05:03 PDT 2010
# -----------------------------------------------------------------------------

# Diddle the the directory because Autotest is not at all designed to handle
# tests the way this one was written
if test -n "$1"; then
    topDir=$1
    if test -e $topDir/../../testsuite; then
        topDir=$1/../..
    fi
else
    topDir=.
fi

smode="pdb"
if test "$2" = "DB_HDF5"; then
    smode="h5"
fi

#echo -e "driver\tfsmode\tmesh\tvartyp\tdattyp\tstatus"
for fsmode in "-s 1" ""; do
    for mt in "quad" "ucd"; do
        for v in "n" "z"; do
            for d in "c" "s" "i" "l" "L" "d"; do
                diffs=$($topDir/../tools/browser/browser -q ${fsmode} -e "diff f${v}var ${d}${v}var" specmix_$mt.$smode | grep -v 'different data sizes' | grep -v 'byte data' | grep vals | head)
                if test -n "$diffs"; then
                    result=1
                    break 4
#                        echo -e "${smode}\t${fsmode}\t${mt}\t${v}\t${d}\tFAILED"
#                    else
#                        echo -e "${smode}\t${fsmode}\t${mt}\t${v}\t${d}\tPASSED"
                fi
            done
        done
    done
done

exit $result 
