#!/usr/local/bin/perl

$ENV{PATH}="/sbin:/usr/sbin:/usr/bsd:/usr/bin:/bin:/etc:/usr/atria/bin";
$ENV{CDPATH} = undef;

$user = $ENV{'USER'};
$target = $ENV{'TARGET'};
$meshtv_home = (getpwnam("meshtv"))[7];
$target =~ s|^$meshtv_home/clearcase_bin/||;

print STDERR "Attempting network connection...\n";
system "/usr/local/bin/ssh","viper","-l","meshtv","clearcase_bin/$target.script","$user",@ARGV;
