#!/bin/sh 
#######################################################################
#
# build-3rdparty-closed - Build and install 3rd party libraries.
#
# Author: Thomas Treadway
# Date: Fri Nov 30 13:26:50 PST 2007
#
# Usage:
#     build-3rdparty-closed
#
# Modifications:
#
#######################################################################
#
BDTOPDIR="/usr/gapps/silo"
LCTOPDIR="/usr/gapps/silo"
#LCTOPDIR="/nfs/tmp0/$USER"
SZIPRELEASE=2.1
HDF5RELEASE=1.6.6
QTRELEASE=3.3.8
lcun=$USER
bdun=$USER
bdhost="vader"
export BDTOPDIR LCTOPDIR

usage() {
  printf "Usage: %s [-lc-username <lc-username>] [-bdiv-username <username>] [-bdiv-host <hostname>] [all|localhost|sunset|purple|uv|gauss|lilac|rhea|bgl]" $0
  printf "\n"
  printf "Silo 3rd party library installing script. Assumes a tarball exist in\n"
  printf "/usr/gapps/silo/szip/src/szip-$SZIPRELEASE, and\n"
  printf "/usr/gapps/silo/hdf5/src/hdf5-$HDF5RELEASE.\n"
  printf "Log files are stored at ./ARCH.log\n"
  printf "You may want to run this script from the LC network.\n"
}

bbuild() {
    ssh ${bdun}@${HOSTS} "/bin/sh" << EOF > ${ARCH}.log 2>&1 &
    $*
    umask 002
    mkdir $BDTOPDIR/szip/src/$ARCH
    cd $BDTOPDIR/szip/src/$ARCH
    $BDTOPDIR/szip/src/szip-$SZIPRELEASE/configure $CONFOPTS \
    --prefix=$BDTOPDIR/szip/$SZIPRELEASE/$ARCH \
    --disable-shared
    gmake install
    chmod -R g+w $BDTOPDIR/szip/$SZIPRELEASE/$ARCH
    cd $BDTOPDIR/szip/src
    rm -rf $BDTOPDIR/szip/src/$ARCH
    mkdir $BDTOPDIR/hdf5/src/$ARCH
    cd $BDTOPDIR/hdf5/src/$ARCH
    $BDTOPDIR/hdf5/src/hdf5-$HDF5RELEASE/configure $CONFOPTS \
    --prefix=$BDTOPDIR/hdf5/$HDF5RELEASE/$ARCH \
    --with-szlib=$BDTOPDIR/szip/$SZIPRELEASE/$ARCH \
    --disable-shared
    gmake -j 4 install
    chmod -R g+w $BDTOPDIR/hdf5/$HDF5RELEASE/$ARCH
    cd $BDTOPDIR/hdf5/src
    rm -rf $BDTOPDIR/hdf5/src/$ARCH
EOF
}
stdbuild() {
    ssh ${lcun}@${HOSTS} "/bin/sh" << EOF > ${ARCH}.log 2>&1 &
    $*
    umask 002
    mkdir $BDTOPDIR/szip/src/$ARCH
    cd $BDTOPDIR/szip/src/$ARCH
    $BDTOPDIR/szip/src/szip-$SZIPRELEASE/configure $CONFOPTS \
    --prefix=$BDTOPDIR/szip/$SZIPRELEASE/$ARCH \
    --disable-shared
    gmake install
    chmod -R g+w $BDTOPDIR/szip/$SZIPRELEASE/$ARCH
    cd $BDTOPDIR/szip/src
#   rm -rf $BDTOPDIR/szip/src/$ARCH
    mkdir $BDTOPDIR/hdf5/src/$ARCH
    cd $BDTOPDIR/hdf5/src/$ARCH
    $BDTOPDIR/hdf5/src/hdf5-$HDF5RELEASE/configure $CONFOPTS \
    --prefix=$BDTOPDIR/hdf5/$HDF5RELEASE/$ARCH \
    --with-szlib=$BDTOPDIR/szip/$SZIPRELEASE/$ARCH \
    --disable-shared
    gmake -j 4 install
    chmod -R g+w $BDTOPDIR/hdf5/$HDF5RELEASE/$ARCH
    cd $BDTOPDIR/hdf5/src
#   rm -rf $BDTOPDIR/hdf5/src/$ARCH
EOF
}
localhost() {
    localhostgcc
    localhostpgc
    localhosticc
}
localhostgcc() {
    HOSTS="${bdhost}"
    ARCH="linux_rhel3-gcc-3.2.3"
    CONFOPTS="CC=gcc CXX=g++ FC=g77 F77=g77 CFLAGS=\"-fPIC -O2\" \
CXXFLAGS=\"-fPIC -O2\" FFLAGS=-Wno-globals F77FLAGS=-Wno-globals \
FCFLAGS=-Wno-globals"
    export HOSTS ARCH CONFOPTS
    bbuild \
    "PATH=/usr/local/bin:/bin:/usr/bin:/usr/X11R6/bin:/usr/atria/bin:\
/usr/lib/jre/bin:/sbin:/usr/sbin:/opt/bin:/usr/local/apps/bin:\
/usr/security/bin" \
    "LD_LIBRARY_PATH=/usr/lib:/lib" \
    "export PATH LD_LIBRARY_PATH"
}
#
localhostpgc() {
    HOSTS="${bdhost}"
    ARCH="linux_rhel3-pgc-6.2"
    CONFOPTS="CC=pgcc CXX=pgCC FC=\"pgf77 -g77libs\" \
CFLAGS=\"-fPIC -O2\" CXXFLAGS=\"-fPIC -O2\""
    export HOSTS ARCH CONFOPTS
    bbuild \
    "PATH=/usr/local/bin:/bin:/usr/bin:/usr/X11R6/bin:/usr/atria/bin:\
/sbin:/usr/sbin:/opt/bin:/usr/local/apps/bin:/usr/local/pgi/linux86/6.2/bin:\
/usr/security/bin" \
    "LD_LIBRARY_PATH=/usr/lib:/lib:/usr/local/pgi/linux86/lib" \
    "LM_LICENSE_FILE=/usr/local/flexlm/licenses/license.dat:\
7128@helios.llnl.gov:7127@helios.llnl.gov" \
    "export PATH LD_LIBRARY_PATH LM_LICENSE_FILE"
}
#
localhosticc() {
    HOSTS="${bdhost}"
    ARCH="linux_rhel3-icc-8.1"
    CONFOPTS="CC=icc CXX=icc FC=ifort LDFLAGS=-lstdc++ \
CFLAGS=\"-fPIC -O2\" CXXFLAGS=\"-fPIC -O2\""
    export HOSTS ARCH CONFOPTS
    bbuild \
    "PATH=/usr/local/bin:/bin:/usr/bin:/usr/X11R6/bin:/usr/atria/bin:\
/usr/lib/jre/bin:/sbin:/usr/sbin:/opt/bin:/usr/local/apps/bin:\
/usr/local/pgi/linux86/6.0/bin:/usr/security/bin:\
/usr/local/intel/compiler81/bin" \
    "LD_LIBRARY_PATH=/usr/lib:/lib:/usr/local/intel/compiler81/lib" \
    "INTEL_LICENSE_FILE=7127@helios.llnl.gov" \
    "LM_LICENSE_FILE=/usr/local/flexlm/licenses/license.dat:\
7128@helios.llnl.gov:7127@helios.llnl.gov" \
    "export PATH LD_LIBRARY_PATH INTEL_LICENSE_FILE LM_LICENSE_FILE" \
    ". /usr/local/intel/compiler81/bin/iccvars.sh"
}
#
sunset() {
    sunsetgcc
    sunsetcc
}
sunsetgcc() {
    HOSTS=sunset
    ARCH="sunos_57"
    CONFOPTS="CC=gcc CXX=g++ FC=g77 F77=g77 \
FFLAGS=-Wno-globals F77FLAGS=-Wno-globals FCFLAGS=-Wno-globals"
    export HOSTS ARCH CONFOPTS
    bbuild \
    "PATH=/usr/bin:/bin:/usr/local/apps/bin:/usr/local/bin:/usr/ccs/bin:\
/opt/SUNWspro/bin:/usr/ucb:/etc:/usr/openwin/bin:/usr/dt/bin:/usr/java/bin" \
    "LD_LIBRARY_PATH=/usr/local/lib:/usr/lib:/lib" \
    "export PATH LD_LIBRARY_PATH"
}
#
sunsetcc() {
    HOSTS=sunset
    ARCH="sunos_57-cc-5.2"
    CONFOPTS="CC=c89 CXX=CC FC=f77 F77=f77"
    export HOSTS ARCH CONFOPTS
    bbuild \
    "PATH=/usr/bin:/bin:/usr/local/apps/bin:/usr/local/bin:/usr/ccs/bin:\
/opt/SUNWspro/bin:/usr/ucb:/etc:/usr/openwin/bin:/usr/dt/bin:/usr/java/bin" \
    "LD_LIBRARY_PATH=/usr/local/lib:/usr/lib:/lib" \
    "export PATH LD_LIBRARY_PATH"
}

purple() {
    purple64
    purple32
    purple64gcc
    purple32gcc
}
purple64() {
    HOSTS=purple
    ARCH="aix_5_64_fed"
    OBJECT_MODE=64
    CONFOPTS="CC=xlc CXX=xlC FC=xlf F77=xlf"
    export HOSTS ARCH CONFOPTS
    export OBJECT_MODE HOSTS ARCH CONFOPTS
    stdbuild \
    "PATH=/usr/local/bin:/usr/bin:/usr/sbin:/usr/ucb:\
/usr/local/gnu/bin:/usr/local/scripts:/usr/apps/bin:/usr/gapps/bin" \
    "export PATH"
}
#
purple32() {
    HOSTS=purple
    ARCH="aix_5_ll"
    OBJECT_MODE=32
    CONFOPTS="CC=xlc CXX=xlC FC=xlf F77=xlf"
    export HOSTS ARCH CONFOPTS
    export OBJECT_MODE HOSTS ARCH CONFOPTS
    stdbuild \
    "PATH=/usr/local/bin:/usr/bin:/usr/sbin:/usr/ucb:\
/usr/local/gnu/bin:/usr/local/scripts:/usr/apps/bin:/usr/gapps/bin" \
    "export PATH"
}
#
purplegcc() {
  purplegcc32
  purplegcc64
}
purple64gcc() {
    HOSTS=purple
    ARCH="aix_5_64_fed-gcc"
    OBJECT_MODE=64
    CONFOPTS="CC=gcc CXX=g++ FC=g77 F77=g77"
    export HOSTS ARCH CONFOPTS
    export OBJECT_MODE HOSTS ARCH CONFOPTS
    stdbuild \
    "PATH=/usr/local/bin:/usr/bin:/usr/sbin:/usr/ucb:\
/usr/local/gnu/bin:/usr/local/scripts:/usr/apps/bin:/usr/gapps/bin" \
    "export PATH"
}
#
purple32gcc() {
    HOSTS=purple
    ARCH="aix_5_ll-gcc"
    OBJECT_MODE=32
    CONFOPTS="CC=gcc CXX=g++ FC=g77 F77=g77"
    export HOSTS ARCH CONFOPTS
    export OBJECT_MODE HOSTS ARCH CONFOPTS
    stdbuild \
    "PATH=/usr/local/bin:/usr/bin:/usr/sbin:/usr/ucb:\
/usr/local/gnu/bin:/usr/local/scripts:/usr/apps/bin:/usr/gapps/bin" \
    "export PATH"
}

lilac() {
    lilacgcc
    lilacicc
}
lilacgcc() {
    HOSTS=lilac
    ARCH=chaos_3_x86_elan3
    CONFOPTS="CC=gcc CXX=g++ FC=g77 F77=g77 CFLAGS=-fPIC CXXFLAGS=-fPIC"
    export HOSTS ARCH CONFOPTS
    stdbuild \
    "PATH=/usr/local/intel/compiler91/bin:/usr/local/bin:/bin:/usr/bin:\
/usr/bin/X11:/usr/lib/mpi/bin:/usr/apps/bin:/usr/gapps/bin" \
    "export PATH"
}
#
lilacicc() {
    HOSTS=lilac
    ARCH=chaos_3_x86_elan3-icc
    CONFOPTS="CC=icc CXX=icc FC=ifort LDFLAGS=-lstdc++ \
CFLAGS=-fPIC CXXFLAGS=-fPIC"
    export HOSTS ARCH CONFOPTS
    stdbuild \
    "PATH=/usr/local/intel/compiler91/bin:/usr/local/bin:/bin:\
/usr/bin:/usr/bin/X11:/usr/lib/mpi/bin:/usr/apps/bin:/usr/gapps/bin" \
    "export PATH"
}
#
gauss() {
    gaussgcc
    gaussicc
}
gaussgcc() {
    HOSTS=gauss
    ARCH=chaos_3_x86_64_ib-gcc
    CONFOPTS="CC=gcc CXX=g++ FC=g77 F77=g77 CFLAGS=-fPIC CXXFLAGS=-fPIC"
    export HOSTS ARCH CONFOPTS
    stdbuild \
    "PATH=/usr/local/intel/compiler91/bin:/usr/local/bin:/bin:/usr/bin:\
/usr/bin/X11:/usr/lib/mpi/bin:/usr/apps/bin:/usr/gapps/bin" \
    "export PATH"
}
#
gaussicc() {
    HOSTS=gauss
    ARCH=chaos_3_x86_64_ib-icc
    CONFOPTS="CC=icc CXX=icc FC=ifort LDFLAGS=-lstdc++ \
CFLAGS=-fPIC CXXFLAGS=-fPIC"
    export HOSTS ARCH CONFOPTS
    stdbuild \
    "PATH=/usr/local/intel/compiler91/bin:/usr/local/bin:/bin:\
/usr/bin:/usr/bin/X11:/usr/lib/mpi/bin:/usr/apps/bin:/usr/gapps/bin" \
    "export PATH"
}
#
rhea() {
    rheagcc
    rheaicc
    rheapc
    rheapgc
}
rheagcc() {
    HOSTS=rhea
    ARCH=chaos_3_x86_64-gcc-3.4.4
    CONFOPTS="CC=gcc CXX=g++ FC=g77 F77=g77 CFLAGS=-fPIC CXXFLAGS=-fPIC \
FFLAGS=-Wno-globals F77FLAGS=-Wno-globals FCFLAGS=-Wno-globals"
    export HOSTS ARCH CONFOPTS
    stdbuild \
    "PATH=/usr/local/intel/compiler91/bin:/usr/local/bin:/bin:/usr/bin:\
/usr/bin/X11:/usr/lib/mpi/bin:/usr/apps/bin:/usr/gapps/bin" \
    "export PATH"
}
#
rheaicc() {
    HOSTS=rhea
    ARCH=chaos_3_x86_64-icc-9.1
    CONFOPTS="CC=icc CXX=icc FC=ifort F77=ifort LDFLAGS=-lstdc++ \
CFLAGS=-fPIC CXXFLAGS=-fPIC"
    export HOSTS ARCH CONFOPTS
    stdbuild \
    "PATH=/usr/local/intel/compiler91_64/bin:/usr/local/bin:/bin:/usr/bin:\
/usr/bin/X11:/usr/lib/mpi/bin:/usr/apps/bin:/usr/gapps/bin:/usr/kerberos/bin" \
  "INTEL_LICENSE_FILE=/usr/local/intel/compiler91_64/licenses:\
/opt/intel/licenses" \
    "LM_LICENSE_FILE=/usr/local/etc/license.client" \
    "export PATH INTEL_LICENSE_FILE LM_LICENSE_FILE" \
    ". /usr/local/intel/compiler91/bin/iccvars.sh"
}
#
rheapc() {
    HOSTS=rhea
    ARCH=chaos_3_x86_64-pc-2.4
    CONFOPTS="CC=pathcc CXX=pathCC FC=pathf90 F77=pathf90 \
CFLAGS=-fPIC CXXFLAGS=-fPIC"
    export HOSTS ARCH CONFOPTS
    stdbuild \
    "PATH=/usr/global/tools/RSI/bin:\
/usr/local/tools/pathscale/pathscale-2.4/bin2:/usr/local/bin:/bin:/usr/bin:\
/usr/bin/X11:/usr/lib/mpi/bin:/usr/apps/bin:/usr/gapps/bin:/usr/kerberos/bin" \
    "LM_LICENSE_FILE=/usr/local/etc/license.client" \
    "PATHSCALE_SUBSCRIPTION_DAEMON=license1ocf.llnl.gov" \
    "export PATH LM_LICENSE_FILE PATHSCALE_SUBSCRIPTION_DAEMON"
}
#
rheapgc() {
    HOSTS=rhea
    ARCH=chaos_3_x86_64-pgc-6.2
  CONFOPTS=" CC=pgcc CXX=pgCC FC=\"pgf77 -g77libs\" CFLAGS=-fPIC CXXFLAGS=-fPIC"
    export HOSTS ARCH CONFOPTS
    stdbuild \
    "PATH=/usr/global/tools/RSI/bin:\
/usr/local/tools/pgi6.23/linux86-64/6.2/bin:/usr/local/bin:/bin:/usr/bin:\
/usr/bin/X11:/usr/lib/mpi/bin:/usr/apps/bin:/usr/gapps/bin:/usr/kerberos/bin" \
    "LM_LICENSE_FILE=/usr/local/etc/license.client" \
    "export PATH LM_LICENSE_FILE"
}
#
bgl() {
    HOSTS=bgl
    ARCH=sles_9_ppc64
    CONFOPTS="CC=mpxlc"
    export HOSTS ARCH CONFOPTS
    stdbuild \
    "PATH=/opt/ibmcmp/vac/7.0/bin:/opt/ibmcmp/xlf/9.1/bin:/usr/local/bin:\
/bin:/usr/bin:/usr/bin/X11:/usr/lib/mpi/bin:/usr/apps/bin:/usr/gapps/bin" \
    "export PATH"
}

GROUPNAME=`id -gn`
if [ "$GROUPNAME" != "visit" ] ; then
   echo "You must be in the \"visit\" group to run $0. Do \"newgrp visit\"."
   exit 2
fi
umask 002
if [ "$1" = "-lc-username" ] ; then
   lcun=$2
   shift 2
fi
if [ "$1" = "-bdiv-username" ] ; then
    bdun=$2
    shift 2
fi
if [ "$1" = "-bdiv-host" ] ; then
    bdhost=$2
    shift 2
fi

if [ $# -lt 1 ] ; then
  localhost
  sunset
  purple
  uv
  gauss 
  lilac
  rhea
  bgl
else
 while [ "$*" != "" ]
 do 
  case $1 in
    all|-a*)
      localhost
      sunset
      purple
      uv
      gauss 
      lilac
      rhea
      bgl
      shift;;
    local*pgc|-local*pgc)
      localhostpgc
      shift;;
    local*icc|-local*icc)
      localhosticc
      shift;;
    local*gcc|-local*gcc)
      localhostgcc
      shift;;
    localhost|-lo*)
      localhost
      shift;;
    sun*gcc|-sun*gcc)
      sunsetgcc
      shift;;
    sun*cc|-sun*cc)
      sunsetcc
      shift;;
    sun*|-sun*)
      sunset
      shift;;
    purple32|-pu*32)
      purple32
      shift;;
    purple64|-pu*64)
      purple64
      shift;;
    purple|-pu*)
      purple
      shift;;
    uv32|-uv*32)
      uv32
      shift;;
    uv64|-uv*64)
      uv64
      shift;;
    uv|-uv*)
      uv
      shift;;
    sccc|-sccc)
      sccc
      shift;;
    sc|-sc)
      sc
      shift;;
    gaus*icc|-gs*icc)
      gaussicc
      shift;;
    gaus*gcc|-gs*gcc)
      gaussgcc
      shift;;
    gaus*|-gs*)
      gauss
      shift;;
    rhea*icc|-rh*icc)
      rheaicc
      shift;;
    rhea*gcc|-rh*gcc)
      rheagcc
      shift;;
    rhea*|-rh*)
      rhea
      shift;;
    lil*|-li*)
      lilac
      shift;;
    slic*icc|-sl*icc)
      slicicc
      shift;;
    slic*gcc|-sl*gcc)
      slicgcc
      shift;;
    slic*|-sl*)
      slic
      shift;;
    bgltest|-bgltest)
      bgltest
      shift;;
    bgl|-bgl)
      bgl
      shift;;
    sh*|-sh*)
      shar
      shift;;
    *)
      shift;;
  esac
 done
fi
