#!/usr/local/bin/perl

# This script creates a directory element in a ClearCase VOB from the
# view-private directory name given as the first argument.  All other
# arguments are ignored.

$ct = "/usr/atria/bin/cleartool";
$name = shift(@ARGV);

if ($name =~ /^\s*$/)
{
    die "No name given.\n";
}

# Rename the old directory to $name_temporary.
rename($name,"${name}_temporary");

# Make a new directory as an element
$status = system("$ct mkdir $name");
$status /= 256;
if ($status != 0)
{
    # Things screwed up.  Reset everything.
    print STDERR <<"EOF";
ERROR: Unable to make directory element \"name\".
ERROR: $!
EOF
    rename("${name}_temporary",$name);
    exit(-1);
}

# Check to see if there's anything in $name_temporary that we need to move
$status = opendir(DIR,"${name}_temporary");
if ($status == 0)
{
    print STDERR <<"EOF";
ERROR: $!
ERROR: Unable to look in \"${name}_temporary\" to see if there are
ERROR: contents that need to be moved to \"$name\".  You're going to
ERROR: have to do that yourself.
EOF
    exit(-1);
}
@allfiles = grep(!/^\.\.?$/, readdir(DIR));
closedir(DIR);

if ($allfiles[0] ne undef)
{
    # There are things in the directory.  Move them.
    $status = system("mv ${name}_temporary/* $name");
    $status /= 256;
    if ($status != 0)
    {
        print STDERR <<"EOF";
WARNING: $!
WARNING: Unable to move the contents of "${name}_temporary" to "$name".
WARNING: You are going to have to do it yourself.
EOF
        exit(-1);
    }
}

rmdir("${name}_temporary");

exit(0);
