#!/bin/sh

# Since link creation for the public header files has been removed from
# the makefiles, this program builds those links instead.  Run it from
# the top of the source tree.

public="spi/SpiDraw.h silo/aio/aio.h silo/pdb/pdb.h silo/score/score.h silo/sdx/sdx.h silo/sdx/sdx.inc silo/sdx/sdxproto.h silo/silo/silo.h silo/silo/silo_f.h silo/silo/silo.inc silo/silo/silo_drivers.h silo/silo/silo_private.h silo/swat/swat.h spi/spi.h"

if [ -d include ]; then (
  set -x;
  cd include
  for f in $public; do
    rm -f `basename $f`
    ln -s ../$f .
  done
)
fi
