#!/bin/sh
#-----------------------------------------------------------------------
#
# SILO-INSTALL-CLOSED- Install the silo distributions on the closed
#                      network.
#
# Author: Eric Brugger
# Date:   April 6, 2001
#
# Usage:
#    silo-install-closed -v <version>
#
#-----------------------------------------------------------------------

test=no

user=`whoami`

#
# Parse the execute line, providing default values for error checking.
#
hitit=true
sunset=true
sc=true
tidalwave=true
white=true
lilac=true
gauss=true
ubgl=false

ver=undefined

#
# The loop is executed once for each symbol on the execute line.  This means
# that $1 may be blank for later executions of the loop if any "shift 2"
# commands are executed.  The variable abc is not used in the loop.
#
for abc
do
   case $1 in
      -none)
         hitit=false
         sunset=false
         sc=false
         tidalwave=false
         white=false
         lilac=false
         gauss=false
         ubgl=false
         shift
         ;;
      -hitit)
         hitit=false
         shift
         ;;
      +hitit)
         hitit=true
         shift
         ;;
      -sunset)
         sunset=false
         shift
         ;;
      +sunset)
         sunset=true
         shift
         ;;
      -sc)
         sc=false
         shift
         ;;
      +sc)
         sc=true
         shift
         ;;
      -tidalwave)
         tidalwave=false
         shift
         ;;
      +tidalwave)
         tidalwave=true
         shift
         ;;
      -white)
         white=false
         shift
         ;;
      +white)
         white=true
         shift
         ;;
      -lilac)
         lilac=false
         shift
         ;;
      +lilac)
         lilac=true
         shift
         ;;
      -gauss)
         gauss=false
         shift
         ;;
      +gauss)
         gauss=true
         shift
         ;;
      -ubgl)
         ubgl=false
         shift
         ;;
      +ubgl)
         ubgl=true
         shift
         ;;
      -v)
         ver=$2
         shift 2
         ;;
   esac
done

#
# Check that both the version and distribution name were provided.
#
if [ $ver = undefined ] ; then
   echo "Usage: -v <version>"
   exit
fi

#
# Install on hitit.
#
rm -f hitit
cat <<EOF > hitit
#!/bin/sh
cd /usr/gapps/silo
if test ! -e $ver ; then
   mkdir $ver
fi
if test -e $ver/redhat_7_ia32 ; then
   rm -rf $ver/redhat_7_ia32
fi
mkdir $ver/redhat_7_ia32
mkdir $ver/redhat_7_ia32/bin
mkdir $ver/redhat_7_ia32/include
mkdir $ver/redhat_7_ia32/lib
cd /gscratch/$user/hitit/silobuild
cp bin/browser           /usr/gapps/silo/$ver/redhat_7_ia32/bin
cp bin/silock            /usr/gapps/silo/$ver/redhat_7_ia32/bin
cp bin/silodiff          /usr/gapps/silo/$ver/redhat_7_ia32/bin
cp include/silo.h        /usr/gapps/silo/$ver/redhat_7_ia32/include
cp include/silo.inc      /usr/gapps/silo/$ver/redhat_7_ia32/include
cp include/sdx.h         /usr/gapps/silo/$ver/redhat_7_ia32/include
cp include/sdx.inc       /usr/gapps/silo/$ver/redhat_7_ia32/include
cp lib/libsilo.a         /usr/gapps/silo/$ver/redhat_7_ia32/lib
cp lib/libsiloh5.a       /usr/gapps/silo/$ver/redhat_7_ia32/lib
chgrp -R meshtv /usr/gapps/silo/$ver
find /usr/gapps/silo/$ver -type d -exec chmod 775 {} \;
find /usr/gapps/silo/$ver/redhat_7_ia32 -type f -exec chmod 664 {} \;
chmod 775 /usr/gapps/silo/$ver/redhat_7_ia32/bin/*
rm -f resultlog
echo "        install of silo on hitit"               > resultlog 2>&1
echo "       --------------------------"              >> resultlog 2>&1
echo ""                                               >> resultlog 2>&1
df -k /usr/gapps/silo                                 >> resultlog 2>&1
echo ""                                               >> resultlog 2>&1
ls -l /usr/gapps/silo/$ver/redhat_7_ia32/bin          >> resultlog 2>&1
ls -l /usr/gapps/silo/$ver/redhat_7_ia32/include      >> resultlog 2>&1
ls -l /usr/gapps/silo/$ver/redhat_7_ia32/lib          >> resultlog 2>&1
EOF

if [ $hitit = true ]
then
   if [ $test = no ] ; then
      scp -P 22 hitit hitit:install_silo_hitit
      ssh -p 22 hitit "chmod 750 install_silo_hitit;./install_silo_hitit"
   fi
fi

#
# Install on sunset.
#
rm -f sunset
cat <<EOF > sunset
#!/bin/sh
cd /usr/gapps/silo
if test ! -d $ver ; then
   mkdir $ver
fi
if test -d $ver/sunos_57 ; then
   rm -rf $ver/sunos_57
fi
mkdir $ver/sunos_57
mkdir $ver/sunos_57/bin
mkdir $ver/sunos_57/include
mkdir $ver/sunos_57/lib
cd /export/scratch/$user/sunset/silobuild
cp bin/browser           /usr/gapps/silo/$ver/sunos_57/bin
cp bin/silock            /usr/gapps/silo/$ver/sunos_57/bin
cp bin/silodiff          /usr/gapps/silo/$ver/sunos_57/bin
cp include/silo.h        /usr/gapps/silo/$ver/sunos_57/include
cp include/silo.inc      /usr/gapps/silo/$ver/sunos_57/include
cp include/sdx.h         /usr/gapps/silo/$ver/sunos_57/include
cp include/sdx.inc       /usr/gapps/silo/$ver/sunos_57/include
cp lib/libsilo.a         /usr/gapps/silo/$ver/sunos_57/lib
cp lib/libsiloh5.a       /usr/gapps/silo/$ver/sunos_57/lib
chgrp -R meshtv /usr/gapps/silo/$ver
find /usr/gapps/silo/$ver -type d -exec chmod 775 {} \;
find /usr/gapps/silo/$ver/sunos_57 -type f -exec chmod 664 {} \;
chmod 775 /usr/gapps/silo/$ver/sunos_57/bin/*
rm -f resultlog
echo "        install of silo on sunset"              > resultlog 2>&1
echo "       ---------------------------"             >> resultlog 2>&1
echo ""                                               >> resultlog 2>&1
df -k /usr/gapps/silo                                 >> resultlog 2>&1
echo ""                                               >> resultlog 2>&1
ls -l /usr/gapps/silo/$ver/sunos_57/bin               >> resultlog 2>&1
ls -l /usr/gapps/silo/$ver/sunos_57/include           >> resultlog 2>&1
ls -l /usr/gapps/silo/$ver/sunos_57/lib               >> resultlog 2>&1
EOF

if [ $sunset = true ]
then
   if [ $test = no ] ; then
      scp sunset sunset:install_silo_sunset
      ssh sunset "chmod 750 install_silo_sunset;./install_silo_sunset"
   fi
fi

#
# Install on sc.
#
rm -f sc
cat <<EOF > sc
#!/bin/sh
cd /usr/gapps/silo
if test ! -e $ver ; then
   mkdir $ver
fi
if test -e $ver/tru64_5 ; then
   rm -rf $ver/tru64_5
fi
mkdir $ver/tru64_5
mkdir $ver/tru64_5/bin
mkdir $ver/tru64_5/include
mkdir $ver/tru64_5/lib
cd /nfs/tmp1/$user/sc/silobuild
cp bin/browser           /usr/gapps/silo/$ver/tru64_5/bin
cp bin/silock            /usr/gapps/silo/$ver/tru64_5/bin
cp bin/silodiff          /usr/gapps/silo/$ver/tru64_5/bin
cp include/silo.h        /usr/gapps/silo/$ver/tru64_5/include
cp include/silo.inc      /usr/gapps/silo/$ver/tru64_5/include
cp include/sdx.h         /usr/gapps/silo/$ver/tru64_5/include
cp include/sdx.inc       /usr/gapps/silo/$ver/tru64_5/include
cp lib/libsilo.a         /usr/gapps/silo/$ver/tru64_5/lib
cp lib/libsiloh5.a       /usr/gapps/silo/$ver/tru64_5/lib
chgrp -R swat /usr/gapps/silo/$ver
find /usr/gapps/silo/$ver -type d -exec chmod 775 {} \;
find /usr/gapps/silo/$ver/tru64_5 -type f -exec chmod 664 {} \;
chmod 775 /usr/gapps/silo/$ver/tru64_5/bin/*
rm -f resultlog
echo "        install of silo on sc"              > resultlog 2>&1
echo "       -----------------------"             >> resultlog 2>&1
echo ""                                           >> resultlog 2>&1
df -k /usr/gapps/silo                             >> resultlog 2>&1
echo ""                                           >> resultlog 2>&1
ls -l /usr/gapps/silo/$ver/tru64_5/bin            >> resultlog 2>&1
ls -l /usr/gapps/silo/$ver/tru64_5/include        >> resultlog 2>&1
ls -l /usr/gapps/silo/$ver/tru64_5/lib            >> resultlog 2>&1
EOF

if [ $sc = true ]
then
   if [ $test = no ] ; then
      scp sc sc1:install_silo_sc
      ssh sc1 "chmod 750 install_silo_sc;./install_silo_sc"
   fi
fi

#
# Install on tidalwave.
#
rm -f tidalwave
cat <<EOF > tidalwave
#!/bin/sh
cd /usr/gapps/silo
if test ! -d $ver ; then
   mkdir $ver
fi
if test -d $ver/irix_6.5_o32 ; then
   rm -rf $ver/irix_6.5_o32
fi
if test -d $ver/irix_6.5_n32 ; then
   rm -rf $ver/irix_6.5_n32
fi
if test -d $ver/irix_6.5_64 ; then
   rm -rf $ver/irix_6.5_64
fi
mkdir $ver/irix_6.5_o32
mkdir $ver/irix_6.5_o32/bin
mkdir $ver/irix_6.5_o32/include
mkdir $ver/irix_6.5_o32/lib
mkdir $ver/irix_6.5_n32
mkdir $ver/irix_6.5_n32/bin
mkdir $ver/irix_6.5_n32/include
mkdir $ver/irix_6.5_n32/lib
mkdir $ver/irix_6.5_64
mkdir $ver/irix_6.5_64/bin
mkdir $ver/irix_6.5_64/include
mkdir $ver/irix_6.5_64/lib
cd /fc/san1/$user/tidalwave/silobuild
cp bin/browser           /usr/gapps/silo/$ver/irix_6.5_o32/bin
cp bin/silock            /usr/gapps/silo/$ver/irix_6.5_o32/bin
cp bin/silodiff          /usr/gapps/silo/$ver/irix_6.5_o32/bin
cp include/silo.h        /usr/gapps/silo/$ver/irix_6.5_o32/include
cp include/silo.inc      /usr/gapps/silo/$ver/irix_6.5_o32/include
cp include/sdx.h         /usr/gapps/silo/$ver/irix_6.5_o32/include
cp include/sdx.inc       /usr/gapps/silo/$ver/irix_6.5_o32/include
cp libo32/libsilo.a      /usr/gapps/silo/$ver/irix_6.5_o32/lib
cp bin/browser           /usr/gapps/silo/$ver/irix_6.5_n32/bin
cp bin/silock            /usr/gapps/silo/$ver/irix_6.5_n32/bin
cp bin/silodiff          /usr/gapps/silo/$ver/irix_6.5_n32/bin
cp include/silo.h        /usr/gapps/silo/$ver/irix_6.5_n32/include
cp include/silo.inc      /usr/gapps/silo/$ver/irix_6.5_n32/include
cp include/sdx.h         /usr/gapps/silo/$ver/irix_6.5_n32/include
cp include/sdx.inc       /usr/gapps/silo/$ver/irix_6.5_n32/include
cp libn32/libsilo.a      /usr/gapps/silo/$ver/irix_6.5_n32/lib
cp libn32/libsiloh5.a    /usr/gapps/silo/$ver/irix_6.5_n32/lib
cp bin/browser           /usr/gapps/silo/$ver/irix_6.5_64/bin
cp bin/silock            /usr/gapps/silo/$ver/irix_6.5_64/bin
cp bin/silodiff          /usr/gapps/silo/$ver/irix_6.5_64/bin
cp include/silo.h        /usr/gapps/silo/$ver/irix_6.5_64/include
cp include/silo.inc      /usr/gapps/silo/$ver/irix_6.5_64/include
cp include/sdx.h         /usr/gapps/silo/$ver/irix_6.5_64/include
cp include/sdx.inc       /usr/gapps/silo/$ver/irix_6.5_64/include
cp lib64/libsilo.a       /usr/gapps/silo/$ver/irix_6.5_64/lib
cp lib64/libsiloh5.a     /usr/gapps/silo/$ver/irix_6.5_64/lib
chgrp -R swat /usr/gapps/silo/$ver
find /usr/gapps/silo/$ver -type d -exec chmod 775 {} \;
find /usr/gapps/silo/$ver/irix_6.5_* -type f -exec chmod 664 {} \;
chmod 775 /usr/gapps/silo/$ver/irix_6.5_*/bin/*
rm -f resultlog
echo "        install of silo on tidalwave"        > resultlog 2>&1
echo "       ------------------------------"       >> resultlog 2>&1
echo ""                                            >> resultlog 2>&1
df -k /usr/gapps/silo                              >> resultlog 2>&1
echo ""                                            >> resultlog 2>&1
ls -l /usr/gapps/silo/$ver/irix_6.5_*/bin          >> resultlog 2>&1
ls -l /usr/gapps/silo/$ver/irix_6.5_*/include      >> resultlog 2>&1
ls -l /usr/gapps/silo/$ver/irix_6.5_*/lib          >> resultlog 2>&1
EOF

if [ $tidalwave = true ]
then
   if [ $test = no ] ; then
      scp tidalwave tidalwave:install_silo_tidalwave
      ssh tidalwave "chmod 750 install_silo_tidalwave;./install_silo_tidalwave"
   fi
fi

#
# Install on white.
#
rm -f white
cat <<EOF > white
#!/bin/sh
cd /usr/gapps/silo
if test ! -e $ver ; then
   mkdir $ver
fi
if test -e $ver/aix_5_ll ; then
   rm -rf $ver/aix_5_ll
fi
if test -e $ver/aix_5_64_fed ; then
   rm -f $ver/aix_5_64_fed
fi
mkdir $ver/aix_5_ll
mkdir $ver/aix_5_ll/bin
mkdir $ver/aix_5_ll/include
mkdir $ver/aix_5_ll/lib
ln -s aix_5_ll $ver/aix_5_64_fed
cd /nfs/tmp1/$user/white/silobuild
cp bin/browser           /usr/gapps/silo/$ver/aix_5_ll/bin
cp bin/silock            /usr/gapps/silo/$ver/aix_5_ll/bin
cp bin/silodiff          /usr/gapps/silo/$ver/aix_5_ll/bin
cp include/silo.h        /usr/gapps/silo/$ver/aix_5_ll/include
cp include/silo.inc      /usr/gapps/silo/$ver/aix_5_ll/include
cp include/sdx.h         /usr/gapps/silo/$ver/aix_5_ll/include
cp include/sdx.inc       /usr/gapps/silo/$ver/aix_5_ll/include
cp lib/libsilo.a         /usr/gapps/silo/$ver/aix_5_ll/lib
cp lib/libsiloh5.a       /usr/gapps/silo/$ver/aix_5_ll/lib
chgrp -R swat /usr/gapps/silo/$ver
find /usr/gapps/silo/$ver -type d -exec chmod 775 {} \;
find /usr/gapps/silo/$ver/aix_5_ll -type f -exec chmod 664 {} \;
chmod 775 /usr/gapps/silo/$ver/aix_5_ll/bin/*
rm -f resultlog
echo "        install of silo on white"               > resultlog 2>&1
echo "       --------------------------"              >> resultlog 2>&1
echo ""                                               >> resultlog 2>&1
df -k /usr/gapps/silo                                 >> resultlog 2>&1
echo ""                                               >> resultlog 2>&1
ls -l /usr/gapps/silo/$ver/aix_5_ll/bin               >> resultlog 2>&1
ls -l /usr/gapps/silo/$ver/aix_5_ll/include           >> resultlog 2>&1
ls -l /usr/gapps/silo/$ver/aix_5_ll/lib               >> resultlog 2>&1
EOF

if [ $white = true ]
then
   if [ $test = no ] ; then
      scp white white:install_silo_white
      ssh white "chmod 750 install_silo_white;./install_silo_white"
   fi
fi

#
# Install on lilac.
#
rm -f lilac
cat <<EOF > lilac
#!/bin/sh
cd /usr/gapps/silo
if test ! -e $ver ; then
   mkdir $ver
fi
if test -e $ver/chaos_3_x86_elan3 ; then
   rm -rf $ver/chaos_3_x86_elan3
fi
mkdir $ver/chaos_3_x86_elan3
mkdir $ver/chaos_3_x86_elan3/bin
mkdir $ver/chaos_3_x86_elan3/include
mkdir $ver/chaos_3_x86_elan3/lib
ln -s chaos_3_x86_elan3 $ver/chaos_3_x86
cd /usr/tmp/$user/lilac/silobuild
cp bin/browser           /usr/gapps/silo/$ver/chaos_3_x86_elan3/bin
cp bin/silock            /usr/gapps/silo/$ver/chaos_3_x86_elan3/bin
cp bin/silodiff          /usr/gapps/silo/$ver/chaos_3_x86_elan3/bin
cp include/silo.h        /usr/gapps/silo/$ver/chaos_3_x86_elan3/include
cp include/silo.inc      /usr/gapps/silo/$ver/chaos_3_x86_elan3/include
cp include/sdx.h         /usr/gapps/silo/$ver/chaos_3_x86_elan3/include
cp include/sdx.inc       /usr/gapps/silo/$ver/chaos_3_x86_elan3/include
cp lib/libsilo.a         /usr/gapps/silo/$ver/chaos_3_x86_elan3/lib
cp lib/libsiloh5.a       /usr/gapps/silo/$ver/chaos_3_x86_elan3/lib
chgrp -R swat /usr/gapps/silo/$ver
find /usr/gapps/silo/$ver -type d -exec chmod 775 {} \;
find /usr/gapps/silo/$ver/chaos_3_x86_elan3 -type f -exec chmod 664 {} \;
chmod 775 /usr/gapps/silo/$ver/chaos_3_x86_elan3/bin/*
rm -f resultlog
echo "        install of silo on lilac"               > resultlog 2>&1
echo "       --------------------------"              >> resultlog 2>&1
echo ""                                               >> resultlog 2>&1
df -k /usr/gapps/silo                                 >> resultlog 2>&1
echo ""                                               >> resultlog 2>&1
ls -l /usr/gapps/silo/$ver/chaos_3_x86_elan3/bin      >> resultlog 2>&1
ls -l /usr/gapps/silo/$ver/chaos_3_x86_elan3/include  >> resultlog 2>&1
ls -l /usr/gapps/silo/$ver/chaos_3_x86_elan3/lib      >> resultlog 2>&1
EOF

if [ $lilac = true ]
then
   if [ $test = no ] ; then
      scp lilac lilac3:install_silo_lilac
      ssh lilac3 "chmod 750 install_silo_lilac;./install_silo_lilac"
   fi
fi

#
# Install on gauss.
#
rm -f gauss
cat <<EOF > gauss
#!/bin/sh
cd /usr/gapps/silo
if test ! -e $ver ; then
   mkdir $ver
fi
if test -e $ver/chaos_3_x86_64_ib ; then
   rm -rf $ver/chaos_3_x86_64_ib
fi
mkdir $ver/chaos_3_x86_64_ib
mkdir $ver/chaos_3_x86_64_ib/bin
mkdir $ver/chaos_3_x86_64_ib/include
mkdir $ver/chaos_3_x86_64_ib/lib
cd /usr/tmp/$user/gauss/silobuild
cp bin/browser           /usr/gapps/silo/$ver/chaos_3_x86_64_ib/bin
cp bin/silock            /usr/gapps/silo/$ver/chaos_3_x86_64_ib/bin
cp bin/silodiff          /usr/gapps/silo/$ver/chaos_3_x86_64_ib/bin
cp include/silo.h        /usr/gapps/silo/$ver/chaos_3_x86_64_ib/include
cp include/silo.inc      /usr/gapps/silo/$ver/chaos_3_x86_64_ib/include
cp include/sdx.h         /usr/gapps/silo/$ver/chaos_3_x86_64_ib/include
cp include/sdx.inc       /usr/gapps/silo/$ver/chaos_3_x86_64_ib/include
cp lib/libsilo.a         /usr/gapps/silo/$ver/chaos_3_x86_64_ib/lib
cp lib/libsiloh5.a       /usr/gapps/silo/$ver/chaos_3_x86_64_ib/lib
chgrp -R swat /usr/gapps/silo/$ver
find /usr/gapps/silo/$ver -type d -exec chmod 775 {} \;
find /usr/gapps/silo/$ver/chaos_3_x86_64_ib -type f -exec chmod 664 {} \;
chmod 775 /usr/gapps/silo/$ver/chaos_3_x86_64_ib/bin/*
rm -f resultlog
echo "        install of silo on gauss"               > resultlog 2>&1
echo "       --------------------------"              >> resultlog 2>&1
echo ""                                               >> resultlog 2>&1
df -k /usr/gapps/silo                                 >> resultlog 2>&1
echo ""                                               >> resultlog 2>&1
ls -l /usr/gapps/silo/$ver/chaos_3_x86_64_ib/bin      >> resultlog 2>&1
ls -l /usr/gapps/silo/$ver/chaos_3_x86_64_ib/include  >> resultlog 2>&1
ls -l /usr/gapps/silo/$ver/chaos_3_x86_64_ib/lib      >> resultlog 2>&1
EOF

if [ $gauss = true ]
then
   if [ $test = no ] ; then
      scp gauss gauss:install_silo_gauss
      ssh gauss2 "chmod 750 install_silo_gauss;./install_silo_gauss"
   fi
fi

#
# Install on ubgl.
#
rm -f ubgl
cat <<EOF > ubgl
#!/bin/sh
cd /usr/gapps/silo
if test ! -e $ver ; then
   mkdir $ver
fi
if test -e $ver/sles_9_ppc64 ; then
   rm -rf $ver/sles_9_ppc64
fi
mkdir $ver/sles_9_ppc64
mkdir $ver/sles_9_ppc64/bin
mkdir $ver/sles_9_ppc64/include
mkdir $ver/sles_9_ppc64/lib
cd /usr/tmp/$user/ubgl/silobuild
cp bin/browser           /usr/gapps/silo/$ver/sles_9_ppc64/bin
cp bin/silock            /usr/gapps/silo/$ver/sles_9_ppc64/bin
cp bin/silodiff          /usr/gapps/silo/$ver/sles_9_ppc64/bin
cp include/silo.h        /usr/gapps/silo/$ver/sles_9_ppc64/include
cp include/silo.inc      /usr/gapps/silo/$ver/sles_9_ppc64/include
cp include/sdx.h         /usr/gapps/silo/$ver/sles_9_ppc64/include
cp include/sdx.inc       /usr/gapps/silo/$ver/sles_9_ppc64/include
cp lib/libsilo.a         /usr/gapps/silo/$ver/sles_9_ppc64/lib
cp lib/libsiloh5.a       /usr/gapps/silo/$ver/sles_9_ppc64/lib
cp lib/Silo.so           /usr/gapps/silo/$ver/sles_9_ppc64/lib
chgrp -R swat /usr/gapps/silo/$ver
find /usr/gapps/silo/$ver -type d -exec chmod 775 {} \;
find /usr/gapps/silo/$ver/sles_9_ppc64 -type f -exec chmod 664 {} \;
chmod 775 /usr/gapps/silo/$ver/sles_9_ppc64/bin/*
rm -f resultlog
echo "        install of silo on ubgl"                > resultlog 2>&1
echo "       -------------------------"               >> resultlog 2>&1
echo ""                                               >> resultlog 2>&1
df -k /usr/gapps/silo                                 >> resultlog 2>&1
echo ""                                               >> resultlog 2>&1
ls -l /usr/gapps/silo/$ver/sles_9_ppc64/bin           >> resultlog 2>&1
ls -l /usr/gapps/silo/$ver/sles_9_ppc64/include       >> resultlog 2>&1
ls -l /usr/gapps/silo/$ver/sles_9_ppc64/lib           >> resultlog 2>&1
EOF

if [ $ubgl = true ]
then
   if [ $test = no ] ; then
      scp ubgl ubgl:install_silo_ubgl
      ssh ubgl "chmod 750 install_silo_ubgl;./install_silo_ubgl"
   fi
fi

#
# Clean up.
#
if [ $test = no ] ; then
   rm -f hitit sunset sc tidalwave white lilac gauss ubgl
fi
