#!/bin/sh
#-----------------------------------------------------------------------
#
# SILO-BUILD-OPEN - Build the silo distributions on the open network.
#
# Author: Eric Brugger
# Date:   September 19, 2000
#
# Usage:
#    silo-build-open -d <distribution> -l <LC username>
#
#-----------------------------------------------------------------------

test=no

user=`whoami`
lc_username=$user

#
# Set the user e-mail address.
#
emailName=brugger1@llnl.gov
case $user in
   ahern)
      emailName=ahern1@llnl.gov
      ;;
   kbonnell)
      emailName=bonnell2@llnl.gov
      ;;
   brugger)
      emailName=brugger1@llnl.gov
      ;;
   childs)
      emailName=childs3@llnl.gov
      ;;
   jennings)
      emailName=jennings4@llnl.gov
      ;;
   meredith)
      emailName=meredith6@llnl.gov
      ;;
   mcmiller)
      emailName=miller86@llnl.gov
      ;;
   miller)
      emailName=miller86@llnl.gov
      ;;
   murguia)
      emailName=murguia1@llnl.gov
      ;;
   whitlocb)
      emailName=whitlock2@llnl.gov
      ;;
esac

#
# Parse the execute line, providing default values for error checking.
#
hoth=true
sunspot=true
quad=true
gps=true
berg=true
pengra=true
thunder=true
ubgl=true

dist=undefined

#
# The loop is executed once for each symbol on the execute line.  This means
# that $1 may be blank for later executions of the loop if any "shift 2"
# commands are executed.  The variable abc is not used in the loop.
#
for abc
do
   case $1 in
      -none)
	 hoth=false
         sunspot=false
         quad=false
         gps=false
         berg=false
         pengra=false
         thunder=false
         shift
         ;;
      -hoth)
         hoth=false
         shift
         ;;
      +hoth)
         hoth=true
         shift
         ;;
      -sunspot)
         sunspot=false
         shift
         ;;
      +sunspot)
         sunspot=true
         shift
         ;;
      -quad)
         quad=false
         shift
         ;;
      +quad)
         quad=true
         shift
         ;;
      -gps)
         gps=false
         shift
         ;;
      +gps)
         gps=true
         shift
         ;;
      -berg)
         berg=false
         shift
         ;;
      +berg)
         berg=true
         shift
         ;;
      -pengra)
         pengra=false
         shift
         ;;
      +pengra)
         pengra=true
         shift
         ;;
      -thunder)
         thunder=false
         shift
         ;;
      +thunder)
         thunder=true
         shift
         ;;
      -ubgl)
         ubgl=false
         shift
         ;;
      +ubgl)
         ubgl=true
         shift
         ;;
      -d)
         dist=$2
         shift 2
         ;;
      -l)
         lc_username=$2
	 shift 2
	 ;;
   esac
done

#
# Check that both the version and distribution name were provided.
#
if [ $dist = undefined ]
then
   echo "Usage: -d <distribution>"
   exit
fi

#
# Check that the distribution exists.
#
distfile=$dist.sh
if [ ! -f $distfile ]
then
   echo "Distribution file doesn't exist."
   exit
fi

#
# Build on hoth
#
rm -f hoth
cat <<EOF > hoth
#!/bin/sh
if test ! -d /usr/tmp/$user ; then
   mkdir /usr/tmp/$user
fi
if test ! -d /usr/tmp/$user/hoth ; then
   mkdir /usr/tmp/$user/hoth
fi
rm -rf /usr/tmp/$user/hoth/silobuild
mkdir /usr/tmp/$user/hoth/silobuild
mv $dist.sh.hoth /usr/tmp/$user/hoth/silobuild/$dist.sh
cd /usr/tmp/$user/hoth/silobuild
sh $dist.sh > buildlog 2>&1
mkdir bin include lib
cd $dist
env CFLAGS=-O2 ./configure --without-readline --without-exodus --with-hdf5=/usr/gapps/hdf5/1.6.0/LinuxE3/serial/64/optim/include,/usr/gapps/hdf5/1.6.0/LinuxE3/serial/64/optim/lib --disable-static >> ../buildlog 2>&1
make -j 4 >> ../buildlog 2>&1
mv lib/libsilo.a ../lib/libsiloh5.a
mv bin/browser ../bin/browser
mv bin/silock ../bin/silock
cp bin/silodiff ../bin/silodiff
make distclean >> ../buildlog 2>&1
env CFLAGS=-O2 ./configure --without-readline --without-exodus --without-hdf5 --disable-static >> ../buildlog 2>&1
make -j 4 >> ../buildlog 2>&1
cp lib/libsilo.a ../lib/libsilo.a
cp include/silo.h include/silo.inc include/sdx.h include/sdx.inc ../include
cp lib/Silo.so ../lib/
cd ..
rm -f resultlog
uname -a > resultlog 2>&1
ls -l bin include lib >> resultlog 2>&1
mail $emailName < resultlog
EOF

if [ $hoth = true ]
then
   if [ $test = no ]
   then
      scp hoth hoth:buildsilo_hoth
      scp $dist.sh hoth:$dist.sh.hoth
      ssh hoth "chmod 750 buildsilo_hoth;./buildsilo_hoth" &
   fi
fi

#
# Build on sunspot.
#
# We are building with debug because there appears to be a compiler bug
# that prevents setjmp and longjmp from working with optimization.
#
rm -f sunspot
cat <<EOF > sunspot
#!/bin/sh
if test ! -d /export/scratch/$user ; then
   mkdir /export/scratch/$user
fi
if test ! -d /export/scratch/$user/sunspot ; then
   mkdir /export/scratch/$user/sunspot
fi
rm -rf /export/scratch/$user/sunspot/silobuild
mkdir /export/scratch/$user/sunspot/silobuild
mv $dist.sh.sunspot /export/scratch/$user/sunspot/silobuild/$dist.sh
cd /export/scratch/$user/sunspot/silobuild
sh $dist.sh > buildlog 2>&1
mkdir bin include lib
cd $dist
env CFLAGS=-g ./configure --without-readline --without-exodus --with-hdf5=/usr/gapps/hdf5/1.6.0/SunOS/serial/default/optim/include,/usr/gapps/hdf5/1.6.0/SunOS/serial/default/optim/lib >> ../buildlog 2>&1
make -j 4 >> ../buildlog 2>&1
mv lib/libsilo.a ../lib/libsiloh5.a
mv bin/browser ../bin/browser
mv bin/silock ../bin/silock
cp bin/silodiff ../bin/silodiff
make distclean >> ../buildlog 2>&1
env CFLAGS=-g ./configure --without-readline --without-exodus --without-hdf5 >> ../buildlog 2>&1
make -j 4 >> ../buildlog 2>&1
cp lib/libsilo.a ../lib/libsilo.a
cp include/silo.h include/silo.inc include/sdx.h include/sdx.inc ../include
cp lib/Silo.so ../lib/
cd ..
rm -f resultlog
uname -a > resultlog 2>&1
ls -l bin include lib >> resultlog 2>&1
mail $emailName < resultlog
EOF

if [ $sunspot = true ]
then
   if [ $test = no ]
   then
      scp sunspot sunspot:buildsilo_sunspot
      scp $dist.sh sunspot:$dist.sh.sunspot
      ssh sunspot "chmod 750 buildsilo_sunspot;./buildsilo_sunspot" &
   fi
fi

#
# Build on quad.
#
rm -f quad
cat <<EOF > quad
#!/bin/sh
if test ! -d /usr/tmp/$user ; then
   mkdir /usr/tmp/$user
fi
if test ! -d /usr/tmp/$user/quad ; then
   mkdir /usr/tmp/$user/quad
fi
rm -rf /usr/tmp/$user/quad/silobuild
mkdir /usr/tmp/$user/quad/silobuild
mv $dist.sh.quad /usr/tmp/$user/quad/silobuild/$dist.sh
cd /usr/tmp/$user/quad/silobuild
sh $dist.sh > buildlog 2>&1
mkdir bin include libn32 lib64
cd $dist
env CC=cc CFLAGS="-O2 -n32 -c99" ./configure --without-readline --without-exodus --with-hdf5=/usr/gapps/visit/hdf5/1.6.0/irix_6.5_n32/include,/usr/gapps/visit/hdf5/1.6.0/irix_6.5_n32/lib >> ../buildlog 2>&1
env PARALLEL=4 make -P >> ../buildlog 2>&1
mv lib/libsilo.a ../libn32/libsiloh5.a
make distclean >> ../buildlog 2>&1
env CC=cc CFLAGS="-O2 -64 -c99" ./configure --without-readline --without-exodus --with-hdf5=/usr/gapps/visit/hdf5/1.6.0/irix_6.5_64/include,/usr/gapps/visit/hdf5/1.6.0/irix_6.5_64/lib >> ../buildlog 2>&1
env PARALLEL=4 make -P >> ../buildlog 2>&1
mv lib/libsilo.a ../lib64/libsiloh5.a
mv bin/browser ../bin/browser
mv bin/silock ../bin/silock
cp bin/silodiff ../bin/silodiff
make distclean >> ../buildlog 2>&1
env CC=cc CFLAGS="-O2 -n32 -c99" ./configure --without-readline --without-exodus --without-hdf5 >> ../buildlog 2>&1
env PARALLEL=4 make -P >> ../buildlog 2>&1
mv lib/libsilo.a ../libn32/libsilo.a
make distclean >> ../buildlog 2>&1
env CC=cc CFLAGS="-O2 -64 -c99" ./configure --without-readline --without-exodus --without-hdf5 >> ../buildlog 2>&1
env PARALLEL=4 make -P >> ../buildlog 2>&1
cp lib/libsilo.a ../lib64/libsilo.a
cp include/silo.h include/silo.inc include/sdx.h include/sdx.inc ../include
cd ..
rm -f resultlog
uname -a > resultlog 2>&1
ls -l bin include libn32 lib64 >> resultlog 2>&1
mail $emailName < resultlog
EOF

if [ $quad = true ]
then
   if [ $test = no ]
   then
      scp quad quad:buildsilo_quad
      scp $dist.sh quad:$dist.sh.quad
      ssh quad "chmod 750 buildsilo_quad;./buildsilo_quad " &
   fi
fi

#
# Build on gps.
#
rm -f gps
cat <<EOF > gps
#!/bin/sh
if test ! -d /nfs/tmp0/$lc_username ; then
   mkdir /nfs/tmp0/$lc_username
fi
if test ! -d /nfs/tmp0/$lc_username/gps ; then
   mkdir /nfs/tmp0/$lc_username/gps
fi
rm -rf /nfs/tmp0/$lc_username/gps/silobuild
mkdir /nfs/tmp0/$lc_username/gps/silobuild
mv $dist.sh.gps /nfs/tmp0/$lc_username/gps/silobuild/$dist.sh
cd /nfs/tmp0/$lc_username/gps/silobuild
sh $dist.sh > buildlog 2>&1
mkdir bin include lib
cd $dist
./configure --without-readline --without-exodus --with-hdf5=/usr/local/hdf5/hdf5-1.6.0/serial/include,/usr/local/hdf5/hdf5-1.6.0/serial/lib >> ../buildlog 2>&1
make >> ../buildlog 2>&1
mv lib/libsilo.a ../lib/libsiloh5.a
mv bin/browser ../bin/browser
mv bin/silock ../bin/silock
cp bin/silodiff ../bin/silodiff
make distclean >> ../buildlog 2>&1
./configure --without-readline --without-exodus --without-hdf5 >> ../buildlog 2>&1
make >> ../buildlog 2>&1
cp lib/libsilo.a ../lib/libsilo.a
cp include/silo.h include/silo.inc include/sdx.h include/sdx.inc ../include
cd ..
rm -f resultlog
uname -a > resultlog 2>&1
ls -l bin include lib >> resultlog 2>&1
mail $emailName < resultlog
EOF

if [ $gps = true ]
then
   if [ $test = no ]
   then
      scp gps $lc_username@gps15:buildsilo_gps
      scp $dist.sh $lc_username@gps15:$dist.sh.gps
      ssh gps15 -l $lc_username "chmod 750 buildsilo_gps;./buildsilo_gps" &
   fi
fi

#
# Build on berg.
#
rm -f berg
cat <<EOF > berg
#!/bin/sh
if test ! -d /nfs/tmp0/$lc_username ; then
   mkdir /nfs/tmp0/$lc_username
fi
if test ! -d /nfs/tmp0/$lc_username/berg ; then
   mkdir /nfs/tmp0/$lc_username/berg
fi
rm -rf /nfs/tmp0/$lc_username/berg/silobuild
mkdir /nfs/tmp0/$lc_username/berg/silobuild
mv $dist.sh.berg /nfs/tmp0/$lc_username/berg/silobuild/$dist.sh
cd /nfs/tmp0/$lc_username/berg/silobuild
sh $dist.sh > buildlog 2>&1
mkdir bin include lib
cd $dist
env LDFLAGS=-q64 AR="ar -X 64" CFLAGS="-q64 -O2" ./configure --without-readline --without-exodus --with-hdf5=/usr/local/hdf5/hdf5-1.6.0/serial/64/include,/usr/local/hdf5/hdf5-1.6.0/serial/64/lib >> ../buildlog 2>&1
make >> ../buildlog 2>&1
mv lib/libsilo.a ../lib/libsiloh5.a
mv bin/browser ../bin/browser
mv bin/silock ../bin/silock
cp bin/silodiff ../bin/silodiff
make distclean >> ../buildlog 2>&1
mv ../lib/libsiloh5.a lib/libsilo.a
env LDFLAGS=-q32 AR="ar -X 32" CFLAGS="-q32 -O2" ./configure --without-readline --without-exodus --with-hdf5=/usr/local/hdf5/hdf5-1.6.0/serial/32/include,/usr/local/hdf5/hdf5-1.6.0/serial/32/lib >> ../buildlog 2>&1
make >> ../buildlog 2>&1
mv lib/libsilo.a ../lib/libsiloh5.a
make distclean >> ../buildlog 2>&1
env LDFLAGS=-q64 AR="ar -X 64" CFLAGS="-q64 -O2" ./configure --without-readline --without-exodus --without-hdf5 >> ../buildlog 2>&1
make >> ../buildlog 2>&1
mv lib/libsilo.a ../lib/libsilo.a
make distclean >> ../buildlog 2>&1
mv ../lib/libsilo.a lib/libsilo.a
env LDFLAGS=-q32 AR="ar -X 32" CFLAGS="-q32 -O2" ./configure --without-readline --without-exodus --without-hdf5 >> ../buildlog 2>&1
make >> ../buildlog 2>&1
cp lib/libsilo.a ../lib/libsilo.a
cp include/silo.h include/silo.inc include/sdx.h include/sdx.inc ../include
cd ..
rm -f resultlog
uname -a > resultlog 2>&1
ls -l bin include lib >> resultlog 2>&1
mail $emailName < resultlog
EOF

if [ $berg = true ]
then
   if [ $test = no ]
   then
      scp berg $lc_username@berg:buildsilo_berg
      scp $dist.sh $lc_username@berg:$dist.sh.berg
      ssh berg -l $lc_username "chmod 750 buildsilo_berg;./buildsilo_berg" &
      sleep 4
   fi
fi

#
# Build on pengra.
#
rm -f pengra
cat <<EOF > pengra
#!/bin/sh
if test ! -d /nfs/tmp0/$lc_username ; then
   mkdir /nfs/tmp0/$lc_username
fi
if test ! -d /nfs/tmp0/$lc_username/pengra ; then
   mkdir /nfs/tmp0/$lc_username/pengra
fi
rm -rf /nfs/tmp0/$lc_username/pengra/silobuild
mkdir /nfs/tmp0/$lc_username/pengra/silobuild
mv $dist.sh.pengra /nfs/tmp0/$lc_username/pengra/silobuild/$dist.sh
cd /nfs/tmp0/$lc_username/pengra/silobuild
sh $dist.sh > buildlog 2>&1
mkdir bin include lib
cd $dist
env CFLAGS=-O2 ./configure --without-readline --without-exodus --with-hdf5=/usr/local/hdf5/hdf5-1.6.0/serial_gcc/include,/usr/local/hdf5/hdf5-1.6.0/serial_gcc/lib --disable-static >> ../buildlog 2>&1
make >> ../buildlog 2>&1
mv lib/libsilo.a ../lib/libsiloh5.a
mv bin/browser ../bin/browser
mv bin/silock ../bin/silock
cp bin/silodiff ../bin/silodiff
make distclean >> ../buildlog 2>&1
env CFLAGS=-O2 ./configure --without-readline --without-exodus --without-hdf5 --disable-static >> ../buildlog 2>&1
make >> ../buildlog 2>&1
cp lib/libsilo.a ../lib/libsilo.a
cp include/silo.h include/silo.inc include/sdx.h include/sdx.inc ../include
cp lib/Silo.so ../lib/
cd ..
rm -f resultlog
uname -a > resultlog 2>&1
ls -l bin include lib >> resultlog 2>&1
mail $emailName < resultlog
EOF

if [ $pengra = true ]
then
   if [ $test = no ]
   then
      scp pengra $lc_username@pengra:buildsilo_pengra
      scp $dist.sh $lc_username@pengra:$dist.sh.pengra
      ssh pengra -l $lc_username "chmod 750 buildsilo_pengra;./buildsilo_pengra" &
   fi
fi

#
# Build on thunder.
#
rm -f thunder
cat <<EOF > thunder
#!/bin/sh
if test ! -d /usr/tmp/$lc_username ; then
   mkdir /usr/tmp/$lc_username
fi
if test ! -d /usr/tmp/$lc_username/thunder ; then
   mkdir /usr/tmp/$lc_username/thunder
fi
rm -rf /usr/tmp/$lc_username/thunder/silobuild
mkdir /usr/tmp/$lc_username/thunder/silobuild
mv $dist.sh.thunder /usr/tmp/$lc_username/thunder/silobuild/$dist.sh
cd /usr/tmp/$lc_username/thunder/silobuild
sh $dist.sh > buildlog 2>&1
mkdir gcc
mkdir gcc/{bin,include,lib}
mkdir icc
mkdir icc/{bin,include,lib}
cd $dist
env CFLAGS="-O2 -fPIC" CXXFLAGS="-O2 -fPIC" ./configure --without-readline --without-exodus --with-hdf5=/usr/local/hdf5/hdf5-1.6.0/serial_gcc/include,/usr/local/hdf5/hdf5-1.6.0/serial_gcc/lib --disable-static >> ../buildlog 2>&1
make >> ../buildlog 2>&1
mv lib/libsilo.a ../gcc/lib/libsiloh5.a
mv bin/browser ../gcc/bin/browser
mv bin/silock ../gcc/bin/silock
cp bin/silodiff ../gcc/bin/silodiff
make distclean >> ../buildlog 2>&1
env CFLAGS="-O2 -fPIC" CXXFLAGS="-O2 -fPIC" ./configure --without-readline --without-exodus --without-hdf5 --disable-static >> ../buildlog 2>&1
make >> ../buildlog 2>&1
cp lib/libsilo.a ../gcc/lib/libsilo.a
cp include/silo.h include/silo.inc include/sdx.h include/sdx.inc ../gcc/include
cp lib/Silo.so ../gcc/lib
env CC=icc CXX=icc CFLAGS="-O2 -fPIC" CXXFLAGS="-O2 -fPIC" ./configure --without-readline --without-exodus --with-hdf5=/usr/local/hdf5/hdf5-1.6.4/serial/include,/usr/local/hdf5/hdf5-1.6.4/serial/lib --disable-static >> ../buildlog 2>&1
make >> ../buildlog 2>&1
mv lib/libsilo.a ../icc/lib/libsiloh5.a
mv bin/browser ../icc/bin/browser
mv bin/silock ../icc/bin/silock
cp bin/silodiff ../icc/bin/silodiff
make distclean >> ../buildlog 2>&1
env CC=icc CXX=icc CFLAGS="-O2 -fPIC" CXXFLAGS="-O2 -fPIC" ./configure --without-readline --without-exodus --without-hdf5 --disable-static >> ../buildlog 2>&1
make >> ../buildlog 2>&1
cp lib/libsilo.a ../icc/lib/libsilo.a
cp include/silo.h include/silo.inc include/sdx.h include/sdx.inc ../icc/include
cp lib/Silo.so ../icc/lib
cd ..
rm -f resultlog
uname -a > resultlog 2>&1
ls -l gcc/{bin,include,lib} icc/{bin,include,lib} >> resultlog 2>&1
mail $emailName < resultlog
EOF

if [ $thunder = true ]
then
   if [ $test = no ]
   then
      scp thunder $lc_username@thunder:buildsilo_thunder
      scp $dist.sh $lc_username@thunder:$dist.sh.thunder
      ssh thunder3 -l $lc_username "chmod 750 buildsilo_thunder;./buildsilo_thunder" &
   fi
fi

#
# Build on ubgl.
#
rm -f ubgl
cat <<EOF > ubgl
#!/bin/sh
if test ! -d /tmp/$user ; then
   mkdir /tmp/$user
fi
if test ! -d /tmp/$user/ubgl ; then
   mkdir /tmp/$user/ubgl
fi
rm -rf /tmp/$user/ubgl/silobuild
mkdir /tmp/$user/ubgl/silobuild
mv $dist.sh.ubgl /tmp/$user/ubgl/silobuild/$dist.sh
cd /tmp/$user/ubgl/silobuild
sh $dist.sh > buildlog 2>&1
mkdir bin include lib
cd $dist
#
# Note: build the tools for the front end
# nodes but libs for the back end nodes.
#
env CC=gcc CFLAGS="-O2" ./configure --without-readline --without-exodus --with-hdf5=/usr/local/tools/hdf5/hdf5-1.6.4/serial/include,/usr/local/tools/hdf5/hdf5-1.6.4/serial/lib >> ../buildlog 2>&1
make >> ../buildlog 2>&1
mv bin/browser ../bin/browser
mv bin/silock ../bin/silock
cp bin/silodiff ../bin/silodiff
cp lib/Silo.so ../lib/
make distclean >> ../buildlog 2>&1
env CFLAGS="-O2" ./configure --without-readline --without-exodus --disable-browser --with-hdf5=/usr/local/tools/hdf5/hdf5-1.6.4/serial/include,/usr/local/tools/hdf5/hdf5-1.6.4/serial/lib >> ../buildlog 2>&1
make >> ../buildlog 2>&1
mv lib/libsilo.a ../lib/libsiloh5.a
make distclean >> ../buildlog 2>&1
env CFLAGS="-O2" ./configure --without-readline --without-exodus --without-hdf5 >> ../buildlog 2>&1
make >> ../buildlog 2>&1
mv lib/libsilo.a ../lib/libsilo.a
make distclean >> ../buildlog 2>&1
cp include/silo.h include/silo.inc include/sdx.h include/sdx.inc ../include
cd ..
rm -f resultlog
uname -a > resultlog 2>&1
ls -l bin include lib >> resultlog 2>&1
EOF

if [ $ubgl = true ]
then
   if [ $test = no ]
   then
      scp ubgl ubgl:buildsilo_ubgl
      scp $dist.sh ubgl:$dist.sh.ubgl
      ssh ubgl "chmod 750 buildsilo_ubgl;./buildsilo_ubgl" &
      sleep 4
   fi
fi




#
# Clean up.
#
if [ $test = no ]
then
   rm -f hoth sunspot quad gps berg pengra thunder ubgl
fi
