#!/bin/sh

### Purpose:
#   Prints the names of all the important SILO files.

### Programmer:
#   Robb Matzke
#   28 Feb 1997

### Modifications
#
#       Sean Ahern, Mon Apr 22 11:21:25 PDT 2002
#       Removed unproto.

if [ ! -d silo/silo ]; then
   echo "Invoke `basename $0` from the root of the meshtv source tree." 2>&1
   exit 1
fi

# It's really ugly right now to get rid of files we don't need.  I should think
# of a better way to do this. -ahern (March 7, 1997)

PATH="$PATH:./clearcase_bin"
(
   mkman --quiet --norecursive --simple .
   mkman --quiet --norecursive --simple ./config-site
   mkman --quiet --recursive   --simple ./silo
   mkman --quiet --recursive   --simple ./include
   mkman --quiet --recursive   --simple ./bin
   mkman --quiet --recursive   --simple ./lib
   mkman --quiet --recursive   --simple ./clearcase_bin
) | egrep -v 'include/SpiDraw.h|include/spi.h' | sort | uniq

