#!/bin/sh
#######################################################################
#
# silo-release-open - Build and install a tarball on the open network.
#
# Author: Thomas Treadway
# Date: Thu Jun 15 12:48:17 PDT 2006
#
# Usage: 
#    silo-release-open version
#
# Modifications:
#
#
#
#######################################################################
#
BDTOPDIR="/usr/gapps/silo"
LCTOPDIR="/usr/gapps/silo"
#LCTOPDIR="/nfs/tmp0/$USER"

usage() {
  printf "Usage: %s version [all|hoth|sunspot|berg|gps|thunder|pengra|quad|bgl]" $0
  printf "\n"
  printf "Silo release installing script. Assumes a tarball exist in\n"
  printf "current directory, called silo-$VERSION.tar.gz.\n"
  printf "This script will attempt to:\n"
  printf "  1) copy tarball to B Div's /usr/gapps/silo/test and\n"
  printf "     LC's /usr/gapps/silo/test.\n"
  printf "  2) untar\n"
  printf "  3) start remote scripts on the target machines that\n"
  printf "     perform a configure, make check, followed by a make install\n"
  printf "Log files are stored at $HOME/HOSTNAME.log\n"
}
hoth() {
  ssh -f hoth "(/bin/sh -c \"cd $BDTOPDIR/test; \
    PATH=/usr/local/bin:/bin:/usr/bin:/usr/X11R6/bin:/usr/atria/bin:/usr/lib/jre/bin:/sbin:/usr/sbin:/opt/bin:/usr/local/apps/bin:/usr/security/bin; \
    LD_LIBRARY_PATH=/usr/lib:/lib; \
    export PATH LD_LIBRARY_PATH; \
    rm -rf linux_rhel3_gcc_3.2.3; \
    mkdir linux_rhel3_gcc_3.2.3; \
    cd linux_rhel3_gcc_3.2.3; \
    ../$TOPSRCDIR/configure \
    --prefix=$BDTOPDIR/$VERSION/linux_rhel3_gcc_3.2.3 \
    --without-readline --without-hdf5; \
    make -j 4 check && make install; \
    make prefix=$BDTOPDIR/linux_rhel3_gcc_3.2.3/$VERSION install; \
    make clean; \
    ../$TOPSRCDIR/configure \
    --prefix=$BDTOPDIR/$VERSION/linux_rhel3_gcc_3.2.3 \
    --with-hdf5=/usr/gapps/hdf5/1.6.5/LinuxE3/serial/64/optim/include,/usr/gapps/hdf5/1.6.5/LinuxE3/serial/64/optim/lib; \
    make -j 4 check && make install; \
    make prefix=$BDTOPDIR/linux_rhel3_gcc_3.2.3/$VERSION install; \
    rm -f $BDTOPDIR/$VERSION/linux_rhel3_gcc_3.2.3/lib/Silo.a; \
    rm -f $BDTOPDIR/linux_rhel3_gcc_3.2.3/$VERSION/lib/Silo.a; \
    chmod -R g+w $BDTOPDIR/$VERSION/linux_rhel3_gcc_3.2.3; \
    chmod -R g+w $BDTOPDIR/linux_rhel3_gcc_3.2.3/$VERSION; \
    \")" > hoth.log 2>&1
}
hothpgc() {
  ssh -f hoth "(/bin/sh -c \"cd $BDTOPDIR/test; \
    PATH=/usr/local/bin:/bin:/usr/bin:/usr/X11R6/bin:/usr/atria/bin:/usr/lib/jre/bin:/sbin:/usr/sbin:/opt/bin:/usr/local/apps/bin:/usr/local/pgi/linux86/6.0/bin:/usr/security/bin; \
    LD_LIBRARY_PATH=/usr/lib:/lib:/usr/local/pgi/linux86/6.0/lib; \
    LM_LICENSE_FILE=/usr/local/flexlm/licenses/license.dat:7496@genesse.llnl.gov:7127@corona.llnl.gov; \
    export PATH LD_LIBRARY_PATH LM_LICENSE_FILE; \
    rm -rf linux_rhel3_pgc_6.0; \
    mkdir linux_rhel3_pgc_6.0; \
    cd linux_rhel3_pgc_6.0; \
    ../$TOPSRCDIR/configure \
    CC=pgcc CXX=pgCC FC='pgf77 -g77libs' \
    --prefix=$BDTOPDIR/$VERSION/linux_rhel3_pgc_6.0 \
    --without-readline --without-hdf5; \
    make -j 4 check && make install; \
    make prefix=$BDTOPDIR/linux_rhel3_pgc_6.0/$VERSION install; \
    make clean; \
    ../$TOPSRCDIR/configure \
    CC=pgcc CXX=pgCC FC='pgf77 -g77libs' \
    --prefix=$BDTOPDIR/$VERSION/linux_rhel3_pgc_6.0 \
    --with-hdf5=/usr/gapps/hdf5/1.6.5/LinuxE3/serial/64/optim/include,/usr/gapps/hdf5/1.6.5/LinuxE3/serial/64/optim/lib; \
    make -j 4 check && make install; \
    make prefix=$BDTOPDIR/linux_rhel3_pgc_6.0/$VERSION install; \
    rm -f $BDTOPDIR/$VERSION/linux_rhel3_pgc_6.0/lib/Silo.a; \
    rm -f $BDTOPDIR/linux_rhel3_pgc_6.0/$VERSION/lib/Silo.a; \
    chmod -R g+w $BDTOPDIR/$VERSION/linux_rhel3_pgc_6.0; \
    chmod -R g+w $BDTOPDIR/linux_rhel3_pgc_6.0/$VERSION; \
    \")" > hohtpgc.log 2>&1
}
hothicc() {
  ssh -f hoth "(/bin/sh -c \"cd $BDTOPDIR/test; \
    PATH=/usr/local/bin:/bin:/usr/bin:/usr/X11R6/bin:/usr/atria/bin:/usr/lib/jre/bin:/sbin:/usr/sbin:/opt/bin:/usr/local/apps/bin:/usr/local/pgi/linux86/6.0/bin:/usr/security/bin:/usr/local/intel/compiler90/bin; \
    LD_LIBRARY_PATH=/usr/lib:/lib:/usr/local/intel/compiler90/lib; \
    INTEL_LICENSE_FILE=7127@corona.llnl.gov; \
    LM_LICENSE_FILE=/usr/local/flexlm/licenses/license.dat:7496@genesse.llnl.gov:7127@corona.llnl.gov; \
    export PATH LD_LIBRARY_PATH INTEL_LICENSE_FILE LM_LICENSE_FILE; \
    rm -rf linux_rhel3_icc_9.0; \
    mkdir linux_rhel3_icc_9.0; \
    cd linux_rhel3_icc_9.0; \
    . /usr/local/intel/compiler90/bin/iccvars.sh; \
    ../$TOPSRCDIR/configure \
    CC=icc CXX=icc FC=ifort \
    --prefix=$BDTOPDIR/$VERSION/linux_rhel3_icc_9.0 \
    --without-readline --without-hdf5; \
    make -j 4 check; make install; \
    make prefix=$BDTOPDIR/linux_rhel3_icc_9.0/$VERSION install; \
    make clean; \
    ../$TOPSRCDIR/configure \
    CC=icc CXX=icc FC=ifort \
    --prefix=$BDTOPDIR/$VERSION/linux_rhel3_icc_9.0 \
    --with-hdf5=/usr/gapps/hdf5/1.6.5/LinuxE3/serial/64/optim/include,/usr/gapps/hdf5/1.6.5/LinuxE3/serial/64/optim/lib; \
    make -j 4 check; make install; \
    make prefix=$BDTOPDIR/linux_rhel3_icc_9.0/$VERSION install; \
    rm -f $BDTOPDIR/$VERSION/linux_rhel3_icc_9.0/lib/Silo.a; \
    rm -f $BDTOPDIR/linux_rhel3_icc_9.0/$VERSION/lib/Silo.a; \
    chmod -R g+w $BDTOPDIR/$VERSION/linux_rhel3_icc_9.0; \
    chmod -R g+w $BDTOPDIR/linux_rhel3_icc_9.0/$VERSION; \
    \")" > hohticc.log 2>&1
}
    
sunspot() {
# testsuite fails with bus error on "spec"
# weird truncated PATH via ssh
  ssh -f sunspot "(/bin/sh -c \"cd $BDTOPDIR/test; \
    PATH=/usr/bin:/bin:/usr/local/apps/bin:/usr/local/bin:/usr/ccs/bin:/opt/SUNWspro/bin:/usr/ucb:/etc:/usr/openwin/bin:/usr/dt/bin:/usr/java/bin; \
    LD_LIBRARY_PATH=/usr/local/lib:/usr/lib:/lib; \
    export PATH LD_LIBRARY_PATH; \
    rm -rf sunos_57; \
    mkdir sunos_57; \
    cd sunos_57; \
    ../$TOPSRCDIR/configure \
    --prefix=$BDTOPDIR/$VERSION/sunos_57 \
    --without-readline --without-hdf5; \
    make -j 4 check; make install; \
    make prefix=$BDTOPDIR/sunos_57/$VERSION install; \
    make clean; \
    ../$TOPSRCDIR/configure \
    --prefix=$BDTOPDIR/$VERSION/sunos_57 \
    --with-hdf5=/usr/gapps/hdf5/1.6.5/SunOS/serial/default/optim/include,/usr/gapps/hdf5/1.6.5/SunOS/serial/default/optim/lib; \
    make -j 4 check; make install; \
    make prefix=$BDTOPDIR/sunos_57/$VERSION install; \
    rm -f $BDTOPDIR/$VERSION/sunos_57/lib/Silo.a; \
    chmod -R g+w $BDTOPDIR/$VERSION/sunos_57; \
    rm -f $BDTOPDIR/sunos_57/$VERSION/lib/Silo.a; \
    chmod -R g+w $BDTOPDIR/sunos_57/$VERSION; \
    \")" > sunspot.log 2>&1
}
sunspotcc() {
# weird truncated PATH via ssh
  ssh -f sunspot "(/bin/sh -c \"cd $BDTOPDIR/test; \
    PATH=/usr/bin:/bin:/usr/local/apps/bin:/usr/local/bin:/usr/ccs/bin:/opt/SUNWspro/bin:/usr/ucb:/etc:/usr/openwin/bin:/usr/dt/bin:/usr/java/bin; \
    LD_LIBRARY_PATH=/usr/local/lib:/usr/lib:/lib; \
    export PATH LD_LIBRARY_PATH; \
    rm -rf sunos_57_cc_5.2; \
    mkdir sunos_57_cc_5.2; \
    cd sunos_57_cc_5.2; \
    ../$TOPSRCDIR/configure \
    CC=c89 CXX=CC FC=f77 \
    --prefix=$BDTOPDIR/$VERSION/sunos_57_cc_5.2 \
    --without-readline --without-hdf5; \
    make -j 4 check && make install; \
    make prefix=$BDTOPDIR/sunos_57_cc_5.2/$VERSION install; \
    make clean; \
    ../$TOPSRCDIR/configure \
    CC=c89 CXX=CC FC=f77 \
    LDFLAGS=-L/usr/local/lib \
    --prefix=$BDTOPDIR/$VERSION/sunos_57_cc_5.2 \
    --with-hdf5=/usr/gapps/hdf5/1.6.5/SunOS/serial/default/optim/include,/usr/gapps/hdf5/1.6.5/SunOS/serial/default/optim/lib; \
    make -j 4 check && make install; \
    make prefix=$BDTOPDIR/sunos_57_cc_5.2/$VERSION install; \
    rm -f $BDTOPDIR/$VERSION/sunos_57_cc_5.2/lib/Silo.a; \
    chmod -R g+w $BDTOPDIR/$VERSION/sunos_57_cc_5.2; \
    rm -f $BDTOPDIR/sunos_57_cc_5.2/$VERSION/lib/Silo.a; \
    chmod -R g+w $BDTOPDIR/sunos_57_cc_5.2/$VERSION; \
    \")" > sunspotcc.log 2>&1
}

berg() {
# not using gcc
# use gmake for parallel seems to hang
# 32-bit and 64-bit compiles
  berg32
  berg64
}
berg32() {
  ssh -f newberg "(/bin/sh -c \"cd $LCTOPDIR/test; \
    PATH=/usr/local/bin:/usr/bin:/usr/sbin:/usr/ucb:/usr/local/gnu/bin:/usr/local/scripts:/usr/apps/bin:/usr/gapps/bin; \
    OBJECT_MODE=32; \
    export PATH OBJECT_MODE; \
    rm -rf aix_5_ll; \
    mkdir aix_5_ll; \
    cd aix_5_ll; \
    ../$TOPSRCDIR/configure \
    --prefix=$LCTOPDIR/$VERSION/aix_5_ll \
    --without-readline --without-hdf5; \
    make check && make install; \
    make prefix=$BDTOPDIR/aix_5_ll/$VERSION install; \
    make clean; \
    ../$TOPSRCDIR/configure \
    --prefix=$LCTOPDIR/$VERSION/aix_5_ll \
    --with-hdf5=/usr/local/hdf5/hdf5-1.6.5/serial.32/include,/usr/local/hdf5/hdf5-1.6.5/serial.32/lib; \
    make check; make install; \
    make prefix=$BDTOPDIR/aix_5_ll/$VERSION install; \
    rm -f $LCTOPDIR/$VERSION/aix_5_ll/lib/Silo.a; \
    chmod -R g+w $LCTOPDIR/$VERSION/aix_5_ll; \
    rm -f $LCTOPDIR/aix_5_ll/$VERSION/lib/Silo.a; \
    chmod -R g+w $LCTOPDIR/aix_5_ll/$VERSION; \
     \") >newberg32.log 2>&1"
}
berg64() {
  ssh -f newberg "(/bin/sh -c \"cd $LCTOPDIR/test; \
    PATH=/usr/local/bin:/usr/bin:/usr/sbin:/usr/ucb:/usr/local/gnu/bin:/usr/local/scripts:/usr/apps/bin:/usr/gapps/bin; \
    OBJECT_MODE=64; \
    export PATH OBJECT_MODE; \
    rm -rf aix_5_64_fed; \
    mkdir aix_5_64_fed; \
    cd aix_5_64_fed; \
    ../$TOPSRCDIR/configure \
    PYTHON_CPPFLAGS=-I/usr/apps/python64/include/python2.4 \
    --prefix=$LCTOPDIR/$VERSION/aix_5_64_fed \
    --without-readline --without-hdf5; \
    make check && make install; \
    make prefix=$BDTOPDIR/aix_5_64_fed/$VERSION install; \
    make clean; \
    ../$TOPSRCDIR/configure \
    PYTHON_CPPFLAGS=-I/usr/apps/python64/include/python2.4 \
    --prefix=$LCTOPDIR/$VERSION/aix_5_64_fed \
    --with-hdf5=/usr/local/hdf5/hdf5-1.6.5/serial/include,/usr/local/hdf5/hdf5-1.6.5/serial/lib; \
    make check; make install; \
    make prefix=$BDTOPDIR/aix_5_64_fed/$VERSION install; \
    rm -f $LCTOPDIR/$VERSION/aix_5_64_fed/lib/Silo.a; \
    chmod -R g+w $LCTOPDIR/$VERSION/aix_5_64_fed; \
    rm -f $LCTOPDIR/aix_5_64_fed/$VERSION/lib/Silo.a; \
    chmod -R g+w $LCTOPDIR/aix_5_64_fed/$VERSION; \
     \") >newberg64.log 2>&1"
}

gps() {
# the default g++ has bugs 
# problems with g77 floating exception during testsuite of quadf77 & ucdf77
  ssh -f gps "(/bin/sh -c \"cd $LCTOPDIR/test; \
    PATH=/usr/local/bin:/usr/bin:/usr/ccs/bin:/usr/bin/X11:/usr/apps/bin:/usr/gapps/bin; \
    export PATH; \
    rm -rf tru64_5; \
    mkdir tru64_5; \
    cd tru64_5; \
    ../$TOPSRCDIR/configure \
    --prefix=$LCTOPDIR/$VERSION/tru64_5 \
    --without-readline --without-hdf5; \
    gmake -j 4 check ; gmake install; \
    gmake prefix=$BDTOPDIR/tru64_5/$VERSION install; \
    gmake clean; \
    ../$TOPSRCDIR/configure \
    --prefix=$LCTOPDIR/$VERSION/tru64_5 \
    --with-hdf5=/usr/local/hdf5/hdf5-1.6.5/serial/include,/usr/local/hdf5/hdf5-1.6.5/serial/lib; \
    gmake -j 4 check ; gmake install; \
    gmake prefix=$BDTOPDIR/tru64_5/$VERSION install; \
    rm -f $LCTOPDIR/$VERSION/tru64_5/lib/Silo.a; \
    chmod -R g+w $LCTOPDIR/$VERSION/tru64_5; \
    rm -f $LCTOPDIR/tru64_5/$VERSION/lib/Silo.a; \
    chmod -R g+w $LCTOPDIR/tru64_5/$VERSION; \
    \") > gps.log 2>&1"
}
gpscc() {
  ssh -f gps "(/bin/sh -c \"cd $LCTOPDIR/test; \
    PATH=/usr/local/bin:/usr/bin:/usr/ccs/bin:/usr/bin/X11:/usr/apps/bin:/usr/gapps/bin; \
    export PATH; \
    rm -rf tru64_5_cc; \
    mkdir tru64_5_cc; \
    cd tru64_5_cc; \
    ../$TOPSRCDIR/configure \
    CC=c89 CXX=cxx FC=f77 F77=f77 \
    --prefix=$LCTOPDIR/$VERSION/tru64_5_cc \
    --without-readline --without-hdf5; \
    gmake -j 4 check ; gmake install; \
    gmake prefix=$BDTOPDIR/tru64_5_cc/$VERSION install; \
    gmake clean; \
    ../$TOPSRCDIR/configure \
    CC=c89 CXX=cxx FC=f77 F77=f77 \
    --prefix=$LCTOPDIR/$VERSION/tru64_5_cc \
    --with-hdf5=/usr/local/hdf5/hdf5-1.6.5/serial/include,/usr/local/hdf5/hdf5-1.6.5/serial/lib; \
    gmake -j 4 check ; gmake install; \
    gmake prefix=$BDTOPDIR/tru64_5_cc/$VERSION install; \
    rm -f $LCTOPDIR/$VERSION/tru64_5_cc/lib/Silo.a; \
    chmod -R g+w $LCTOPDIR/$VERSION/tru64_5_cc; \
    rm -f $LCTOPDIR/tru64_5_cc/$VERSION/lib/Silo.a; \
    chmod -R g+w $LCTOPDIR/tru64_5_cc/$VERSION; \
    \") > gpscc.log 2>&1"
}
    
pengra() {
  ssh -f pengra "(/bin/sh -c \"cd $LCTOPDIR/test; \
    PATH=usr/local/intel/compiler91/bin:/usr/local/bin:/bin:/usr/bin:/usr/bin/X11:/usr/lib/mpi/bin:/usr/apps/bin:/usr/gapps/bin; \
    export PATH; \
    rm -rf chaos_3_x86_elan3; \
    mkdir chaos_3_x86_elan3; \
    cd chaos_3_x86_elan3; \
    ../$TOPSRCDIR/configure \
    --prefix=$LCTOPDIR/$VERSION/chaos_3_x86_elan3 \
    --without-readline --without-hdf5; \
    make -j 4 check && make install; \
    make prefix=$BDTOPDIR/chaos_3_x86_elan3/$VERSION install; \
    make clean; \
    ../$TOPSRCDIR/configure \
    --prefix=$LCTOPDIR/$VERSION/chaos_3_x86_elan3 \
    --with-hdf5=/usr/local/hdf5/hdf5-1.6.5/serial_gcc/include,/usr/local/hdf5/hdf5-1.6.5/serial_gcc/lib; \
    make -j 4 check && make install; \
    make prefix=$BDTOPDIR/chaos_3_x86_elan3/$VERSION install; \
    rm -f $LCTOPDIR/$VERSION/chaos_3_x86_elan3/lib/Silo.a; \
    chmod -R g+w $LCTOPDIR/$VERSION/chaos_3_x86_elan3; \
    rm -f $LCTOPDIR/chaos_3_x86_elan3/$VERSION/lib/Silo.a; \
    chmod -R g+w $LCTOPDIR/chaos_3_x86_elan3/$VERSION; \
    \") > pengra.log 2>&1"
}
    
thunder() {
  thundergcc
  thundericc
}
thundergcc() {
  ssh -f thunder "(/bin/sh -c \"cd $LCTOPDIR/test; \
    PATH=usr/local/intel/compiler91/bin:/usr/local/bin:/bin:/usr/bin:/usr/bin/X11:/usr/lib/mpi/bin:/usr/apps/bin:/usr/gapps/bin; \
    export PATH; \
    rm -rf chaos_3_ia64_elan4; \
    mkdir chaos_3_ia64_elan4; \
    cd chaos_3_ia64_elan4; \
    ../$TOPSRCDIR/configure \
    --prefix=$LCTOPDIR/$VERSION/chaos_3_ia64_elan4/gcc \
    --without-readline --without-hdf5; \
    make -j 4 check && make install; \
    make prefix=$BDTOPDIR/chaos_3_ia64_elan4/gcc/$VERSION install; \
    make clean; \
    ../$TOPSRCDIR/configure \
    --prefix=$LCTOPDIR/$VERSION/chaos_3_ia64_elan4/gcc \
    --with-hdf5=/usr/local/hdf5/hdf5-1.6.5/serial_gcc/include,/usr/local/hdf5/hdf5-1.6.5/serial/lib; \
    make -j 4 check && make install; \
    make prefix=$BDTOPDIR/chaos_3_ia64_elan4/gcc/$VERSION install; \
    rm -f $LCTOPDIR/$VERSION/chaos_3_ia64_elan4/gcc/lib/Silo.a; \
    chmod -R g+w $LCTOPDIR/$VERSION/chaos_3_ia64_elan4/gcc; \
    rm -f $LCTOPDIR/chaos_3_ia64_elan4/gcc/$VERSION/lib/Silo.a; \
    chmod -R g+w $LCTOPDIR/chaos_3_ia64_elan4/gcc/$VERSION; \
    \") > thundergcc.log 2>&1"
}
thundericc() {
  ssh -f thunder "(/bin/sh -c \"cd $LCTOPDIR/test; \
    PATH=usr/local/intel/compiler91/bin:/usr/local/bin:/bin:/usr/bin:/usr/bin/X11:/usr/lib/mpi/bin:/usr/apps/bin:/usr/gapps/bin; \
    export PATH; \
    rm -rf chaos_3_ia64_elan4_icc; \
    mkdir chaos_3_ia64_elan4_icc; \
    cd chaos_3_ia64_elan4_icc; \
    . /usr/local/intel/compiler91/bin/iccvars.sh; \
    ../$TOPSRCDIR/configure \
    CC=icc CXX=icc FC=ifort \
    --prefix=$LCTOPDIR/$VERSION/chaos_3_ia64_elan4/icc \
    --without-readline --without-hdf5; \
    make -j 4 check && make install; \
    make prefix=$BDTOPDIR/chaos_3_ia64_elan4/icc/$VERSION install; \
    make clean; \
    ../$TOPSRCDIR/configure \
    CC=icc CXX=icc FC=ifort \
    --prefix=$LCTOPDIR/$VERSION/chaos_3_ia64_elan4/icc \
    --with-hdf5=/usr/local/hdf5/hdf5-1.6.5/serial/include,/usr/local/hdf5/hdf5-1.6.5/serial/lib; \
    make -j 4 check && make install; \
    make prefix=$BDTOPDIR/chaos_3_ia64_elan4/icc/$VERSION install; \
    rm -f $LCTOPDIR/$VERSION/chaos_3_ia64_elan4/icc/lib/Silo.a; \
    chmod -R g+w $LCTOPDIR/$VERSION/chaos_3_ia64_elan4/icc; \
    rm -f $LCTOPDIR/chaos_3_ia64_elan4/icc/$VERSION/lib/Silo.a; \
    chmod -R g+w $LCTOPDIR/chaos_3_ia64_elan4/icc/$VERSION; \
    \") > thundericc.log 2>&1"
}

quad() {
# not using gcc
# IRIX make doesn't support VPATH
# 32-bit and 64-bit compiles
  quad32
  quad64
}
quad32() {
  ssh -f quad "(/bin/sh -c \"cd $LCTOPDIR/test; \
    PATH=/usr/sbin:/usr/bsd:/sbin:/usr/bin:/usr/bin/X11:/usr/freeware/bin; \
    PARALLEL=4; \
    export PATH PARALLEL; \
    rm -rf irix_6.5_n32; \
    mkdir irix_6.5_n32; \
    cd irix_6.5_n32; \
    ../$TOPSRCDIR/configure \
    PYTHON_CPPFLAGS=-I/usr/freeware/include/python2.1 \
    --prefix=$LCTOPDIR/$VERSION/irix_6.5_n32 \
    --without-readline --without-hdf5; \
    gmake -j 4 check && gmake install; \
    gmake prefix=$BDTOPDIR/irix_6.5_n32/$VERSION install; \
    gmake clean; \
    ../$TOPSRCDIR/configure \
    PYTHON_CPPFLAGS=-I/usr/freeware/include/python2.1 \
    --prefix=$LCTOPDIR/$VERSION/irix_6.5_n32 \
    --with-hdf5=/usr/gapps/visit/hdf5/1.6.5/irix64_cc_7.41_n32/include,/usr/gapps/visit/hdf5/1.6.5/irix64_cc_7.41_n32/lib; \
    gmake -j 4 check && gmake install; \
    gmake prefix=$BDTOPDIR/irix_6.5_n32/$VERSION install; \
    chmod -R g+w $LCTOPDIR/$VERSION/irix_6.5_n32; \
    chmod -R g+w $LCTOPDIR/irix_6.5_n32/$VERSION; \
     \") >quad32.log 2>&1"
}
quad64() {
  ssh -f quad "(/bin/sh -c \"cd $LCTOPDIR/test; \
    PATH=/usr/sbin:/usr/bsd:/sbin:/usr/bin:/usr/bin/X11:/usr/freeware/bin; \
    PARALLEL=4; \
    export PATH PARALLEL; \
    rm -rf irix_6.5_64; \
    mkdir irix_6.5_64; \
    cd irix_6.5_64; \
    ../$TOPSRCDIR/configure \
    CC='cc -64' CXX='CC -64' FC='f77 -64' \
    LDFLAGS=-64 \
    CFLAGS='-O2 -c99' \
    PYTHON_CPPFLAGS=-I/usr/freeware/include/python2.1 \
    --prefix=$LCTOPDIR/$VERSION/irix_6.5_64 \
    --without-readline --without-hdf5; \
    gmake -j 4 check && gmake install; \
    gmake prefix=$BDTOPDIR/irix_6.5_64/$VERSION install; \
    gmake clean; \
    ../$TOPSRCDIR/configure \
    CC='cc -64' CXX='CC -64' FC='f77 -64' \
    LDFLAGS=-64 \
    CFLAGS='-O2 -c99' \
    PYTHON_CPPFLAGS=-I/usr/freeware/include/python2.1 \
    --prefix=$LCTOPDIR/$VERSION/irix_6.5_64 \
    --with-hdf5=/usr/gapps/visit/hdf5/1.6.5/irix64_cc_7.41_64/include,/usr/gapps/visit/hdf5/1.6.5/irix64_cc_7.41_64/lib; \
    gmake -j 4 check && gmake install; \
    gmake prefix=$BDTOPDIR/irix_6.5_64/$VERSION install; \
    rm -f $LCTOPDIR/$VERSION/irix_6.5_64/lib/Silo.a; \
    chmod -R g+w $LCTOPDIR/$VERSION/irix_6.5_64; \
    rm -f $LCTOPDIR/irix_6.5_64/$VERSION/lib/Silo.a; \
    chmod -R g+w $LCTOPDIR/irix_6.5_64/$VERSION; \
     \") >quad64.log 2>&1"
}
    
ubgltest() {
  ssh -f ubgl "(/bin/sh -c \"cd $LCTOPDIR/test; \
    PATH=/opt/ibmcmp/vacpp/7.0/bin:/opt/ibmcmp/xlf/9.1/bin:/usr/local/bin:/bin:/usr/bin:/usr/bin/X11:/usr/lib/mpi/bin:/usr/apps/bin:/usr/gapps/bin; \
    export PATH; \
    rm -rf sles_9_ppc64; \
    mkdir sles_9_ppc64; \
    cd sles_9_ppc64; \
    ../$TOPSRCDIR/configure \
    CC='xlc' CXX='xlC' FC='fort77' \
    --prefix=$LCTOPDIR/$VERSION/sles_9_ppc64 \
    --without-readline --without-hdf5; \
    make -j 4 CC='blrts_xlc' CXX='blrts_xlC' FC='blrts_fort77' install; \
    chmod -R g+w $LCTOPDIR/$VERSION/sles_9_ppc64; \
    \") > ubgltest.log 2>&1"
}
ubgl() {
  ssh -f ubgl "(/bin/sh -c \"cd $LCTOPDIR/test; \
    PATH=/opt/ibmcmp/vac/7.0/bin:/opt/ibmcmp/xlf/9.1/bin:/usr/local/bin:/bin:/usr/bin:/usr/bin/X11:/usr/lib/mpi/bin:/usr/apps/bin:/usr/gapps/bin; \
    export PATH; \
    rm -rf sles_9_ppc64; \
    mkdir sles_9_ppc64; \
    cd sles_9_ppc64; \
    ../$TOPSRCDIR/configure \
    CC='xlc' \
    --prefix=$LCTOPDIR/$VERSION/sles_9_ppc64 \
    --with-hdf5=/usr/local/tools/hdf5/hdf5-1.6.5/serial_frontend/include,/usr/local/tools/hdf5/hdf5-1.6.5/serial_frontend/lib; \
    make -j 4 install;\
    make prefix=$LCTOPDIR/sles_9_ppc64/$VERSION install;\
    make clean; \
    ../$TOPSRCDIR/configure \
    --prefix=$LCTOPDIR/$VERSION/sles_9_ppc64 \
    --disable-browser --without-readline --without-hdf5; \
    make -j 4 install;\
    make prefix=$LCTOPDIR/sles_9_ppc64/$VERSION install;\
    make clean; \
    ../$TOPSRCDIR/configure \
    --prefix=$LCTOPDIR/$VERSION/sles_9_ppc64 \
    --disable-browser --without-readline \
    --with-hdf5=/usr/local/tools/hdf5/hdf5-1.6.5/serial/include,/usr/local/tools/hdf5/hdf5-1.6.5/serial/lib; \
    make -j 4 install; \
    make prefix=$LCTOPDIR/sles_9_ppc64/$VERSION install; \
    rm -f $LCTOPDIR/$VERSION/sles_9_ppc64/lib/Silo.a; \
    chmod -R g+w $LCTOPDIR/$VERSION/sles_9_ppc64; \
    rm -f $LCTOPDIR/sles_9_ppc64/$VERSION/lib/Silo.a; \
    chmod -R g+w $LCTOPDIR/sles_9_ppc64/$VERSION; \
    \") > ubgl.log 2>&1"
}

if [ $# -lt 1 ] ; then
  usage
  exit 2
fi
VERSION=$1
shift
TARFILE="silo-$VERSION.tar.gz"
TOPSRCDIR="silo-$VERSION"
if [ -e $TARFILE ] ; then
  scp $TARFILE hoth:$BDTOPDIR/test
  scp $TARFILE gps:$LCTOPDIR/test

  ssh hoth "(/bin/sh -c \"cd $BDTOPDIR/test; \
   gzip -dc $TARFILE|tar xf -\")"
  ssh gps "(/bin/sh -c \"cd $LCTOPDIR/test; \
   gzip -dc $TARFILE|tar xf -\")"
fi 

if [ $# -lt 1 ] ; then
  hoth
  sunspot
  berg
  gps
  thunder
  pengra
  quad
  ubgl
else
 while [ "$*" != "" ]
 do
  case $1 in
    all|-a*)
      hoth
      sunspot
      berg
      gps
      thunder
      pengra
      quad
      ubgl
      shift;;
    hothpgc|-hothpgc)
      hothpgc
      shift;;
    hothicc|-hothicc)
      hothicc
      shift;;
    hoth|-ho*)
      hoth
      shift;;
    sun*cc|-sun*cc)
      sunspotcc
      shift;;
    sun*|-sun*)
      sunspot
      shift;;
    berg32|-be*32|new*32|-new*32)
      berg32
      shift;;
    berg64|-be*64|new*64|-new*64)
      berg64
      shift;;
    berg|-be*|new*|-new*)
      berg
      shift;;
    gpscc|-gpscc)
      gpscc
      shift;;
    gps|-gps)
      gps
      shift;;
    thun*icc|-th*icc)
      thundericc
      shift;;
    thun*gcc|-th*gcc)
      thundergcc
      shift;;
    thun*|-th*)
      thunder
      shift;;
    pen*|-pe*)
      pengra
      shift;;
    quad32|-quad32)
      quad32
      shift;;
    quad64|-quad64)
      quad64
      shift;;
    quad|-quad)
      quad
      shift;;
    ubgltest|-ubgltest)
      ubgltest
      shift;;
    ubgl|-ubgl)
      ubgl
      shift;;
    sh*|-sh*)
      shar
      shift;;
    *)
      shift;;
  esac
 done
fi
