#!/bin/sh
#######################################################################
#
# silo-release-closed - Build and install a tarball on the closed network.
#
# Author: Thomas Treadway
# Date: Wed Sep 13 16:31:51 PDT 2006
#
# Usage: 
#    silo-release-closed version
#
# Modifications:
#    Thomas R. Treadway, Fri Nov  2 16:17:59 PDT 2007
#    Tunning for release 4.6
#    Default hostnode (assumed to be Linux) will be "localhost"
#
#######################################################################
#
BDTOPDIR="/usr/gapps/silo"
LCTOPDIR="/usr/gapps/silo"
#LCTOPDIR="/nfs/tmp0/$USER"
SZIPRELEASE=2.1
HDF5RELEASE=1.6.6
QTRELEASE=3.3.8
lcun=$USER
bdun=$USER
bdhost="vader"
BININSTALLS="browser silex silock silodiff"

usage() {
  printf "Usage: %s version [-lc-username <username>] [-bdiv-username <username>] [-bdiv-host <hostname>] [all|localhost|sunset|purple|uv|gauss|lilac|rhea|bgl]" $0
  printf "\n"
  printf "Silo release installing script. Assumes a tarball exist in\n"
  printf "current directory, called silo-$VERSION.tar.gz.\n"
  printf "This script will attempt to:\n"
  printf "  1) copy tarball to B Div's /usr/gapps/silo/$VERSION and\n"
  printf "     LC's /usr/gapps/silo/$VERSION.\n"
  printf "  2) untar in /usr/gapps/silo/$VERSION/test.\n"
  printf "  3) start remote scripts on the target machines that\n"
  printf "     perform a configure, make check, followed by a make install\n"
  printf "     into directories /usr/gapps/silo/$VERSION/$ARCH.\n"
  printf "Log files are stored at ./HOSTNAME.log\n"
  printf "You may want to run this script from the LC network.\n"
}
localhost() {
  localhostgcc
  localhostpgc
  localhosticc
}
localhostgcc() {
  ssh ${bdun}@${bdhost} "/bin/sh" << EOF > localhostgcc.log 2>&1 &
    cd $BDTOPDIR/$VERSION/test
    umask 002
    PATH=/usr/local/bin:/bin:/usr/bin:/usr/X11R6/bin:/usr/atria/bin:/usr/lib/jre/bin:/sbin:/usr/sbin:/opt/bin:/usr/local/apps/bin:/usr/security/bin
    LD_LIBRARY_PATH=/usr/lib:/lib
    export PATH LD_LIBRARY_PATH
    rm -rf linux_rhel3-gcc-3.2.3
    mkdir linux_rhel3-gcc-3.2.3
    cd linux_rhel3-gcc-3.2.3
    ../$TOPSRCDIR/configure \
    CFLAGS=-fPIC CXXFLAGS=-fPIC \
    CC=gcc CXX=g++ FC=f77 \
    FFLAGS=-Wno-globals F77FLAGS=-Wno-globals FCFLAGS=-Wno-globals \
    --prefix=$BDTOPDIR/$VERSION/linux_rhel3-gcc-3.2.3 \
    --disable-browser --disable-silex --without-hdf5 --without-szlib
    make -j 4
    make install
    make distclean
    ../$TOPSRCDIR/configure \
    CFLAGS=-fPIC CXXFLAGS=-fPIC \
    CC=gcc CXX=g++ FC=f77 \
    FFLAGS=-Wno-globals F77FLAGS=-Wno-globals FCFLAGS=-Wno-globals \
    --prefix=$BDTOPDIR/$VERSION/linux_rhel3-gcc-3.2.3
    make -j 4 check
    make install
    make bindir=/misc/gapps/Linux/bin install-exec
    chmod -R g+w $BDTOPDIR/$VERSION/linux_rhel3-gcc-3.2.3
    for FILE in $BININSTALLS
    do chmod -R g+w /misc/gapps/Linux/bin/$FILE
    done
    make distclean
EOF
}
localhostpgc() {
  ssh ${bdun}@${bdhost} "/bin/sh" << EOF > localhostpgc.log 2>&1 &
    cd $BDTOPDIR/$VERSION/test
    umask 002
    PATH=/usr/local/bin:/bin:/usr/bin:/usr/X11R6/bin:/usr/atria/bin:/usr/lib/jre/bin:/sbin:/usr/sbin:/opt/bin:/usr/local/apps/bin:/usr/local/pgi/linux86/bin:/usr/security/bin
    LD_LIBRARY_PATH=/usr/lib:/lib:/usr/local/pgi/linux86/lib
    LM_LICENSE_FILE=/usr/local/flexlm/licenses/license.dat:7128@helios.llnl.gov:7127@helios.llnl.gov
    export PATH LD_LIBRARY_PATH LM_LICENSE_FILE
    rm -rf linux_rhel3-pgc-4.0
    mkdir linux_rhel3-pgc-4.0
    cd linux_rhel3-pgc-4.0
    ../$TOPSRCDIR/configure \
    CC=pgcc CXX=pgCC FC='pgf77 -g77libs' LDFLAGS=-lstdc++ \
    --prefix=$BDTOPDIR/$VERSION/linux_rhel3-pgc-4.0 \
    --disable-browser --disable-silex --without-hdf5 --without-szlib
    make -j 4
    make install
    make distclean
    ../$TOPSRCDIR/configure \
    CC=pgcc CXX=pgCC FC='pgf77 -g77libs' LDFLAGS=-lstdc++ \
    --prefix=$BDTOPDIR/$VERSION/linux_rhel3-pgc-4.0 \
    --disable-silex
    make -j 4 check
    make install
    ln -s $BDTOPDIR/$VERSION/linux_rhel3-gcc-3.2.3/bin/silex \
       $BDTOPDIR/$VERSION/linux_rhel3-pgc-4.0/bin/silex
    chmod -R g+w $BDTOPDIR/$VERSION/linux_rhel3-pgc-4.0
    make distclean
EOF
}
localhosticc() {
  ssh ${bdun}@${bdhost} "/bin/sh" << EOF > localhosticc.log 2>&1 &
    cd $BDTOPDIR/$VERSION/test
    umask 002
    PATH=/usr/local/bin:/bin:/usr/bin:/usr/X11R6/bin:/usr/atria/bin:/usr/lib/jre/bin:/sbin:/usr/sbin:/opt/bin:/usr/local/apps/bin:/usr/local/pgi/linux86/6.0/bin:/usr/security/bin:/usr/local/intel/compiler81/bin
    LD_LIBRARY_PATH=/usr/lib:/lib:/usr/local/intel/compiler81/lib
    INTEL_LICENSE_FILE=7127@helios.llnl.gov
    LM_LICENSE_FILE=/usr/local/flexlm/licenses/license.dat:7128@helios.llnl.gov:7127@helios.llnl.gov
    export PATH LD_LIBRARY_PATH INTEL_LICENSE_FILE LM_LICENSE_FILE
    rm -rf linux_rhel3-icc-8.1
    mkdir linux_rhel3-icc-8.1
    cd linux_rhel3-icc-8.1
    . /usr/local/intel/compiler81/bin/iccvars.sh
    ../$TOPSRCDIR/configure \
    CC=icc CXX=icc FC=ifort LDFLAGS=-lstdc++ \
    --prefix=$BDTOPDIR/$VERSION/linux_rhel3-icc-8.1 \
    --disable-browser --disable-silex --without-hdf5 --without-szlib
    make -j 4
    make install
    make distclean
    ../$TOPSRCDIR/configure \
    CC=icc CXX=icc FC=ifort LDFLAGS=-lstdc++ \
    --prefix=$BDTOPDIR/$VERSION/linux_rhel3-icc-8.1 \
    --disable-silex \
    --with-szlib=/usr/gapps/silo/szip/$SZIPRELEASE/i386-pc-linux-gcc-3.2.3 \
    --with-hdf5=/usr/gapps/silo/hdf5/$HDF5RELEASE/i386-pc-linux-gcc-3.2.3/include,/usr/gapps/silo/hdf5/$HDF5RELEASE/i386-pc-linux-gcc-3.2.3/lib
    make -j 4 check
    make install
    ln -s $BDTOPDIR/$VERSION/linux_rhel3-gcc-3.2.3/bin/silex \
       $BDTOPDIR/$VERSION/linux_rhel3-icc-8.1/bin/silex
    chmod -R g+w $BDTOPDIR/$VERSION/linux_rhel3-icc-8.1
    make distclean
EOF
}
    
sunset() {
  sunsetgcc
  sunsetcc
}
sunsetgcc() {
  ssh sunset "/bin/sh" << EOF > sunset.log 2>&1 &
    cd $BDTOPDIR/$VERSION/test
    umask 002
# testsuite fails with bus error on "spec"
# weird truncated PATH via ssh
    PATH=/usr/bin:/bin:/usr/local/apps/bin:/usr/local/bin:/usr/ccs/bin:/opt/SUNWspro/bin:/usr/ucb:/etc:/usr/openwin/bin:/usr/dt/bin:/usr/java/bin
    LD_LIBRARY_PATH=/usr/local/lib:/usr/lib:/lib
    export PATH LD_LIBRARY_PATH
    rm -rf sunos_57
    mkdir sunos_57
    cd sunos_57
    ../$TOPSRCDIR/configure \
    FC=g77 F77=g77 \
    FFLAGS=-Wno-globals F77FLAGS=-Wno-globals FCFLAGS=-Wno-globals \
    --prefix=$BDTOPDIR/$VERSION/sunos_57 \
    --disable-browser --disable-silex --without-hdf5 --without-szlib
    make -j 4
    make install
    make distclean
    ../$TOPSRCDIR/configure \
    FC=g77 F77=g77 \
    FFLAGS=-Wno-globals F77FLAGS=-Wno-globals FCFLAGS=-Wno-globals \
    --prefix=$BDTOPDIR/$VERSION/sunos_57
    make -j 4 check
    make install
    make bindir=/misc/gapps/SunOS/bin install-exec
    chmod -R g+w $BDTOPDIR/$VERSION/sunos_57
    for FILE in $BININSTALLS
    do chmod -R g+w /misc/gapps/SunOS/bin/$FILE
    done
    make distclean
EOF
}
sunsetcc() {
  ssh sunset "/bin/sh" << EOF > sunsetcc.log 2>&1 &
    cd $BDTOPDIR/$VERSION/test
    umask 002
# weird truncated PATH via ssh
    PATH=/usr/bin:/bin:/usr/local/apps/bin:/usr/local/bin:/usr/ccs/bin:/opt/SUNWspro/bin:/usr/ucb:/etc:/usr/openwin/bin:/usr/dt/bin:/usr/java/bin
    LD_LIBRARY_PATH=/usr/local/lib:/usr/lib:/lib
    export PATH LD_LIBRARY_PATH
    rm -rf sunos_57-cc-5.2
    mkdir sunos_57-cc-5.2
    cd sunos_57-cc-5.2
    ../$TOPSRCDIR/configure \
    CC=c89 CXX=CC FC=f77 \
    --prefix=$BDTOPDIR/$VERSION/sunos_57-cc-5.2 \
    --disable-browser --disable-silex --without-hdf5 --without-szlib
    gmake -j 4
    gmake install
    gmake distclean
    ../$TOPSRCDIR/configure \
    CC=c89 CXX=CC FC=f77 \
    LDFLAGS=-L/usr/local/lib \
    --prefix=$BDTOPDIR/$VERSION/sunos_57-cc-5.2 \
    --disable-silex --without-readline \
    --with-szlib=/usr/gapps/silo/szip/$SZIPRELEASE/sparc-sun-solaris-cc-5.2 \
    --with-hdf5=/usr/gapps/silo/hdf5/$HDF5RELEASE/sparc-sun-solaris-cc-5.2/include,/usr/gapps/silo/hdf5/$HDF5RELEASE/sparc-sun-solaris-cc-5.2/lib
    gmake -j 4 check
    gmake install
    ln -s $BDTOPDIR/$VERSION/sunos_57/bin/silex \
       $BDTOPDIR/$VERSION/sunos_57-cc-5.2/bin/silex
    chmod -R g+w $BDTOPDIR/$VERSION/sunos_57-cc-5.2
    make distclean
EOF
}

purple() {
# not using gcc
# use gmake for parallel seems to hang
# 32-bit and 64-bit compiles
  purple64
  purple32
#  purplegcc - no equiv. HDF5 builds
}
purple32() {
  ssh ${lcun}@purple "/bin/sh" << EOF > purple32.log 2>&1 &
    cd $LCTOPDIR/$VERSION/test
    umask 002
    PATH=/usr/local/bin:/usr/bin:/usr/sbin:/usr/ucb:/usr/local/gnu/bin:/usr/local/scripts:/usr/apps/bin:/usr/gapps/bin
    OBJECT_MODE=32
    export PATH OBJECT_MODE
    rm -rf aix_5_ll
    mkdir aix_5_ll
    cd aix_5_ll
    ../$TOPSRCDIR/configure \
    --prefix=$LCTOPDIR/$VERSION/aix_5_ll \
    --disable-browser --disable-silex --without-hdf5 --without-szlib
    gmake
    gmake install
    gmake distclean
    ../$TOPSRCDIR/configure \
    --prefix=$LCTOPDIR/$VERSION/aix_5_ll --disable-silex
    gmake check
    gmake install
    ln -s $LCTOPDIR/$VERSION/aix_5_64_fed/bin/silex \
       $LCTOPDIR/$VERSION/aix_5_ll/bin/silex
    chmod -R g+w $LCTOPDIR/$VERSION/aix_5_ll
    make distclean
EOF
}
purple64() {
  ssh ${lcun}@purple "/bin/sh" << EOF > purple64.log 2>&1 &
    cd $LCTOPDIR/$VERSION/test
    umask 002
    PATH=/usr/local/bin:/usr/bin:/usr/sbin:/usr/ucb:/usr/local/gnu/bin:/usr/local/scripts:/usr/apps/bin:/usr/gapps/bin
    OBJECT_MODE=64
    export PATH OBJECT_MODE
    rm -rf aix_5_64_fed
    mkdir aix_5_64_fed
    cd aix_5_64_fed
    ../$TOPSRCDIR/configure \
    PYTHON_CPPFLAGS=-I/usr/apps/python64/include/python2.4 \
    --prefix=$LCTOPDIR/$VERSION/aix_5_64_fed \
    --disable-browser --disable-silex --without-hdf5 --without-szlib
    gmake
    gmake install
    gmake distclean
    ../$TOPSRCDIR/configure \
    --prefix=$LCTOPDIR/$VERSION/aix_5_64_fed
    gmake check
    gmake install
    gmake bindir=/usr/gapps/bin/aix_5_64 install-exec
    gmake bindir=/usr/gapps/bin/aix_5_64_fed install-exec
    gmake bindir=/usr/gapps/bin/aix_5_ll install-exec
    chmod -R g+w $LCTOPDIR/$VERSION/aix_5_64_fed
    for FILE in $BININSTALLS
    do chmod -R g+w /usr/gapps/bin/aix_5_64/$FILE
       chmod -R g+w /usr/gapps/bin/aix_5_64_fed/$FILE
       chmod -R g+w /usr/gapps/bin/aix_5_ll/$FILE
    done
    make distclean
EOF
}

purplegcc() {
# use gmake for parallel seems to hang
# 32-bit and 64-bit compiles
  purplegcc32
  purplegcc64
}
purplegcc32() {
  ssh ${lcun}@purple "/bin/sh" << EOF > purplegcc32.log 2>&1 &
    cd $LCTOPDIR/$VERSION/test
    umask 002
    PATH=/usr/local/bin:/usr/bin:/usr/sbin:/usr/ucb:/usr/local/gnu/bin:/usr/local/scripts:/usr/apps/bin:/usr/gapps/bin
    OBJECT_MODE=32
    export PATH OBJECT_MODE
    rm -rf aix_5_ll-gcc
    mkdir aix_5_ll-gcc
    cd aix_5_ll-gcc
    ../$TOPSRCDIR/configure \
    CC=gcc CXX=g++ FC=g77 F77=g77 \
    FFLAGS=-Wno-globals F77FLAGS=-Wno-globals FCFLAGS=-Wno-globals \
    --prefix=$LCTOPDIR/$VERSION/aix_5_ll-gcc \
    --disable-browser --disable-silex --without-hdf5 --without-szlib
    gmake
    gmake install
    gmake distclean
    ../$TOPSRCDIR/configure \
    CC=gcc CXX=g++ FC=g77 F77=g77 \
    FFLAGS=-Wno-globals F77FLAGS=-Wno-globals FCFLAGS=-Wno-globals \
    --prefix=$LCTOPDIR/$VERSION/aix_5_ll-gcc \
    --with-szlib=/usr/gapps/silo/szip/$SZIPRELEASE/aix_5_ll-gcc \
    --with-hdf5=/usr/gapps/silo/hdf5/$HDF5RELEASE/aix_5_ll-gcc/include,/usr/gapps/silo/hdf5/$HDF5RELEASE/aix_5_ll-gcc/lib
    gmake check
    gmake install
    ln -s $LCTOPDIR/$VERSION/aix_5_64_fed/bin/silex \
       $LCTOPDIR/$VERSION/aix_5_ll-gcc/bin/silex
    chmod -R g+w $LCTOPDIR/$VERSION/aix_5_ll-gcc
    make distclean
EOF
}   
purplegcc64() {
  ssh ${lcun}@purple "/bin/sh" << EOF > purplegcc64.log 2>&1 &
    cd $LCTOPDIR/$VERSION/test
    umask 002
    PATH=/usr/local/bin:/usr/bin:/usr/sbin:/usr/ucb:/usr/local/gnu/bin:/usr/local/scripts:/usr/apps/bin:/usr/gapps/bin
    OBJECT_MODE=64
    export PATH OBJECT_MODE
    rm -rf aix_5_64_fed-gcc
    mkdir aix_5_64_fed-gcc
    cd aix_5_64_fed-gcc
    ../$TOPSRCDIR/configure \
    CC=gcc CXX=g++ FC=g77 F77=g77 \
    FFLAGS=-Wno-globals F77FLAGS=-Wno-globals FCFLAGS=-Wno-globals \
    PYTHON_CPPFLAGS=-I/usr/apps/python64/include/python2.4 \
    --prefix=$LCTOPDIR/$VERSION/aix_5_64_fed-gcc \
    --disable-browser --disable-silex --without-hdf5 --without-szlib
    gmake
    gmake install
    gmake distclean
    ../$TOPSRCDIR/configure \
    CC=gcc CXX=g++ FC=g77 F77=g77 \
    FFLAGS=-Wno-globals F77FLAGS=-Wno-globals FCFLAGS=-Wno-globals \
    PYTHON_CPPFLAGS=-I/usr/apps/python64/include/python2.4 \
    --prefix=$LCTOPDIR/$VERSION/aix_5_64_fed-gcc \
    --with-szlib=/usr/gapps/silo/szip/$SZIPRELEASE/aix_5_64_fed-gcc \
    --with-hdf5=/usr/gapps/silo/hdf5/$HDF5RELEASE/aix_5_64_fed-gcc/include,/usr/gapps/silo/hdf5/$HDF5RELEASE/aix_5_64_fed-gcc/lib
    gmake check
    gmake install
    ln -s $LCTOPDIR/$VERSION/aix_5_64_fed/bin/silex \
       $LCTOPDIR/$VERSION/aix_5_64_fed-gcc/bin/silex
    chmod -R g+w $LCTOPDIR/$VERSION/aix_5_64_fed-gcc
    make distclean
EOF
}

uv() { 
# not using gcc
# use gmake for parallel seems to hang# 32-bit and 64-bit compiles
# These are commented out as purple will serve this role
#  uv64
#  uv32
test
}   
uv32() {
  ssh ${lcun}@uv "/bin/sh" << EOF > uv32.log 2>&1 &
    cd $LCTOPDIR/$VERSION/test
    umask 002
    PATH=/usr/local/bin:/usr/bin:/usr/sbin:/usr/ucb:/usr/local/gnu/bin:/usr/local/scripts:/usr/apps/bin:/usr/gapps/bin
    OBJECT_MODE=32
    export PATH OBJECT_MODE
    rm -rf aix_5_ll
    mkdir aix_5_ll
    cd aix_5_ll
    ../$TOPSRCDIR/configure \
    --prefix=$LCTOPDIR/$VERSION/aix_5_ll \
    --disable-browser --disable-silex --without-hdf5 --without-szlib
    make
    make install
    make distclean
    OBJECT_MODE=32
    export PATH OBJECT_MODE
    ../$TOPSRCDIR/configure \
    --prefix=$LCTOPDIR/$VERSION/aix_5_ll --disable-silex \
    --with-szlib=/usr/gapps/silo/szip/$SZIPRELEASE/aix_5_ll \
    --with-hdf5=/usr/gapps/silo/hdf5/$HDF5RELEASE/aix_5_ll/include,/usr/gapps/silo/hdf5/$HDF5RELEASE/aix_5_ll/lib
    make check
    make install
    ln -s $LCTOPDIR/$VERSION/aix_5_64_fed/bin/silex \
       $LCTOPDIR/$VERSION/aix_5_ll/bin/silex
    chmod -R g+w $LCTOPDIR/$VERSION/aix_5_ll
    make distclean
EOF
}
uv64() {
  ssh ${lcun}@uv "/bin/sh" << EOF > uv64.log 2>&1 &
    cd $LCTOPDIR/$VERSION/test
    umask 002
    PATH=/usr/local/bin:/usr/bin:/usr/sbin:/usr/ucb:/usr/local/gnu/bin:/usr/local/scripts:/usr/apps/bin:/usr/gapps/bin
    OBJECT_MODE=64
    export PATH OBJECT_MODE
    rm -rf aix_5_64_fed
    mkdir aix_5_64_fed
    cd aix_5_64_fed
    ../$TOPSRCDIR/configure \
    PYTHON_CPPFLAGS=-I/usr/apps/python64/include/python2.4 \
    --prefix=$LCTOPDIR/$VERSION/aix_5_64_fed \
    --disable-browser --disable-silex --without-hdf5 --without-szlib
    make
    make install
    make distclean
    ../$TOPSRCDIR/configure \
    --prefix=$LCTOPDIR/$VERSION/aix_5_64_fed
    make check
    make install
    chmod -R g+w $LCTOPDIR/$VERSION/aix_5_64_fed
    make distclean
EOF
}

uvgcc() {
# use gmake for parallel seems to hang
# 32-bit and 64-bit compiles
  uvgcc64
  uvgcc32
}
uvgcc32() {
  ssh ${lcun}@uv "/bin/sh" << EOF > uvgcc32.log 2>&1 &
    cd $LCTOPDIR/$VERSION/test
    umask 002
    PATH=/usr/local/bin:/usr/bin:/usr/sbin:/usr/ucb:/usr/local/gnu/bin:/usr/local/scripts:/usr/apps/bin:/usr/gapps/bin
    OBJECT_MODE=32
    export PATH OBJECT_MODE
    rm -rf aix_5_ll-gcc
    mkdir aix_5_ll-gcc
    cd aix_5_ll-gcc
    ../$TOPSRCDIR/configure \
    CC=gcc CXX=g++ FC=g77 F77=g77 \
    FFLAGS=-Wno-globals F77FLAGS=-Wno-globals FCFLAGS=-Wno-globals \
    --prefix=$LCTOPDIR/$VERSION/aix_5_ll-gcc \
    --disable-browser --disable-silex --without-hdf5 --without-szlib
    make
    make install
    make distclean
    ../$TOPSRCDIR/configure \
    CC=gcc CXX=g++ FC=g77 F77=g77 \
    --prefix=$LCTOPDIR/$VERSION/aix_5_ll-gcc --disable-silex \
    --with-szlib=/usr/gapps/silo/szip/$SZIPRELEASE/aix_5_ll-gcc \
    --with-hdf5=/usr/gapps/silo/hdf5/$HDF5RELEASE/aix_5_ll-gcc/include,/usr/gapps/silo/hdf5/$HDF5RELEASE/aix_5_ll-gcc/lib
    make check
    make install
    ln -s $LCTOPDIR/$VERSION/aix_5_64_fed-gcc/bin/silex \
       $LCTOPDIR/$VERSION/aix_5_ll-gcc/bin/silex
    chmod -R g+w $LCTOPDIR/$VERSION/aix_5_ll-gcc
    make distclean
EOF
}
uvgcc64() {
  ssh ${lcun}@uv "/bin/sh" << EOF > uvgcc64.log 2>&1 &
    cd $LCTOPDIR/$VERSION/test
    umask 002
    PATH=/usr/local/bin:/usr/bin:/usr/sbin:/usr/ucb:/usr/local/gnu/bin:/usr/local/scripts:/usr/apps/bin:/usr/gapps/bin
    OBJECT_MODE=64
    export PATH OBJECT_MODE
    rm -rf aix_5_64_fed-gcc
    mkdir aix_5_64_fed-gcc
    cd aix_5_64_fed-gcc
    ../$TOPSRCDIR/configure \
    CC=gcc CXX=g++ FC=g77 F77=g77 \
    FFLAGS=-Wno-globals F77FLAGS=-Wno-globals FCFLAGS=-Wno-globals \
    PYTHON_CPPFLAGS=-I/usr/apps/python64/include/python2.4 \
    --prefix=$LCTOPDIR/$VERSION/aix_5_64_fed-gcc \
    --disable-browser --disable-silex --without-hdf5 --without-szlib
    make
    make install
    make distclean
    ../$TOPSRCDIR/configure \
    --prefix=$LCTOPDIR/$VERSION/aix_5_64_fed-gcc --enable-silex \
    --with-Qt-dir=/usr/gapps/silo/qt/$QTRELEASE/aix_5_64_fed \
    --with-szlib=/usr/gapps/silo/szip/$SZIPRELEASE/aix_5_64_fed-gcc \
    --with-hdf5=/usr/gapps/silo/hdf5/$HDF5RELEASE/aix_5_64_fed-gcc/include,/usr/gapps/silo/hdf5/$HDF5RELEASE/aix_5_64_fed-gcc/lib
    make
    make install
    chmod -R g+w $LCTOPDIR/$VERSION/aix_5_64_fed-gcc
    make distclean
EOF
}


sc() {
# the default g++ has bugs 
  ssh ${lcun}@sc "/bin/sh" << EOF > sc.log 2>&1 &
    cd $LCTOPDIR/$VERSION/test
    umask 002
    PATH=/usr/local/bin:/usr/bin:/usr/ccs/bin:/usr/bin/X11:/usr/apps/bin:/usr/gapps/bin
    export PATH
    rm -rf tru64_5
    mkdir tru64_5
    cd tru64_5
    ../$TOPSRCDIR/configure \
    CC=gcc-3.4.1 CXX=g++-3.4.1 FC=g77-3.4.1 F77=g77-3.4.1 \
    FFLAGS=-Wno-globals F77FLAGS=-Wno-globals FCFLAGS=-Wno-globals \
    --prefix=$LCTOPDIR/$VERSION/tru64_5 \
    --without-readline --without-hdf5
    gmake -j 4
    gmake install
    gmake distclean
    ../$TOPSRCDIR/configure \
    --prefix=$LCTOPDIR/$VERSION/tru64_5 \
    --without-readline \
    --with-hdf5=/usr/local/hdf5/hdf5-1.6.5/serial/include,/usr/local/hdf5/hdf5-1.6.5/serial/lib
    gmake -j 4 check 
    gmake install
    chmod -R g+w $LCTOPDIR/$VERSION/tru64_5
    make distclean
EOF
}
sccc() {
  ssh ${lcun}@sc "/bin/sh" << EOF > sccc.log 2>&1 &
    cd $LCTOPDIR/$VERSION/test
    umask 002
    PATH=/usr/local/bin:/usr/bin:/usr/ccs/bin:/usr/bin/X11:/usr/apps/bin:/usr/gapps/bin
    export PATH
    rm -rf tru64_5_cc
    mkdir tru64_5_cc
    cd tru64_5_cc
    ../$TOPSRCDIR/configure \
    CC=c89 CXX=cxx FC=f77 F77=f77 \
    --prefix=$LCTOPDIR/$VERSION/tru64_5_cc \
    --without-readline --without-hdf5
    gmake -j 4
    gmake install
    gmake distclean
    ../$TOPSRCDIR/configure \
    --prefix=$LCTOPDIR/$VERSION/tru64_5_cc \
    --without-readline \
    --with-hdf5=/usr/local/hdf5/hdf5-1.6.5/serial/include,/usr/local/hdf5/hdf5-1.6.5/serial/lib
    gmake -j 4 check
    gmake install
    chmod -R g+w $LCTOPDIR/$VERSION/tru64_5_cc
    make distclean
EOF
}
    
lilac() {
  ssh ${lcun}@lilac "/bin/sh" << EOF > lilac.log 2>&1 &
    cd $LCTOPDIR/$VERSION/test
    umask 002
    PATH=usr/local/intel/compiler91/bin:/usr/local/bin:/bin:/usr/bin:/usr/bin/X11:/usr/lib/mpi/bin:/usr/apps/bin:/usr/gapps/bin
    export PATH
    rm -rf chaos_3_x86_elan3
    mkdir chaos_3_x86_elan3
    cd chaos_3_x86_elan3
    ../$TOPSRCDIR/configure \
    CFLAGS=-fPIC CXXFLAGS=-fPIC \
    --prefix=$LCTOPDIR/$VERSION/chaos_3_x86_elan3 \
    --disable-browser --disable-silex --without-hdf5 --without-szlib
    make -j 4
    make install
    make distclean
    ../$TOPSRCDIR/configure \
    CFLAGS=-fPIC CXXFLAGS=-fPIC \
    --prefix=$LCTOPDIR/$VERSION/chaos_3_x86_elan3
    make -j 4 check
    make install
    chmod -R g+w $LCTOPDIR/$VERSION/chaos_3_x86_elan3
    make distclean
EOF
}
    
gauss() {
  gaussgcc
  gaussicc
}
gaussgcc() {
  ssh ${lcun}@gauss "/bin/sh" << EOF > gaussgcc.log 2>&1 &
    cd $LCTOPDIR/$VERSION/test
    umask 002
    PATH=usr/local/intel/compiler91/bin:/usr/local/bin:/bin:/usr/bin:/usr/bin/X11:/usr/lib/mpi/bin:/usr/apps/bin:/usr/gapps/bin
    export PATH
    rm -rf chaos_3_x86_64_ib
    mkdir chaos_3_x86_64_ib
    cd chaos_3_x86_64_ib
    ../$TOPSRCDIR/configure \
    CFLAGS=-fPIC CXXFLAGS=-fPIC \
    CC=gcc CXX=g++ \
    FC=g77 F77=g77 \
    FFLAGS=-Wno-globals F77FLAGS=-Wno-globals FCFLAGS=-Wno-globals \
    --prefix=$LCTOPDIR/$VERSION/chaos_3_x86_64_ib-gcc \
    --disable-browser --disable-silex --without-hdf5 --without-szlib
    make -j 4
    make install
    make distclean
    ../$TOPSRCDIR/configure \
    CFLAGS=-fPIC CXXFLAGS=-fPIC \
    CC=gcc CXX=g++ \
    FC=g77 F77=g77 \
    FFLAGS=-Wno-globals F77FLAGS=-Wno-globals FCFLAGS=-Wno-globals \
    --prefix=$LCTOPDIR/$VERSION/chaos_3_x86_64_ib-gcc
    make -j 4 check
    make install
    chmod -R g+w $LCTOPDIR/$VERSION/chaos_3_x86_64_ib-gcc
    make distclean
EOF
}
gaussicc() {
  ssh ${lcun}@gauss "/bin/sh" << EOF > gaussicc.log 2>&1 &
    cd $LCTOPDIR/$VERSION/test
    umask 002
    PATH=usr/local/intel/compiler91/bin:/usr/local/bin:/bin:/usr/bin:/usr/bin/X11:/usr/lib/mpi/bin:/usr/apps/bin:/usr/gapps/bin
    export PATH
    rm -rf chaos_3_x86_64_ib-icc
    mkdir chaos_3_x86_64_ib-icc
    cd chaos_3_x86_64_ib-icc
    . /usr/local/intel/compiler91/bin/iccvars.sh
    ../$TOPSRCDIR/configure \
    CFLAGS=-fPIC CXXFLAGS=-fPIC \
    CC=icc CXX=icc FC=ifort LDFLAGS=-lstdc++ \
    --prefix=$LCTOPDIR/$VERSION/chaos_3_x86_64_ib-icc \
    --disable-browser --disable-silex --without-hdf5 --without-szlib
    make -j 4
    make install
    make distclean
    ../$TOPSRCDIR/configure \
    CFLAGS=-fPIC CXXFLAGS=-fPIC \
    CC=icc CXX=icc FC=ifort LDFLAGS=-lstdc++ \
    --prefix=$LCTOPDIR/$VERSION/chaos_3_x86_64-icc \
    --disable-browser --without-readline --enable-silex \
    --with-Qt-dir=/usr/gapps/silo/qt/$QTRELEASE/chaos_3_x86_64-icc \
    --with-szlib=/usr/gapps/silo/szip/$SZIPRELEASE/chaos_3_x86_64-icc \
    --with-hdf5=/usr/gapps/silo/hdf5/$HDF5RELEASE/chaos_3_x86_64-icc/include,/usr/gapps/silo/hdf5/$HDF5RELEASE/chaos_3_x86_64-icc/lib
    make -j 4 check
    make install
    gmake bindir=/usr/gapps/bin/chaos_3_x86_64 install-exec
    gmake bindir=/usr/gapps/bin/chaos_3_x86_64_elan4 install-exec
    gmake bindir=/usr/gapps/bin/chaos_3_x86_64_ib install-exec
    chmod -R g+w $LCTOPDIR/$VERSION/chaos_3_x86_64-icc
    for FILE in $BININSTALLS
    do chmod -R g+w /usr/gapps/bin/chaos_3_x86_64/$FILE
       chmod -R g+w /usr/gapps/bin/chaos_3_x86_64_elan4/$FILE
       chmod -R g+w /usr/gapps/bin/chaos_3_x86_64_ib/$FILE
    done
    make distclean
EOF
}
rhea() {
  rheagcc
  rheaicc - icc builds of hdf5/szip inaccessible
}
rheagcc() {
  ssh ${lcun}@rhea "/bin/sh" << EOF > rheagcc.log 2>&1 &
    cd $LCTOPDIR/$VERSION/test
    umask 002
    PATH=usr/local/intel/compiler91/bin:/usr/local/bin:/bin:/usr/bin:/usr/bin/X11:/usr/lib/mpi/bin:/usr/apps/bin:/usr/gapps/bin
    export PATH
    rm -rf chaos_3_x86_64
    mkdir chaos_3_x86_64
    cd chaos_3_x86_64
    ../$TOPSRCDIR/configure \
    CFLAGS=-fPIC CXXFLAGS=-fPIC \
    CC=gcc CXX=g++ \
    FC=g77 F77=g77 \
    FFLAGS=-Wno-globals F77FLAGS=-Wno-globals FCFLAGS=-Wno-globals \
    --prefix=$LCTOPDIR/$VERSION/chaos_3_x86_64-gcc \
    --disable-browser --disable-silex --without-hdf5 --without-szlib 
    make -j 4
    make install
    make distclean
    ../$TOPSRCDIR/configure \
    CFLAGS=-fPIC CXXFLAGS=-fPIC \
    CC=gcc CXX=g++ \
    FC=g77 F77=g77 \
    FFLAGS=-Wno-globals F77FLAGS=-Wno-globals FCFLAGS=-Wno-globals \
    --prefix=$LCTOPDIR/$VERSION/chaos_3_x86_64-gcc \
    --without-szlib
    make -j 4 check
    make install
    chmod -R g+w $LCTOPDIR/$VERSION/chaos_3_x86_64-gcc
    make distclean
EOF
}
rheaicc() {
  ssh ${lcun}@rhea "/bin/sh" << EOF > rheaicc.log 2>&1 &
    cd $LCTOPDIR/$VERSION/test
    umask 002
    PATH=usr/local/intel/compiler91/bin:/usr/local/bin:/bin:/usr/bin:/usr/bin/X11:/usr/lib/mpi/bin:/usr/apps/bin:/usr/gapps/bin
    export PATH
    rm -rf chaos_3_x86_64-icc
    mkdir chaos_3_x86_64-icc
    cd chaos_3_x86_64-icc
    . /usr/local/intel/compiler91/bin/iccvars.sh
    ../$TOPSRCDIR/configure \
    CFLAGS=-fPIC CXXFLAGS=-fPIC \
    CC=icc CXX=icc FC=ifort LDFLAGS=-lstdc++ \
    --prefix=$LCTOPDIR/$VERSION/chaos_3_x86_64-icc \
    --disable-browser --disable-silex --without-hdf5 --without-szlib 
    make -j 4
    make install
    make distclean
    ../$TOPSRCDIR/configure \
    CFLAGS=-fPIC CXXFLAGS=-fPIC \
    CC=icc CXX=icc FC=ifort LDFLAGS=-lstdc++ \
    --prefix=$LCTOPDIR/$VERSION/chaos_3_x86_64-icc --disable-silex \
    --with-szlib=/usr/gapps/silo/szip/$SZIPRELEASE/chaos_3_x86_64-icc \
    --with-hdf5=/usr/gapps/silo/hdf5/$HDF5RELEASE/chaos_3_x86_64-icc/include,/usr/gapps/silo/hdf5/$HDF5RELEASE/chaos_3_x86_64-icc/lib
    make -j 4 check
    make install
    ln -s $LCTOPDIR/$VERSION/chaos_3_x86_64-gcc/bin/silex \
       $LCTOPDIR/$VERSION/chaos_3_x86_64-icc/bin/silex
    chmod -R g+w $LCTOPDIR/$VERSION/chaos_3_x86_64-icc
    make distclean
EOF
}

bgltest() {
  ssh ${lcun}@bgl "/bin/sh" << EOF > bgltest.log 2>&1 &
    cd $LCTOPDIR/$VERSION/test
    umask 002
    PATH=/opt/ibmcmp/vacpp/7.0/bin:/opt/ibmcmp/xlf/9.1/bin:/usr/local/bin:/bin:/usr/bin:/usr/bin/X11:/usr/lib/mpi/bin:/usr/apps/bin:/usr/gapps/bin
    export PATH
    rm -rf sles_9_ppc64
    mkdir sles_9_ppc64
    cd sles_9_ppc64
    ../$TOPSRCDIR/configure \
    CC='xlc' CXX='xlC' FC='fort77' \
    --prefix=$LCTOPDIR/$VERSION/sles_9_ppc64 \
    --without-readline --without-hdf5
    make -j 4 CC='blrts_xlc' CXX='blrts_xlC' FC='blrts_fort77' install
    chmod -R g+w $LCTOPDIR/$VERSION/sles_9_ppc64
    make distclean
EOF
}
bgl() {
  ssh ${lcun}@bgl "/bin/sh" << EOF > bgl.log 2>&1 &
    cd $LCTOPDIR/$VERSION/test
    umask 002
    PATH=/opt/ibmcmp/vac/7.0/bin:/opt/ibmcmp/xlf/9.1/bin:/usr/local/bin:/bin:/usr/bin:/usr/bin/X11:/usr/lib/mpi/bin:/usr/apps/bin:/usr/gapps/bin
    export PATH
    rm -rf sles_9_ppc64
    mkdir sles_9_ppc64
    cd sles_9_ppc64
    ../$TOPSRCDIR/configure \
    CC='xlc' \
    --prefix=$LCTOPDIR/$VERSION/sles_9_ppc64 \
    --without-readline \
    --with-hdf5=/usr/local/tools/hdf5/hdf5-1.6.5/serial_frontend/include,/usr/local/tools/hdf5/hdf5-1.6.5/serial_frontend/lib
    gmake -j 4 install
    gmake distclean
    ../$TOPSRCDIR/configure \
    CC='mpxlc' ac_cv_type_off64_t=yes ac_cv_sizeof_off64_t=8 \
    --prefix=$LCTOPDIR/$VERSION/sles_9_ppc64 \
    --disable-browser --without-readline --without-hdf5
    gmake -j 4 install
    gmake distclean
    ../$TOPSRCDIR/configure \
    CC='mpxlc' ac_cv_type_off64_t=yes ac_cv_sizeof_off64_t=8 \
    --prefix=$LCTOPDIR/$VERSION/sles_9_ppc64 \
    --disable-browser --without-readline \
    --with-szlib=/usr/gapps/silo/szip/$SZIPRELEASE/sles_9_ppc64 \
    --with-hdf5=/usr/gapps/silo/hdf5/$HDF5RELEASE/sles_9_ppc64/include,/usr/gapps/silo/hdf5/$HDF5RELEASE/sles_9_ppc64/lib
    gmake -j 4 install
    gmake bindir=/usr/gapps/bin/sles_9_ppc64 install-exec
    chmod -R g+w $LCTOPDIR/$VERSION/sles_9_ppc64
    chmod -R g+w /usr/gapps/bin/sles_9_ppc64
    make distclean
EOF
}

if [ $# -lt 1 ] ; then
  usage
  exit 2
fi
GROUPNAME=`id -gn`
if [ "$GROUPNAME" != "visit" ] ; then
   echo "You must be in the \"visit\" group to run $0. Do \"newgrp visit\"."
   exit 2
fi
umask 002
VERSION=$1
shift
if [ "$1" = "-lc-username" ] ; then
    lcun=$2
    shift 2
fi
if [ "$1" = "-bdiv-username" ] ; then
    bdun=$2
    shift 2
fi
if [ "$1" = "-bdiv-host" ] ; then
    bdhost=$2
    shift 2
fi

TARFILE="silo-$VERSION.tar.gz"
TOPSRCDIR="silo-$VERSION"
  ssh ${bdun}@${bdhost} "/bin/sh -c \"(umask 002; \
  mkdir $BDTOPDIR/$VERSION; \
  mkdir $BDTOPDIR/$VERSION/test)\" "
  ssh ${lcun}@uv "/bin/sh -c \"(umask 002; \
  mkdir $LCTOPDIR/$VERSION; \
  mkdir $LCTOPDIR/$VERSION/test)\" "
if [ -e $TARFILE ] ; then
  scp $TARFILE ${bdun}@${bdhost}:$BDTOPDIR/$VERSION
  scp $TARFILE ${lcun}@uv:$LCTOPDIR/$VERSION

  ssh ${bdun}@${bdhost} "/bin/sh -c \"(umask 002; \
   cd $BDTOPDIR/$VERSION/test; \
   chmod a+r,g+w ../$TARFILE; \
   tar zxf ../$TARFILE)\" "
  ssh ${lcun}@uv "/bin/sh -c \"(umask 002; \
   cd $LCTOPDIR/$VERSION/test; \
   chmod a+r,g+w ../$TARFILE; \
   tar zxf ../$TARFILE)\" "
fi

if [ $# -lt 1 ] ; then
  localhost
  sunset
  purple
  uv
  gauss
  lilac
  rhea
  bgl
else
 while [ "$*" != "" ]
 do
  case $1 in
    all|-a*)
      localhost
      sunset
      purple
      uv
      gauss
      lilac
      rhea
      bgl
      shift;;
    local*pgc|-local*pgc)
      localhostpgc
      shift;;
    local*icc|-local*icc)
      localhosticc
      shift;;
    local*gcc|-local*gcc)
      localhostgcc
      shift;;
    localhost|-lo*)
      localhost
      shift;;
    sun*gcc|-sun*gcc)
      sunsetgcc
      shift;;
    sun*cc|-sun*cc)
      sunsetcc
      shift;;
    sun*|-sun*)
      sunset
      shift;;
    purple32|-pu*32)
      purple32
      shift;;
    purple64|-pu*64)
      purple64
      shift;;
    purple|-pu*)
      purple
      shift;;
    uv32|-uv*32)
      uv32
      shift;;
    uv64|-uv*64)
      uv64
      shift;;
    uv|-uv*)
      uv
      shift;;
    sccc|-sccc)
      sccc
      shift;;
    sc|-sc)
      sc
      shift;;
    gaus*icc|-gs*icc)
      gaussicc
      shift;;
    gaus*gcc|-gs*gcc)
      gaussgcc
      shift;;
    gaus*|-gs*)
      gauss
      shift;;
    rhea*icc|-rh*icc)
      rheaicc
      shift;;
    rhea*gcc|-rh*gcc)
      rheagcc
      shift;;
    rhea*|-rh*)
      rhea
      shift;;
    lil*|-li*)
      lilac
      shift;;
    slic*icc|-sl*icc)
      slicicc
      shift;;
    slic*gcc|-sl*gcc)
      slicgcc
      shift;;
    slic*|-sl*)
      slic
      shift;;
    bgltest|-bgltest)
      bgltest
      shift;;
    bgl|-bgl)
      bgl
      shift;;
    sh*|-sh*)
      shar
      shift;;
    *)
      shift;;
  esac
 done
fi
