#!/bin/sh
#-----------------------------------------------------------------------
#
# SILO-INSTALL-OPEN - Install the silo distributions on the open
#                     network.
#
# Author: Eric Brugger
# Date:   April 5, 2001
#
# Usage:
#    silo-install-open -v <version> -l <LC username>
#
#-----------------------------------------------------------------------

test=no

user=`whoami`
lc_username=$user

#
# Set the user e-mail address.
#
emailName=brugger1@llnl.gov
case $user in
   ahern)
      emailName=ahern1@llnl.gov
      ;;
   kbonnell)
      emailName=bonnell2@llnl.gov
      ;;
   brugger)
      emailName=brugger1@llnl.gov
      ;;
   childs)
      emailName=childs3@llnl.gov
      ;;
   jennings)
      emailName=jennings4@llnl.gov
      ;;
   meredith)
      emailName=meredith6@llnl.gov
      ;;
   mcmiller)
      emailName=miller86@llnl.gov
      ;;
   miller)
      emailName=miller86@llnl.gov
      ;;
   murguia)
      emailName=murguia1@llnl.gov
      ;;
   whitlocb)
      emailName=whitlock2@llnl.gov
      ;;
esac

#
# Parse the execute line, providing default values for error checking.
#
hoth=true
sunspot=true
quad=true
gps=true
berg=true
pengra=true
thunder=true

ver=undefined

#
# The loop is executed once for each symbol on the execute line.  This means
# that $1 may be blank for later executions of the loop if any "shift 2"
# commands are executed.  The variable abc is not used in the loop.
#
for abc
do
   case $1 in
      -none)
	 hoth=false
         sunspot=false
         quad=false
         gps=false
         berg=false
         pengra=false
         thunder=false
         shift
         ;;
      -hoth)
         hoth=false
         shift
         ;;
      +hoth)
         hoth=true
         shift
         ;;
      -sunspot)
         sunspot=false
         shift
         ;;
      +sunspot)
         sunspot=true
         shift
         ;;
      -quad)
         quad=false
         shift
         ;;
      +quad)
         quad=true
         shift
         ;;
      -gps)
         gps=false
         shift
         ;;
      +gps)
         gps=true
         shift
         ;;
      -berg)
         berg=false
         shift
         ;;
      +berg)
         berg=true
         shift
         ;;
      -pengra)
         pengra=false
         shift
         ;;
      +pengra)
         pengra=true
         shift
         ;;
      -thunder)
         thunder=false
         shift
         ;;
      +thunder)
         thunder=true
         shift
         ;;
      -v)
         ver=$2
         shift 2
         ;;
      -l)
         lc_username=$2
         shift 2
         ;;
   esac
done

#
# Check that both the version and distribution name were provided.
#
if [ $ver = undefined ] ; then
   echo "Usage: -v <version>"
   exit
fi

#
# Install on hoth.
#
rm -f hoth
cat <<EOF > hoth
#!/bin/sh
cd /usr/gapps/silo
if test ! -e $ver ; then
   mkdir $ver
fi
if test -e $ver/linux_rhel3_gcc_3.2.3 ; then
   rm -rf $ver/linux_rhel3_gcc_3.2.3
fi
mkdir $ver/linux_rhel3_gcc_3.2.3
mkdir $ver/linux_rhel3_gcc_3.2.3/bin
mkdir $ver/linux_rhel3_gcc_3.2.3/include
mkdir $ver/linux_rhel3_gcc_3.2.3/lib
cd /usr/tmp/$user/hoth/silobuild
cp bin/browser           /usr/gapps/silo/$ver/linux_rhel3_gcc_3.2.3/bin
cp bin/silock            /usr/gapps/silo/$ver/linux_rhel3_gcc_3.2.3/bin
cp bin/silodiff          /usr/gapps/silo/$ver/linux_rhel3_gcc_3.2.3/bin
cp include/silo.h        /usr/gapps/silo/$ver/linux_rhel3_gcc_3.2.3/include
cp include/silo.inc      /usr/gapps/silo/$ver/linux_rhel3_gcc_3.2.3/include
cp include/sdx.h         /usr/gapps/silo/$ver/linux_rhel3_gcc_3.2.3/include
cp include/sdx.inc       /usr/gapps/silo/$ver/linux_rhel3_gcc_3.2.3/include
cp lib/libsilo.a         /usr/gapps/silo/$ver/linux_rhel3_gcc_3.2.3/lib
cp lib/libsiloh5.a       /usr/gapps/silo/$ver/linux_rhel3_gcc_3.2.3/lib
cp lib/Silo.so           /usr/gapps/silo/$ver/linux_rhel3_gcc_3.2.3/lib
chgrp -R meshtv /usr/gapps/silo/$ver
find /usr/gapps/silo/$ver -type d -exec chmod 775 {} \;
find /usr/gapps/silo/$ver/linux_rhel3_gcc_3.2.3 -type f -exec chmod 664 {} \;
chmod 775 /usr/gapps/silo/$ver/linux_rhel3_gcc_3.2.3/bin/*
rm -f resultlog
echo "        install of silo on hoth"                    > resultlog 2>&1
echo "       -------------------------"                   >> resultlog 2>&1
echo ""                                                   >> resultlog 2>&1
df -k /usr/gapps/silo                                     >> resultlog 2>&1
echo ""                                                   >> resultlog 2>&1
ls -l /usr/gapps/silo/$ver/linux_rhel3_gcc_3.2.3/bin      >> resultlog 2>&1
ls -l /usr/gapps/silo/$ver/linux_rhel3_gcc_3.2.3/include  >> resultlog 2>&1
ls -l /usr/gapps/silo/$ver/linux_rhel3_gcc_3.2.3/lib      >> resultlog 2>&1
mail $emailName < resultlog
EOF

if [ $hoth = true ]
then
   if [ $test = no ] ; then
      scp hoth hoth:install_silo_hoth
      ssh hoth "chmod 750 install_silo_hoth;./install_silo_hoth"
   fi
fi

#
# Install on sunspot.
#
rm -f sunspot
cat <<EOF > sunspot
#!/bin/sh
cd /usr/gapps/silo
if test ! -d $ver ; then
   mkdir $ver
fi
if test -d $ver/sunos_57 ; then
   rm -rf $ver/sunos_57
fi
mkdir $ver/sunos_57
mkdir $ver/sunos_57/bin
mkdir $ver/sunos_57/include
mkdir $ver/sunos_57/lib
cd /export/scratch/$user/sunspot/silobuild
cp bin/browser           /usr/gapps/silo/$ver/sunos_57/bin
cp bin/silock            /usr/gapps/silo/$ver/sunos_57/bin
cp bin/silodiff          /usr/gapps/silo/$ver/sunos_57/bin
cp include/silo.h        /usr/gapps/silo/$ver/sunos_57/include
cp include/silo.inc      /usr/gapps/silo/$ver/sunos_57/include
cp include/sdx.h         /usr/gapps/silo/$ver/sunos_57/include
cp include/sdx.inc       /usr/gapps/silo/$ver/sunos_57/include
cp lib/libsilo.a         /usr/gapps/silo/$ver/sunos_57/lib
cp lib/libsiloh5.a       /usr/gapps/silo/$ver/sunos_57/lib
cp lib/Silo.so           /usr/gapps/silo/$ver/sunos_57/lib
chgrp -R swat /usr/gapps/silo/$ver
find /usr/gapps/silo/$ver -type d -exec chmod 775 {} \;
find /usr/gapps/silo/$ver/sunos_57 -type f -exec chmod 664 {} \;
chmod 775 /usr/gapps/silo/$ver/sunos_57/bin/*
rm -f resultlog
echo "        install of silo on sunspot"         > resultlog 2>&1
echo "       ----------------------------"        >> resultlog 2>&1
echo ""                                           >> resultlog 2>&1
df -k /usr/gapps/silo                             >> resultlog 2>&1
echo ""                                           >> resultlog 2>&1
ls -l /usr/gapps/silo/$ver/sunos_57/bin           >> resultlog 2>&1
ls -l /usr/gapps/silo/$ver/sunos_57/include       >> resultlog 2>&1
ls -l /usr/gapps/silo/$ver/sunos_57/lib           >> resultlog 2>&1
mail $emailName < resultlog
EOF

if [ $sunspot = true ]
then
   if [ $test = no ] ; then
      scp sunspot sunspot:install_silo_sunspot
      ssh sunspot "chmod 750 install_silo_sunspot;./install_silo_sunspot"
   fi
fi

#
# Install on quad.
#
rm -f quad
cat <<EOF > quad
#!/bin/sh
cd /usr/gapps/silo
if test ! -d $ver ; then
   mkdir $ver
fi
if test -d $ver/irix_6.5_n32 ; then
   rm -rf $ver/irix_6.5_n32 
fi
if test -d $ver/irix_6.5_64 ; then
   rm -rf $ver/irix_6.5_64 
fi
mkdir $ver/irix_6.5_n32
mkdir $ver/irix_6.5_n32/bin
mkdir $ver/irix_6.5_n32/include
mkdir $ver/irix_6.5_n32/lib
mkdir $ver/irix_6.5_64
mkdir $ver/irix_6.5_64/bin
mkdir $ver/irix_6.5_64/include
mkdir $ver/irix_6.5_64/lib
cd /usr/tmp/$user/quad/silobuild
cp bin/browser           /usr/gapps/silo/$ver/irix_6.5_n32/bin
cp bin/silock            /usr/gapps/silo/$ver/irix_6.5_n32/bin
cp bin/silodiff          /usr/gapps/silo/$ver/irix_6.5_n32/bin
cp include/silo.h        /usr/gapps/silo/$ver/irix_6.5_n32/include
cp include/silo.inc      /usr/gapps/silo/$ver/irix_6.5_n32/include
cp include/sdx.h         /usr/gapps/silo/$ver/irix_6.5_n32/include
cp include/sdx.inc       /usr/gapps/silo/$ver/irix_6.5_n32/include
cp libn32/libsilo.a      /usr/gapps/silo/$ver/irix_6.5_n32/lib
cp libn32/libsiloh5.a    /usr/gapps/silo/$ver/irix_6.5_n32/lib
cp bin/browser           /usr/gapps/silo/$ver/irix_6.5_64/bin
cp bin/silock            /usr/gapps/silo/$ver/irix_6.5_64/bin
cp bin/silodiff          /usr/gapps/silo/$ver/irix_6.5_64/bin
cp include/silo.h        /usr/gapps/silo/$ver/irix_6.5_64/include
cp include/silo.inc      /usr/gapps/silo/$ver/irix_6.5_64/include
cp include/sdx.h         /usr/gapps/silo/$ver/irix_6.5_64/include
cp include/sdx.inc       /usr/gapps/silo/$ver/irix_6.5_64/include
cp lib64/libsilo.a       /usr/gapps/silo/$ver/irix_6.5_64/lib
cp lib64/libsiloh5.a     /usr/gapps/silo/$ver/irix_6.5_64/lib
chgrp -R swat /usr/gapps/silo/$ver
find /usr/gapps/silo/$ver -type d -exec chmod 775 {} \;
find /usr/gapps/silo/$ver/irix_6.5_* -type f -exec chmod 664 {} \;
chmod 775 /usr/gapps/silo/$ver/irix_6.5_*/bin/*
rm -f resultlog
echo "        install of silo on quad"           > resultlog 2>&1
echo "       -------------------------"          >> resultlog 2>&1
echo ""                                          >> resultlog 2>&1
df -k /usr/gapps/silo                            >> resultlog 2>&1
echo ""                                          >> resultlog 2>&1
ls -l /usr/gapps/silo/$ver/irix_6.5_*/bin        >> resultlog 2>&1
ls -l /usr/gapps/silo/$ver/irix_6.5_*/include    >> resultlog 2>&1
ls -l /usr/gapps/silo/$ver/irix_6.5_*/lib        >> resultlog 2>&1
mail $emailName < resultlog
EOF

if [ $quad = true ]
then
   if [ $test = no ] ; then
      scp quad quad:install_silo_quad
      ssh quad "chmod 750 install_silo_quad;./install_silo_quad"
   fi
fi

#
# Install on gps.
#
rm -f gps
cat <<EOF > gps
#!/bin/sh
cd /usr/gapps/silo
if test ! -e $ver ; then
   mkdir $ver
fi
if test -e $ver/tru64_5 ; then
   rm -rf $ver/tru64_5
fi
mkdir $ver/tru64_5
mkdir $ver/tru64_5/bin
mkdir $ver/tru64_5/include
mkdir $ver/tru64_5/lib
cd /nfs/tmp0/$lc_username/gps/silobuild
cp bin/browser           /usr/gapps/silo/$ver/tru64_5/bin
cp bin/silock            /usr/gapps/silo/$ver/tru64_5/bin
cp bin/silodiff          /usr/gapps/silo/$ver/tru64_5/bin
cp include/silo.h        /usr/gapps/silo/$ver/tru64_5/include
cp include/silo.inc      /usr/gapps/silo/$ver/tru64_5/include
cp include/sdx.h         /usr/gapps/silo/$ver/tru64_5/include
cp include/sdx.inc       /usr/gapps/silo/$ver/tru64_5/include
cp lib/libsilo.a         /usr/gapps/silo/$ver/tru64_5/lib
cp lib/libsiloh5.a       /usr/gapps/silo/$ver/tru64_5/lib
chgrp -R swat /usr/gapps/silo/$ver
find /usr/gapps/silo/$ver -type d -exec chmod 775 {} \;
find /usr/gapps/silo/$ver/tru64_5 -type f -exec chmod 664 {} \;
chmod 775 /usr/gapps/silo/$ver/tru64_5/bin/*
rm -f resultlog
echo "        install of silo on gps"             > resultlog 2>&1
echo "       ------------------------"            >> resultlog 2>&1
echo ""                                           >> resultlog 2>&1
df -k /usr/gapps/silo                             >> resultlog 2>&1
echo ""                                           >> resultlog 2>&1
ls -l /usr/gapps/silo/$ver/tru64_5/bin            >> resultlog 2>&1
ls -l /usr/gapps/silo/$ver/tru64_5/include        >> resultlog 2>&1
ls -l /usr/gapps/silo/$ver/tru64_5/lib            >> resultlog 2>&1
mail $emailName < resultlog
EOF

if [ $gps = true ]
then
   if [ $test = no ] ; then
      scp gps $lc_username@gps15:install_silo_gps
      ssh gps15 -l $lc_username "chmod 750 install_silo_gps;./install_silo_gps"
   fi
fi

#
# Install on berg.
#
rm -f berg
cat <<EOF > berg
#!/bin/sh
cd /usr/gapps/silo
if test ! -e $ver ; then
   mkdir $ver
fi
if test -e $ver/aix_5_ll ; then
   rm -rf $ver/aix_5_ll
fi
if test -e $ver/aix_5_64_fed ; then
   rm -f $ver/aix_5_64_fed
fi
mkdir $ver/aix_5_ll
mkdir $ver/aix_5_ll/bin
mkdir $ver/aix_5_ll/include
mkdir $ver/aix_5_ll/lib
ln -s aix_5_ll $ver/aix_5_64_fed
cd /nfs/tmp0/$lc_username/berg/silobuild
cp bin/browser           /usr/gapps/silo/$ver/aix_5_ll/bin
cp bin/silock            /usr/gapps/silo/$ver/aix_5_ll/bin
cp bin/silodiff          /usr/gapps/silo/$ver/aix_5_ll/bin
cp include/silo.h        /usr/gapps/silo/$ver/aix_5_ll/include
cp include/silo.inc      /usr/gapps/silo/$ver/aix_5_ll/include
cp include/sdx.h         /usr/gapps/silo/$ver/aix_5_ll/include
cp include/sdx.inc       /usr/gapps/silo/$ver/aix_5_ll/include
cp lib/libsilo.a         /usr/gapps/silo/$ver/aix_5_ll/lib
cp lib/libsiloh5.a       /usr/gapps/silo/$ver/aix_5_ll/lib
chgrp -R swat /usr/gapps/silo/$ver
find /usr/gapps/silo/$ver -type d -exec chmod 775 {} \;
find /usr/gapps/silo/$ver/aix_5_ll -type f -exec chmod 664 {} \;
chmod 775 /usr/gapps/silo/$ver/aix_5_ll/bin/*
rm -f resultlog
echo "        install of silo on berg"            > resultlog 2>&1
echo "       --------------------------"          >> resultlog 2>&1
echo ""                                           >> resultlog 2>&1
df -k /usr/gapps/silo                             >> resultlog 2>&1
echo ""                                           >> resultlog 2>&1
ls -l /usr/gapps/silo/$ver/aix_5_ll/bin           >> resultlog 2>&1
ls -l /usr/gapps/silo/$ver/aix_5_ll/include       >> resultlog 2>&1
ls -l /usr/gapps/silo/$ver/aix_5_ll/lib           >> resultlog 2>&1
mail $emailName < resultlog
EOF

if [ $berg = true ]
then
   if [ $test = no ] ; then
      scp berg $lc_username@berg:install_silo_berg
      ssh berg -l $lc_username "chmod 750 install_silo_berg;./install_silo_berg"
   fi
fi

#
# Install on pengra.
#
rm -f pengra
cat <<EOF > pengra
#!/bin/sh
cd /usr/gapps/silo
if test ! -e $ver ; then
   mkdir $ver
fi
if test -e $ver/chaos_3_x86_elan3 ; then
   rm -rf $ver/chaos_3_x86_elan3
fi
mkdir $ver/chaos_3_x86_elan3
mkdir $ver/chaos_3_x86_elan3/bin
mkdir $ver/chaos_3_x86_elan3/include
mkdir $ver/chaos_3_x86_elan3/lib
ln -s chaos_3_x86_elan3 $ver/chaos_3_x86
cd /nfs/tmp0/$lc_username/pengra/silobuild
cp bin/browser           /usr/gapps/silo/$ver/chaos_3_x86_elan3/bin
cp bin/silock            /usr/gapps/silo/$ver/chaos_3_x86_elan3/bin
cp bin/silodiff          /usr/gapps/silo/$ver/chaos_3_x86_elan3/bin
cp include/silo.h        /usr/gapps/silo/$ver/chaos_3_x86_elan3/include
cp include/silo.inc      /usr/gapps/silo/$ver/chaos_3_x86_elan3/include
cp include/sdx.h         /usr/gapps/silo/$ver/chaos_3_x86_elan3/include
cp include/sdx.inc       /usr/gapps/silo/$ver/chaos_3_x86_elan3/include
cp lib/libsilo.a         /usr/gapps/silo/$ver/chaos_3_x86_elan3/lib
cp lib/libsiloh5.a       /usr/gapps/silo/$ver/chaos_3_x86_elan3/lib
cp lib/Silo.so           /usr/gapps/silo/$ver/chaos_3_x86_elan3/lib
chgrp -R swat /usr/gapps/silo/$ver
find /usr/gapps/silo/$ver -type d -exec chmod 775 {} \;
find /usr/gapps/silo/$ver/chaos_3_x86_elan3 -type f -exec chmod 664 {} \;
chmod 775 /usr/gapps/silo/$ver/chaos_3_x86_elan3/bin/*
rm -f resultlog
echo "        install of silo on pengra"              > resultlog 2>&1
echo "       ---------------------------"             >> resultlog 2>&1
echo ""                                               >> resultlog 2>&1
df -k /usr/gapps/silo                                 >> resultlog 2>&1
echo ""                                               >> resultlog 2>&1
ls -l /usr/gapps/silo/$ver/chaos_3_x86_elan3/bin      >> resultlog 2>&1
ls -l /usr/gapps/silo/$ver/chaos_3_x86_elan3/include  >> resultlog 2>&1
ls -l /usr/gapps/silo/$ver/chaos_3_x86_elan3/lib      >> resultlog 2>&1
mail $emailName < resultlog
EOF

if [ $pengra = true ]
then
   if [ $test = no ] ; then
      scp pengra $lc_username@pengra:install_silo_pengra
      ssh pengra -l $lc_username "chmod 750 install_silo_pengra;./install_silo_pengra"
   fi
fi

#
# Install on thunder.
#
rm -f thunder
cat <<EOF > thunder
#!/bin/sh
cd /usr/gapps/silo
if test ! -e $ver ; then
   mkdir $ver
fi
if test -e $ver/chaos_3_ia64_elan4 ; then
   rm -rf $ver/chaos_3_ia64_elan4
fi
mkdir $ver/chaos_3_ia64_elan4
mkdir $ver/chaos_3_ia64_elan4/gcc
mkdir $ver/chaos_3_ia64_elan4/gcc/bin
mkdir $ver/chaos_3_ia64_elan4/gcc/include
mkdir $ver/chaos_3_ia64_elan4/gcc/lib
mkdir $ver/chaos_3_ia64_elan4/icc
mkdir $ver/chaos_3_ia64_elan4/icc/bin
mkdir $ver/chaos_3_ia64_elan4/icc/include
mkdir $ver/chaos_3_ia64_elan4/icc/lib
cd /usr/tmp/$lc_username/thunder/silobuild
cp gcc/bin/browser       /usr/gapps/silo/$ver/chaos_3_ia64_elan4/gcc/bin
cp gcc/bin/silock        /usr/gapps/silo/$ver/chaos_3_ia64_elan4/gcc/bin
cp gcc/bin/silodiff      /usr/gapps/silo/$ver/chaos_3_ia64_elan4/gcc/bin
cp gcc/include/silo.h    /usr/gapps/silo/$ver/chaos_3_ia64_elan4/gcc/include
cp gcc/include/silo.inc  /usr/gapps/silo/$ver/chaos_3_ia64_elan4/gcc/include
cp gcc/include/sdx.h     /usr/gapps/silo/$ver/chaos_3_ia64_elan4/gcc/include
cp gcc/include/sdx.inc   /usr/gapps/silo/$ver/chaos_3_ia64_elan4/gcc/include
cp gcc/lib/libsilo.a     /usr/gapps/silo/$ver/chaos_3_ia64_elan4/gcc/lib
cp gcc/lib/libsiloh5.a   /usr/gapps/silo/$ver/chaos_3_ia64_elan4/gcc/lib
cp gcc/lib/Silo.so       /usr/gapps/silo/$ver/chaos_3_ia64_elan4/gcc/lib
cp icc/bin/browser       /usr/gapps/silo/$ver/chaos_3_ia64_elan4/icc/bin
cp icc/bin/silock        /usr/gapps/silo/$ver/chaos_3_ia64_elan4/icc/bin
cp icc/bin/silodiff      /usr/gapps/silo/$ver/chaos_3_ia64_elan4/icc/bin
cp icc/include/silo.h    /usr/gapps/silo/$ver/chaos_3_ia64_elan4/icc/include
cp icc/include/silo.inc  /usr/gapps/silo/$ver/chaos_3_ia64_elan4/icc/include
cp icc/include/sdx.h     /usr/gapps/silo/$ver/chaos_3_ia64_elan4/icc/include
cp icc/include/sdx.inc   /usr/gapps/silo/$ver/chaos_3_ia64_elan4/icc/include
cp icc/lib/libsilo.a     /usr/gapps/silo/$ver/chaos_3_ia64_elan4/icc/lib
cp icc/lib/libsiloh5.a   /usr/gapps/silo/$ver/chaos_3_ia64_elan4/icc/lib
cp icc/lib/Silo.so       /usr/gapps/silo/$ver/chaos_3_ia64_elan4/icc/lib
chgrp -R swat /usr/gapps/silo/$ver
find /usr/gapps/silo/$ver -type d -exec chmod 775 {} \;
find /usr/gapps/silo/$ver/chaos_3_ia64_elan4 -type f -exec chmod 664 {} \;
chmod 775 /usr/gapps/silo/$ver/chaos_3_ia64_elan4/{gcc,icc}/bin/*
rm -f resultlog
echo "        install of silo on thunder"                 > resultlog 2>&1
echo "       ----------------------------"                >> resultlog 2>&1
echo ""                                                   >> resultlog 2>&1
df -k /usr/gapps/silo                                     >> resultlog 2>&1
echo ""                                                   >> resultlog 2>&1
ls -l /usr/gapps/silo/$ver/chaos_3_ia64_elan4/gcc/bin     >> resultlog 2>&1
ls -l /usr/gapps/silo/$ver/chaos_3_ia64_elan4/gcc/include >> resultlog 2>&1
ls -l /usr/gapps/silo/$ver/chaos_3_ia64_elan4/gcc/lib     >> resultlog 2>&1
ls -l /usr/gapps/silo/$ver/chaos_3_ia64_elan4/icc/bin     >> resultlog 2>&1
ls -l /usr/gapps/silo/$ver/chaos_3_ia64_elan4/icc/include >> resultlog 2>&1
ls -l /usr/gapps/silo/$ver/chaos_3_ia64_elan4/icc/lib     >> resultlog 2>&1
mail $emailName < resultlog
EOF

if [ $thunder = true ]
then
   if [ $test = no ] ; then
      scp thunder $lc_username@thunder:install_silo_thunder
      ssh thunder3 -l $lc_username "chmod 750 install_silo_thunder;./install_silo_thunder"
   fi
fi

#
# Clean up.
#
if [ $test = no ] ; then
   rm -f hoth sunspot quad gps berg pengra thunder
fi
