#!/bin/sh
#set -x
FILELIST="./configure ./libtool ./aclocal.m4 \
./config/compile ./config/config.guess ./config/config.h.in \
./config/config.sub ./config/depcomp ./config/install-sh \
./config/ltmain.sh ./config/missing \
./clearcase_bin/Makefile.in \
./docs/Makefile.in ./config/Makefile.in ./tools/browser/Makefile.in \
./tools/silock/Makefile.in ./tools/python/Makefile.in \
./tools/Makefile.in ./tests/Makefile.in ./src/debug/Makefile.in \
./src/filters/Makefile.in ./src/netcdf/Makefile.in \
./src/silo/Makefile.in ./src/swat/Makefile.in \
./src/taurus/Makefile.in ./src/unknown/Makefile.in \
./src/pdb/Makefile.in ./src/pdb_drv/Makefile.in \
./src/score/Makefile.in ./src/hdf5_drv/Makefile.in \
./src/Makefile.in ./Makefile.in \
./tests/package.m4 ./tests/testsuite"
HOST=`/usr/gapps/silo/autotools/bin/config.guess`
AUTOTOOLS=/usr/gapps/silo/autotools/$HOST/bin
CT="/usr/atria/bin/cleartool"
CHECK=no  # don't do checkin and checkout by default
help () {
  printf "Usage: %s [-c|-o|-i|-h] [-d] Comment"
$0
  printf "\n"
  printf "Silo reconfigure script. This runs GNU autotools to rebuild\n"
  printf "configure, Makefile.in, config.h, etc., optionally checkout/in\n"
  printf "from clearcase the changed files.\n"
  printf "Options are:\n"
  printf "   -c  perform a clearcase checkout, autoreconf, and checkin.\n"
  printf "   -o  perform only a clearcase checkout then quit.\n"
  printf "   -i  perform only a clearcase checkin then quit.\n"
  printf "   -h  print this help message.\n"
  printf "   -d  turn on debugging.\n"
}
do_checkout()
{
for file in $FILELIST
do
  $CT co -c "" $file
done
}
do_checkin()
{
for file in $FILELIST
do
  $CT ci -c "$COMMENT" $file || $CT unco -rm $file
done
}
# somewhat of a hack
if test -x configure.ac ; then
  echo "must be in the same directory as ./configure to run this script"
  exit 1
fi
case $1 in
    -c|-check) 
        shift
        if [ $# -lt 1 ] ; then
          echo "must provide a checkin comment"
          exit 2
        fi
        COMMENT="$*" 
        CHECK=yes ;;
    -o|-co) 
        do_checkout
        exit;;
    -i|-ci) 
        shift
        if [ $# -lt 1 ] ; then
          echo "must provide a checkin comment"
          exit 2
        fi
        COMMENT="$*" 
        do_checkin
        exit;;
    -h|-help) 
        help
        exit;;
    -d|-debug) 
        set -xv
        shift;;
esac

if [ "CHECK" = "yes" ] ; then
  do_checkout
fi
##rm -Rf INSTALL aclocal.m4 configure autom4te.cache 
##cp /usr/apps/autoconf/2.59/share/autoconf/INSTALL INSTALL
##cp /usr/apps/libtool/1.5/share/aclocal/libtool.m4 aclocal.m4
##cp /usr/apps/libtool/1.5/share/aclocal/libtool.m4 config/acinclude.m4
#libtoolize --force --copy
#aclocal -I config
#autoheader --force --include=config
#automake --add-missing --copy --force-missing --foreign 
#autoconf --include=config
$AUTOTOOLS/autoreconf -vif
if [ "CHECK" = "yes" ] ; then
  do_checkin
fi
