#!/bin/sh
AUTOTOOLS=/groups/visit/miller/silo/autotools/linux-x86_64/bin
# somewhat of a hack
if test -x configure.ac ; then
  echo "must be in the same directory as ./configure to run this script"
  exit 1
fi
if test "`which autoreconf`" != $AUTOTOOLS/autoreconf; then
  echo "make sure your path is set to the correct version of autotools"
  exit 1
fi
$AUTOTOOLS/autoreconf -vif
