#!/bin/sh

#
# Modifications:
#   
#   Mark C. Miller, Wed Jul 14 21:04:10 PDT 2010
#   Completely re-wrote to use od instead of file command as that
#   has proven more reliable.
#

#
# Use octal dump (od) command to examine first few bytes of file.
# If do not find expected bytes of any of the formats we'd like
# to identify here, fall back to using the good ole' file command.
#
unknownFiles=
for f in $*; do
    headerBytes=$(od -c -N 10 $f)
    if test -n "$(echo $headerBytes | tr -d ' ' | grep '<<PDB:')"; then
        echo "$f: Portable Database (PDB) data"
    elif test -n "$(echo $headerBytes | tr -d ' \\' | grep 'HDFrn032')"; then
        echo "$f: Hierarchical Data Format version 5 (HDF5) data"
    else
        headerBytes=$(od -t x1 -N 4 $f)
        if test -n "$(echo $headerBytes | grep '0000000 0e 03 13 01')"; then
            echo "$f: Hierarchical Data Format version 4 (HDF4) data"
        else
	    unknownFiles="$unknownFiles $f"
        fi
    fi
done

#
# If we have any unknown files, use the ordinary file command on them.
#
if test -n "$unknownFiles"; then
    file $unknownFiles
fi
