# Modifications
#
#   Sean Ahern, Thu Mar 13 11:24:36 PST 1997
#   Added silo.inc and sdx.inc.
#
#   Sean Ahern, Fri Mar 14 13:09:24 PST 1997
#   Added all of the *.in files.
#
#   Sean Ahern, Fri Mar 14 14:56:46 PST 1997
#   Removed "Makefile" from the "not distributed" list.
#
#   Sean Ahern, June 18, 1997
#   Added "silo_f.h" to the list of distributed files.
#
#   Sean Ahern, Mon Oct 12 17:33:57 PDT 1998
#   Removed aio.h since we don't have AIO any more.
#
#   Jeremy Meredith, Mon Oct 11 12:24:54 PDT 1999
#   Added the GL symlink.

DISTRIB= SpiDraw.h pdb.h score.h sdx.h sdxproto.h silo.h silo_f.h \
         silo_drivers.h silo_private.h spi.h swat.h silo.inc sdx.inc \
         config.h.in make-depend-gnu.in make-depend-std.in \
         make-targets.in make-variables.in GL
NOT_DISTRIB= config.h.top config.h.bot
